"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createCaseWorkspace, getSavedCase, type SavedCaseDetail } from "@/lib/api";
import { RemedyWorkspace } from "@/components/remedy-workspace";

export function CaseDetailWorkspace({savedCaseId}:{savedCaseId:string}){
  const [data,setData]=useState<SavedCaseDetail|null>(null); const [error,setError]=useState(""); const [matterId,setMatterId]=useState<string|null>(null);
  useEffect(()=>{getSavedCase(savedCaseId).then((row)=>{setData(row);setMatterId(row.matter_id);}).catch((e)=>setError(e instanceof Error?e.message:"Unable to load case"));},[savedCaseId]);
  if(error)return <main className="page"><div className="notice-panel danger"><span>{error}</span></div></main>; if(!data)return <main className="page"><div className="loading-card">Loading case…</div></main>;
  const r=data.record; const petitioners=r.parties.filter(p=>p.side==="petitioner"); const respondents=r.parties.filter(p=>p.side==="respondent"); const pa=r.advocates.filter(a=>a.side==="petitioner"); const ra=r.advocates.filter(a=>a.side==="respondent");
  async function workspace(){const result=await createCaseWorkspace(savedCaseId);setMatterId(result.matter_id);}
  return <main className="page"><div className="hero-row matter-hero"><div><div className="eyebrow">Case workspace</div><h1 className="page-title">{r.case_title||`${r.case_type||"Case"} ${r.case_number}`}</h1><p className="page-subtitle">{[r.case_type,r.case_number+(r.year?`/${r.year}`:""),r.cnr].filter(Boolean).join(" · ")}</p></div><div className="hero-actions">{matterId?<Link className="button secondary" href={`/matters/${matterId}`}>Open Matter Workspace</Link>:<button className="button secondary" type="button" onClick={workspace}>Open Workspace</button>}</div></div>
    <section className="case-status-strip"><div><span>Status</span><strong>{r.status||"Unknown"}</strong></div><div><span>Stage</span><strong>{r.case_stage||"Unknown"}</strong></div><div><span>Next hearing</span><strong>{r.next_hearing_date||"—"}</strong></div><div><span>Source</span><strong>{r.source_name}</strong></div></section>
    {data.stale?<div className="notice-panel warning"><span>Cached case data may be stale. Refresh through the supported official-source connector/user-assisted flow before relying on current status.</span></div>:null}
    <div className="grid-2 case-overview-grid"><section className="card"><div className="card-title">Court & case</div><dl className="case-dl"><dt>Court</dt><dd>{r.court_name}</dd><dt>Location</dt><dd>{[r.district,r.state].filter(Boolean).join(", ")||"—"}</dd><dt>Judge / bench</dt><dd>{r.judge||r.bench||"—"}</dd><dt>Filing</dt><dd>{r.filing_date||"—"}</dd><dt>Registration</dt><dd>{r.registration_date||"—"}</dd></dl></section><section className="card"><div className="card-title">Parties & advocates</div><div className="party-block"><span>Petitioner(s)</span><strong>{petitioners.map(p=>p.name).join(", ")||"—"}</strong><small>{pa.map(a=>a.name).join(", ")||"Advocate not available"}</small></div><div className="party-block"><span>Respondent(s)</span><strong>{respondents.map(p=>p.name).join(", ")||"—"}</strong><small>{ra.map(a=>a.name).join(", ")||"Advocate not available"}</small></div></section></div>
    <section className="card"><div className="card-header"><div className="card-title">Acts / Sections</div></div><div className="act-chips">{r.acts.length?r.acts.map((a,i)=><span className="quiet-badge" key={i}>{a.act_name}{a.sections.length?` · ${a.sections.join(", ")}`:""}</span>):<span className="quiet-text">No Act/section data available.</span>}</div></section>
    <div className="grid-2"><section className="card"><div className="card-header"><div className="card-title">Case timeline</div></div><div className="case-timeline">{r.hearing_history.slice().reverse().map((h,i)=><div className="case-timeline-row" key={`${h.hearing_date}-${i}`}><strong>{h.hearing_date}</strong><div><span>{h.purpose_or_stage||"Hearing"}</span><small>{h.result_or_note||h.judge_or_bench||""}</small></div></div>)}</div></section><section className="card"><div className="card-header"><div className="card-title">Orders / judgments</div></div>{[...r.orders.map(o=>({date:o.order_date,title:o.title||o.order_type||"Order",url:o.document_url||o.source_url})),...r.judgments.map(j=>({date:j.decision_date,title:j.title||j.citation||"Judgment",url:j.document_url||j.source_url}))].map((o,i)=><div className="order-row" key={i}><div><strong>{o.title}</strong><span>{o.date||"Date unavailable"}</span></div>{o.url?<a href={o.url} target="_blank" rel="noreferrer">Open ↗</a>:null}</div>)}</section></div>
    {data.changes.length?<section className="card case-changes"><div className="card-header"><div className="card-title">What changed since last time?</div></div>{data.changes.slice(0,12).map(c=><div className="change-row" key={c.id}><span className={`change-kind ${c.change_type}`}>{c.change_type}</span><div><strong>{c.summary}</strong><small>{new Date(c.detected_at).toLocaleString("en-IN")}</small></div></div>)}</section>:null}
    <RemedyWorkspace matterId={matterId||undefined} savedCaseId={savedCaseId}/>
  </main>;
}
