"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import {
  ClientMoneyAccount, ClientMoneyDashboard, ClientMoneyEntry, ClientMoneyTransfer, CRMClient,
  createClientMoneyAccount, createClientMoneyDeposit, createClientMoneyTransfer,
  decideClientMoneyTransfer, executeClientMoneyTransfer, getClientMoneyAccounts,
  getClientMoneyDashboard, getClientMoneyEntries, getClientMoneyTransfers, getCRMClients,
} from "@/lib/api";
import { ReceiptIcon, ShieldIcon } from "@/components/icons";

type Tab = "overview" | "ledger" | "transfers";
const money = (v:string|number,c="INR") => { try{return new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:2}).format(Number(v||0));}catch{return `${c} ${Number(v||0).toFixed(2)}`;} };
const today=()=>new Date().toISOString().slice(0,10);

export function ClientMoneyWorkspace(){
  const [tab,setTab]=useState<Tab>("overview"); const [dash,setDash]=useState<ClientMoneyDashboard|null>(null);
  const [accounts,setAccounts]=useState<ClientMoneyAccount[]>([]); const [clients,setClients]=useState<CRMClient[]>([]);
  const [entries,setEntries]=useState<ClientMoneyEntry[]>([]); const [transfers,setTransfers]=useState<ClientMoneyTransfer[]>([]);
  const [selectedAccount,setSelectedAccount]=useState<string>(""); const [composer,setComposer]=useState<"account"|"deposit"|"transfer"|null>(null);
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const refresh=useCallback(async()=>{try{const [d,a,c,t]=await Promise.all([getClientMoneyDashboard(),getClientMoneyAccounts(),getCRMClients(),getClientMoneyTransfers()]);setDash(d);setAccounts(a);setClients(c);setTransfers(t);const id=selectedAccount||a[0]?.id||"";setSelectedAccount(id);if(id)setEntries(await getClientMoneyEntries(id));setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load client-money workspace");}},[selectedAccount]);
  useEffect(()=>{void refresh();},[refresh]);
  const account=useMemo(()=>accounts.find(a=>a.id===selectedAccount)||null,[accounts,selectedAccount]);

  async function accountSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await createClientMoneyAccount({name:String(f.get("name")),currency:"INR",bank_name:String(f.get("bank_name")||"")||null,bank_account_last4:String(f.get("last4")||"")||null,bank_reference:String(f.get("bank_reference")||"")||null,require_separate_approver:true,notes:String(f.get("notes")||"")||null});setComposer(null);await refresh();}catch(err){setError(err instanceof Error?err.message:"Could not create account");}finally{setBusy(false)}}
  async function depositSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await createClientMoneyDeposit({account_id:String(f.get("account_id")),client_id:String(f.get("client_id")),amount:Number(f.get("amount")),currency:"INR",entry_date:String(f.get("entry_date")),reference:String(f.get("reference")||"")||null,description:String(f.get("description")||"Client money received")});setComposer(null);await refresh();setTab("ledger");}catch(err){setError(err instanceof Error?err.message:"Could not post receipt");}finally{setBusy(false)}}
  async function transferSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await createClientMoneyTransfer({account_id:String(f.get("account_id")),client_id:String(f.get("client_id")),amount:Number(f.get("amount")),currency:"INR",justification:String(f.get("justification"))});setComposer(null);await refresh();setTab("transfers");}catch(err){setError(err instanceof Error?err.message:"Could not request transfer");}finally{setBusy(false)}}
  async function decide(id:string,approve:boolean){setBusy(true);try{await decideClientMoneyTransfer(id,approve,approve?"Reviewed against client-money balance.":"Rejected during finance review.");await refresh();}catch(err){setError(err instanceof Error?err.message:"Decision failed");}finally{setBusy(false)}}
  async function execute(id:string){setBusy(true);try{await executeClientMoneyTransfer(id);await refresh();}catch(err){setError(err instanceof Error?err.message:"Execution failed");}finally{setBusy(false)}}

  return <main className="page finance-page">
    <div className="hero-row"><div><div className="eyebrow">Controlled funds</div><h1 className="page-title">Client money</h1><p className="page-subtitle">Balanced subledger, client/matter allocations, approval controls and reconciliation foundations. The ledger records money movement; it does not decide jurisdiction-specific trust-account rules.</p></div><button className="primary-button" onClick={()=>setComposer("deposit")}><ReceiptIcon/>Record receipt</button></div>
    {error?<div className="notice-panel billing-error"><strong>Attention</strong><span>{error}</span></div>:null}
    <div className="metrics billing-metrics"><div className="metric"><div className="metric-label">Bank control</div><div className="metric-value">{money(dash?.total_bank_balance||0)}</div><div className="metric-note">Computed from posted journal lines</div></div><div className="metric"><div className="metric-label">Pending transfers</div><div className="metric-value">{money(dash?.pending_transfer_total||0)}</div><div className="metric-note">{dash?.pending_transfer_count||0} awaiting action</div></div><div className="metric"><div className="metric-label">Reconciliation gap</div><div className="metric-value">{money(dash?.unreconciled_difference||0)}</div><div className="metric-note">Open reconciliation differences</div></div><div className="metric"><div className="metric-label">Accounts</div><div className="metric-value">{dash?.account_count||0}</div><div className="metric-note">Separate client-money bank controls</div></div></div>
    <div className="workspace-tabs billing-tabs">{(["overview","ledger","transfers"] as Tab[]).map(t=><button key={t} className={`workspace-tab ${tab===t?"active":""}`} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
    {tab==="overview"?<div className="grid-2"><section className="card"><div className="card-header"><div><div className="card-title">Accounts</div><div className="billing-copy">Balances are derived, never manually overwritten.</div></div><button className="secondary-button" onClick={()=>setComposer("account")}>New account</button></div>{accounts.length?accounts.map(a=><button key={a.id} className="billing-invoice-row" onClick={()=>{setSelectedAccount(a.id);setTab("ledger")}}><div><strong>{a.name}</strong><small>{a.bank_name||"Bank not recorded"}{a.bank_account_last4?` · ••••${a.bank_account_last4}`:""}</small></div><span className="quiet-badge">{a.status}</span></button>):<div className="empty-state compact"><div className="empty-state-title">No client-money account yet</div></div>}</section><section className="card"><div className="card-header"><div className="card-title">Control principles</div></div><div className="billing-control-list"><div><ShieldIcon/><span><strong>Balanced postings</strong><small>Every journal entry must have equal debits and credits.</small></span></div><div><span className="billing-symbol">2</span><span><strong>Separate approval</strong><small>Transfer requests default to four-eyes approval.</small></span></div><div><span className="billing-symbol">≠</span><span><strong>Not a compliance shortcut</strong><small>Firm policy and local professional rules still require review.</small></span></div></div></section></div>:null}
    {tab==="ledger"?<section className="card"><div className="card-header"><div><div className="card-title">Journal</div><div className="billing-copy">{account?.name||"Choose an account"}</div></div><select value={selectedAccount} onChange={async e=>{setSelectedAccount(e.target.value);setEntries(await getClientMoneyEntries(e.target.value))}}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="finance-table"><div className="finance-head"><span>Date</span><span>Type</span><span>Reference</span><span>Amount</span></div>{entries.length?entries.map(r=><div className="finance-row" key={r.id}><span>{r.entry_date}</span><span className="quiet-badge">{r.entry_type.replaceAll("_"," ")}</span><span><strong>{r.description}</strong><small>{r.reference||r.content_hash.slice(0,12)}</small></span><strong>{money(r.amount,r.currency)}</strong></div>):<div className="empty-state compact"><div className="empty-state-title">No postings yet</div></div>}</div></section>:null}
    {tab==="transfers"?<section className="card"><div className="card-header"><div><div className="card-title">Transfer-to-fees control</div><div className="billing-copy">Request → independent approval → execution.</div></div><button className="secondary-button" onClick={()=>setComposer("transfer")}>Request transfer</button></div>{transfers.length?transfers.map(t=><div className="finance-transfer" key={t.id}><div><strong>{money(t.amount,t.currency)}</strong><small>{t.justification}</small></div><span className={`processing-badge ${t.status==="executed"?"ready":t.status==="pending"?"pending":"processing"}`}>{t.status}</span><div className="finance-actions">{t.status==="pending"?<><button disabled={busy} className="secondary-button" onClick={()=>void decide(t.id,true)}>Approve</button><button disabled={busy} className="ghost-button" onClick={()=>void decide(t.id,false)}>Reject</button></>:null}{t.status==="approved"?<button disabled={busy} className="primary-button" onClick={()=>void execute(t.id)}>Execute</button>:null}</div></div>):<div className="empty-state compact"><div className="empty-state-title">No transfer requests</div></div>}</section>:null}
    {composer?<div className="drawer-backdrop" onClick={()=>setComposer(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><div className="eyebrow">Client money</div><h2>{composer==="account"?"New account":composer==="deposit"?"Record receipt":"Request transfer"}</h2></div><button className="ghost-button" onClick={()=>setComposer(null)}>Close</button></div>{composer==="account"?<form className="drawer-form" onSubmit={accountSubmit}><label>Account name<input name="name" required placeholder="Client Money Account"/></label><label>Bank<input name="bank_name" placeholder="Bank name"/></label><label>Account last 4<input name="last4" minLength={4} maxLength={4}/></label><label>Bank reference<input name="bank_reference"/></label><label>Notes<textarea name="notes"/></label><button disabled={busy} className="primary-button">Create account</button></form>:null}{composer==="deposit"?<form className="drawer-form" onSubmit={depositSubmit}><label>Account<select name="account_id" required>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Client<select name="client_id" required>{clients.map(c=><option value={c.id} key={c.id}>{c.display_name}</option>)}</select></label><label>Amount<input name="amount" type="number" step="0.01" min="0.01" required/></label><label>Date<input name="entry_date" type="date" defaultValue={today()} required/></label><label>Reference<input name="reference"/></label><label>Description<input name="description" defaultValue="Client money received" required/></label><button disabled={busy} className="primary-button">Post balanced receipt</button></form>:null}{composer==="transfer"?<form className="drawer-form" onSubmit={transferSubmit}><label>Account<select name="account_id" required>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Client<select name="client_id" required>{clients.map(c=><option value={c.id} key={c.id}>{c.display_name}</option>)}</select></label><label>Amount<input name="amount" type="number" step="0.01" min="0.01" required/></label><label>Justification<textarea name="justification" required placeholder="Why may these client funds be transferred?"/></label><button disabled={busy} className="primary-button">Create approval request</button></form>:null}</div></div>:null}
  </main>
}
