"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { DocumentCommentRecord, DocumentVersionRecord, LegalDocument, Matter, createDocumentComment, getDocumentComments, getDocumentVersions, getDocuments, getMatters, resolveDocumentComment, snapshotDocumentVersion, uploadDocumentVersion } from "@/lib/api";
import { DocumentIcon, MessageIcon } from "@/components/icons";

export function CollaborationWorkspace(){
  const [matters,setMatters]=useState<Matter[]>([]); const [matterId,setMatterId]=useState(""); const [documents,setDocuments]=useState<LegalDocument[]>([]); const [documentId,setDocumentId]=useState("");
  const [versions,setVersions]=useState<DocumentVersionRecord[]>([]); const [comments,setComments]=useState<DocumentCommentRecord[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const loadDocument=useCallback(async(id:string)=>{if(!id){setVersions([]);setComments([]);return;}try{const [v,c]=await Promise.all([getDocumentVersions(id),getDocumentComments(id)]);setVersions(v);setComments(c);setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load collaboration data");}},[]);
  useEffect(()=>{void (async()=>{try{const m=await getMatters();setMatters(m);const first=m[0]?.id||"";setMatterId(first);if(first){const d=await getDocuments(first);setDocuments(d);const doc=d[0]?.id||"";setDocumentId(doc);await loadDocument(doc);}}catch(e){setError(e instanceof Error?e.message:"Unable to load matters");}})();},[loadDocument]);
  async function chooseMatter(id:string){setMatterId(id);const d=await getDocuments(id);setDocuments(d);const doc=d[0]?.id||"";setDocumentId(doc);await loadDocument(doc)}
  async function snapshot(){if(!documentId)return;setBusy(true);try{await snapshotDocumentVersion(documentId,"Review snapshot");await loadDocument(documentId);}catch(e){setError(e instanceof Error?e.message:"Snapshot failed");}finally{setBusy(false)}}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!documentId)return;setBusy(true);const f=new FormData(e.currentTarget);const file=f.get("file");try{if(!(file instanceof File)||!file.size)throw new Error("Choose a file");await uploadDocumentVersion(documentId,file,String(f.get("note")||"")||undefined);e.currentTarget.reset();await loadDocument(documentId);}catch(err){setError(err instanceof Error?err.message:"Upload failed");}finally{setBusy(false)}}
  async function comment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!documentId)return;setBusy(true);const f=new FormData(e.currentTarget);try{await createDocumentComment(documentId,String(f.get("body")));e.currentTarget.reset();await loadDocument(documentId);}catch(err){setError(err instanceof Error?err.message:"Comment failed");}finally{setBusy(false)}}
  return <main className="page collaboration-page"><div className="hero-row"><div><div className="eyebrow">Document workroom</div><h1 className="page-title">Collaboration</h1><p className="page-subtitle">Immutable versions, anchored review comments, approval records and e-signature orchestration without replacing the original matter document.</p></div></div>{error?<div className="notice-panel"><strong>Attention</strong><span>{error}</span></div>:null}
  <section className="card collaboration-picker"><div><label>Matter<select value={matterId} onChange={e=>void chooseMatter(e.target.value)}>{matters.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label></div><div><label>Document<select value={documentId} onChange={e=>{setDocumentId(e.target.value);void loadDocument(e.target.value)}}>{documents.map(d=><option key={d.id} value={d.id}>{d.display_name||d.filename}</option>)}</select></label></div><button className="secondary-button" disabled={!documentId||busy} onClick={()=>void snapshot()}><DocumentIcon/>Snapshot current</button></section>
  <div className="grid-2 collaboration-grid"><section className="card"><div className="card-header"><div><div className="card-title">Version history</div><div className="billing-copy">Each file version has its own SHA-256 fingerprint.</div></div></div>{versions.length?versions.map(v=><div className="collab-version" key={v.id}><div className="version-number">v{v.version_number}</div><div><strong>{v.filename}</strong><small>{v.source} · {v.sha256.slice(0,14)}…</small><p>{v.change_note||"No change note"}</p></div></div>):<div className="empty-state compact"><div className="empty-state-title">No versions yet</div><div className="empty-state-copy">Snapshot the current document or upload a revised file.</div></div>}<form className="collab-upload" onSubmit={upload}><input name="file" type="file" required/><input name="note" placeholder="Change note"/><button className="primary-button" disabled={!documentId||busy}>Upload version</button></form></section>
  <section className="card"><div className="card-header"><div><div className="card-title">Review comments</div><div className="billing-copy">Comments can later anchor to page, paragraph or coordinate metadata.</div></div><MessageIcon/></div>{comments.length?comments.map(c=><div className={`collab-comment ${c.status}`} key={c.id}><div><strong>{c.status==="resolved"?"Resolved":"Open review point"}</strong><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString()}</small></div>{c.status!=="resolved"?<button className="ghost-button" onClick={()=>void resolveDocumentComment(c.id,true).then(()=>loadDocument(documentId))}>Resolve</button>:null}</div>):<div className="empty-state compact"><div className="empty-state-title">No comments</div></div>}<form className="collab-comment-form" onSubmit={comment}><textarea name="body" required placeholder="Leave a review note…"/><button className="secondary-button" disabled={!documentId||busy}>Add comment</button></form></section></div>
  <section className="notice-panel collaboration-note"><strong>Approval & e-sign foundation</strong><span>The backend now supports assigned review requests, immutable approval decisions, and manual/mock e-sign envelopes. External e-sign providers remain disabled until an explicit production connector is configured.</span></section></main>
}
