"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createDeploymentEnvironment, getDeploymentDashboard, type DeploymentDashboardRecord } from "@/lib/api";
import { PulseIcon, ShieldIcon } from "@/components/icons";

type Tab="topology"|"readiness"|"rollouts"|"secrets";
const nice=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const dt=(v:string|null|undefined)=>v?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";

export function DeploymentWorkspace(){
  const [data,setData]=useState<DeploymentDashboardRecord|null>(null);
  const [tab,setTab]=useState<Tab>("topology");
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState<string|null>(null);
  const [message,setMessage]=useState<string|null>(null);
  const [showCreate,setShowCreate]=useState(false);
  const [form,setForm]=useState<{environment_key:string;name:string;base_url:string;strategy:"rolling"|"blue_green"|"recreate"}>({environment_key:"production-in",name:"India production",base_url:"https://legal.example.com",strategy:"rolling"});
  const refresh=useCallback(async()=>{try{setData(await getDeploymentDashboard());setError(null)}catch(e){setError(e instanceof Error?e.message:"Unable to load deployment control plane")}},[]);
  useEffect(()=>{void refresh()},[refresh]);
  const ready=data?.runtime_readiness.ready??false;
  const criticalFailed=useMemo(()=>data?.runtime_readiness.checks.filter(x=>x.critical&&!x.passed)??[],[data]);
  async function createEnv(){setBusy(true);setError(null);try{await createDeploymentEnvironment({environment_key:form.environment_key,name:form.name,kind:"production",base_url:form.base_url,strategy:form.strategy,tls_required:true,object_storage_required:true,change_window_required:true});setShowCreate(false);setMessage("Production environment profile created. Runtime deployment still requires the recorded release and rollout gates.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to create environment")}finally{setBusy(false)}}
  return <main className="workspace-page deployment-workspace">
    <header className="workspace-header"><div><div className="eyebrow">Production infrastructure</div><h1>Deployment control</h1><p>Runtime readiness, service topology, controlled rollouts and secret references—without storing secret values.</p></div><div className="health-header-actions"><button className="secondary-button" onClick={()=>void refresh()}>Refresh</button><button className="primary-button" onClick={()=>setShowCreate(true)}>New environment</button></div></header>
    {error?<div className="error-banner">{error}</div>:null}{message?<div className="jobs-message">{message}</div>:null}
    <section className="metrics-grid"><div className="metric-card"><span>Runtime readiness</span><strong className={`deployment-state ${ready?"ready":"held"}`}>{ready?"Ready":"Held"}</strong><small>{criticalFailed.length} critical checks failing</small></div><div className="metric-card"><span>Environments</span><strong>{data?.environments.length??0}</strong><small>Staging + production</small></div><div className="metric-card"><span>Service profiles</span><strong>{data?.services.length??0}</strong><small>API, web, workers, data</small></div><div className="metric-card"><span>Rollouts</span><strong>{data?.rollouts.length??0}</strong><small>Recorded deployments</small></div></section>
    <div className="workspace-tabs"><button className={tab==="topology"?"active":""} onClick={()=>setTab("topology")}>Topology</button><button className={tab==="readiness"?"active":""} onClick={()=>setTab("readiness")}>Readiness</button><button className={tab==="rollouts"?"active":""} onClick={()=>setTab("rollouts")}>Rollouts</button><button className={tab==="secrets"?"active":""} onClick={()=>setTab("secrets")}>Secret references</button></div>
    {tab==="topology"?<div className="deployment-grid"><section className="premium-panel"><div className="panel-title-row"><h2>Environments</h2><span>{data?.environments.length??0}</span></div>{data?.environments.length?data.environments.map(env=><div className="deployment-env" key={env.id}><div><strong>{env.name}</strong><small>{env.base_url} · {nice(env.strategy)}</small></div><span className="release-pill passed">{nice(env.kind)}</span></div>):<div className="empty-state compact"><div className="empty-state-title">No deployment environment</div><div className="empty-state-copy">Create the production profile after the release gate and infrastructure secrets are ready.</div></div>}</section><section className="premium-panel"><div className="panel-title-row"><h2>Services</h2><span>{data?.services.length??0}</span></div>{data?.services.map(s=><div className="deployment-service" key={s.id}><span className="health-dot healthy"/><div><strong>{nice(s.service_key)}</strong><small>{s.replicas} replica{s.replicas===1?"":"s"}{s.queue_names?` · ${s.queue_names}`:""}</small></div><span>{s.health_path??"internal"}</span></div>)}</section></div>:null}
    {tab==="readiness"?<section className="premium-panel"><div className="panel-title-row"><h2>Production preflight</h2><span>{data?.runtime_readiness.app_version??"0.29.0-rc.1"}</span></div>{data?.runtime_readiness.checks.map(row=><div className="deployment-check" key={row.key}><span className={`health-dot ${row.passed?"healthy":row.critical?"down":"degraded"}`}/><div><strong>{nice(row.key)}</strong><small>{row.message}</small></div><span>{row.passed?"Pass":row.critical?"Critical":"Advisory"}</span></div>)}</section>:null}
    {tab==="rollouts"?<section className="premium-panel"><div className="panel-title-row"><h2>Deployment history</h2><span>{data?.rollouts.length??0}</span></div>{data?.rollouts.length?data.rollouts.map(r=><div className="deployment-rollout" key={r.id}><div><strong>Release {r.release_run_id.slice(0,8)}</strong><small>{dt(r.created_at)} · rollback {r.rollback_point_id.slice(0,8)}</small></div><span className={`release-pill ${r.status}`}>{nice(r.status)}</span></div>):<div className="empty-state compact"><div className="empty-state-title">No rollout recorded</div><div className="empty-state-copy">Only an approved release with a verified rollback point and required change window can create one.</div></div>}</section>:null}
    {tab==="secrets"?<section className="premium-panel"><div className="panel-title-row"><h2>Secret references</h2><span>References only</span></div><div className="deployment-secret-note"><ShieldIcon/><div><strong>Secret values are never stored here.</strong><p>Records point to environment variables, Docker/Kubernetes secrets, Vault or a cloud secret manager.</p></div></div>{data?.secrets.map(s=><div className="deployment-secret" key={s.id}><div><strong>{s.secret_key}</strong><small>{nice(s.provider)} · {s.reference}</small></div><span>{s.required?"Required":"Optional"}</span></div>)}</section>:null}
    {showCreate?<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setShowCreate(false)}}><div className="modal-card deployment-create"><div className="panel-title-row"><h2>Production environment</h2><button className="ghost-button" onClick={()=>setShowCreate(false)}>Close</button></div><label>Environment key<input value={form.environment_key} onChange={e=>setForm({...form,environment_key:e.target.value})}/></label><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>HTTPS base URL<input value={form.base_url} onChange={e=>setForm({...form,base_url:e.target.value})}/></label><label>Strategy<select value={form.strategy} onChange={e=>setForm({...form,strategy:e.target.value as "rolling"|"blue_green"|"recreate"})}><option value="rolling">Rolling</option><option value="blue_green">Blue / green</option><option value="recreate">Recreate</option></select></label><div className="deployment-create-note"><PulseIcon/><span>Creating a profile does not deploy anything. Production rollouts remain release-gated and manually evidenced.</span></div><button className="primary-button" disabled={busy} onClick={()=>void createEnv()}>{busy?"Creating…":"Create profile"}</button></div></div>:null}
  </main>;
}
