"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import {
  EvidenceBundleRecord, EvidenceDashboard, EvidenceGapRecord, EvidenceGraph, EvidenceRecord,
  EvidenceWitnessRecord, LitigationIssueRecord, Matter, WitnessPrepQuestionRecord,
  createEvidenceBundle, createEvidenceWitness, createLitigationIssue, evidenceBundleDownloadUrl,
  finalizeEvidenceBundle, generateWitnessPrep, getEvidenceBundles, getEvidenceDashboard, getEvidenceGaps, getEvidenceGraph,
  getEvidenceItems, getEvidenceWitnesses, getLitigationIssues, getMatters, getWitnessPrep,
  rebuildEvidence, updateEvidenceGap, updateEvidenceItem,
} from "@/lib/api";
import { ArchiveIcon, DocumentIcon, ScaleIcon, UsersIcon } from "@/components/icons";

type Tab="evidence"|"issues"|"witnesses"|"gaps"|"bundles"|"graph";
const nice=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const pct=(v:number)=>`${Math.round(v*100)}%`;

export function EvidenceWorkspace(){
  const [matters,setMatters]=useState<Matter[]>([]); const [matterId,setMatterId]=useState("");
  const [dashboard,setDashboard]=useState<EvidenceDashboard|null>(null); const [items,setItems]=useState<EvidenceRecord[]>([]);
  const [issues,setIssues]=useState<LitigationIssueRecord[]>([]); const [witnesses,setWitnesses]=useState<EvidenceWitnessRecord[]>([]);
  const [gaps,setGaps]=useState<EvidenceGapRecord[]>([]); const [bundles,setBundles]=useState<EvidenceBundleRecord[]>([]); const [graph,setGraph]=useState<EvidenceGraph|null>(null);
  const [tab,setTab]=useState<Tab>("evidence"); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
  const [prepWitness,setPrepWitness]=useState<EvidenceWitnessRecord|null>(null); const [questions,setQuestions]=useState<WitnessPrepQuestionRecord[]>([]);

  const loadMatter=useCallback(async(id:string)=>{ if(!id)return; try{const [d,e,i,w,g,b,gr]=await Promise.all([getEvidenceDashboard(id),getEvidenceItems(id),getLitigationIssues(id),getEvidenceWitnesses(id),getEvidenceGaps(id),getEvidenceBundles(id),getEvidenceGraph(id)]);setDashboard(d);setItems(e);setIssues(i);setWitnesses(w);setGaps(g);setBundles(b);setGraph(gr);setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load evidence workspace");}},[]);
  useEffect(()=>{void (async()=>{try{const m=await getMatters();setMatters(m);const id=m[0]?.id||"";setMatterId(id);if(id)await loadMatter(id);}catch(e){setError(e instanceof Error?e.message:"Unable to load matters");}})();},[loadMatter]);
  const matter=useMemo(()=>matters.find(m=>m.id===matterId)||null,[matters,matterId]);
  async function choose(id:string){setMatterId(id);await loadMatter(id)}
  async function rebuild(){if(!matterId)return;setBusy(true);try{const r=await rebuildEvidence(matterId);setMessage(`Processed ${r.documents} document(s); ${r.evidence_items_created} evidence item(s) added.`);await loadMatter(matterId);}catch(e){setError(e instanceof Error?e.message:"Rebuild failed");}finally{setBusy(false)}}
  async function review(item:EvidenceRecord){setBusy(true);try{await updateEvidenceItem(item.id,{review_status:"reviewed"});await loadMatter(matterId);}finally{setBusy(false)}}
  async function gapAction(g:EvidenceGapRecord,status:"resolved"|"dismissed"){setBusy(true);try{await updateEvidenceGap(g.id,status);await loadMatter(matterId);}finally{setBusy(false)}}
  async function issueSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await createLitigationIssue(matterId,{code:String(f.get("code")),title:String(f.get("title")),description:String(f.get("description")||"")||null,priority:Number(f.get("priority")||3)});e.currentTarget.reset();await loadMatter(matterId);}catch(err){setError(err instanceof Error?err.message:"Unable to add issue");}finally{setBusy(false)}}
  async function witnessSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await createEvidenceWitness(matterId,{name:String(f.get("name")),kind:String(f.get("kind")||"unknown"),side:String(f.get("side")||"")||null,role:String(f.get("role")||"")||null});e.currentTarget.reset();await loadMatter(matterId);}catch(err){setError(err instanceof Error?err.message:"Unable to add witness");}finally{setBusy(false)}}
  async function prep(w:EvidenceWitnessRecord){setPrepWitness(w);setQuestions(await getWitnessPrep(w.id))}
  async function generatePrep(){if(!prepWitness)return;setBusy(true);try{await generateWitnessPrep(prepWitness.id);setQuestions(await getWitnessPrep(prepWitness.id));}finally{setBusy(false)}}
  async function finalizeBundle(id:string){setBusy(true);try{await finalizeEvidenceBundle(id);setMessage("Bundle finalized after lawyer-review checks.");await loadMatter(matterId);}catch(err){setError(err instanceof Error?err.message:"Unable to finalize bundle");}finally{setBusy(false)}}
  async function bundleSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await createEvidenceBundle(matterId,{title:String(f.get("title")),bundle_type:String(f.get("bundle_type")||"hearing"),evidence_item_ids:items.filter(i=>i.review_status!=="rejected").map(i=>i.id),description:String(f.get("description")||"")||null});e.currentTarget.reset();await loadMatter(matterId);}catch(err){setError(err instanceof Error?err.message:"Bundle generation failed");}finally{setBusy(false)}}

  return <main className="page evidence-page">
    <div className="hero-row"><div><div className="eyebrow">Litigation intelligence</div><h1 className="page-title">Evidence workspace</h1><p className="page-subtitle">Classify, map and prepare litigation evidence without turning deterministic organization into an AI guessing exercise.</p></div><button className="primary-button" disabled={busy||!matterId} onClick={()=>void rebuild()}><ScaleIcon/>Rebuild evidence map</button></div>
    {message?<div className="success-panel evidence-message">{message}</div>:null}{error?<div className="notice-panel evidence-message"><strong>Attention</strong><span>{error}</span></div>:null}
    <section className="card evidence-picker"><label>Matter<select value={matterId} onChange={e=>void choose(e.target.value)}>{matters.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><div><strong>{matter?.case_number||"Case number not recorded"}</strong><span>{matter?.court_name||"Court not recorded"}</span></div></section>
    <div className="metrics evidence-metrics"><div className="metric"><div className="metric-label">Evidence</div><div className="metric-value">{dashboard?.evidence_items||0}</div><div className="metric-note">{dashboard?.reviewed_items||0} lawyer reviewed</div></div><div className="metric"><div className="metric-label">Issues</div><div className="metric-value">{dashboard?.issues||0}</div><div className="metric-note">source mapped</div></div><div className="metric"><div className="metric-label">Witnesses</div><div className="metric-value">{dashboard?.witnesses||0}</div><div className="metric-note">discovered + manual</div></div><div className="metric"><div className="metric-label">Open gaps</div><div className="metric-value">{dashboard?.open_gaps||0}</div><div className="metric-note">{dashboard?.contradictions||0} contradictions</div></div></div>
    <div className="workspace-tabs">{(["evidence","issues","witnesses","gaps","bundles","graph"] as Tab[]).map(t=><button key={t} className={`workspace-tab ${tab===t?"active":""}`} onClick={()=>setTab(t)}>{nice(t)}</button>)}</div>

    {tab==="evidence"?<section className="card"><div className="card-header"><div><div className="card-title">Evidence register</div><div className="quiet-text">Classification is a review aid. Authenticity and admissibility remain lawyer-controlled.</div></div></div>{items.length?items.map(item=><div className="evidence-row" key={item.id}><div className="evidence-icon"><DocumentIcon/></div><div><div className="evidence-title"><strong>{item.title}</strong><span>{nice(item.kind)}</span></div><p>{item.summary||"No extracted preview"}</p><small>Classifier {pct(item.confidence)} · strength {nice(item.strength)} · authenticity {item.authenticity_checked?"checked":"not checked"} · admissibility {item.admissibility_checked?"checked":"not checked"}</small></div><div>{item.review_status==="reviewed"?<span className="verified-badge">Reviewed</span>:<button className="text-button" disabled={busy} onClick={()=>void review(item)}>Mark reviewed</button>}</div></div>):<div className="empty-state"><ArchiveIcon/><div className="empty-state-title">No evidence register yet</div><p>Run Rebuild evidence map after documents are processed.</p></div>}</section>:null}

    {tab==="issues"?<div className="evidence-grid"><section className="card"><div className="card-header"><div><div className="card-title">Issues in dispute</div><div className="quiet-text">Derived suggestions remain editable and reviewable.</div></div></div>{issues.map(i=><div className="evidence-issue" key={i.id}><span className="issue-priority">P{i.priority}</span><div><strong>{i.title}</strong><small>{i.code} · {nice(i.source)}</small>{i.description?<p>{i.description}</p>:null}</div></div>)}</section><aside className="card"><div className="card-header"><div className="card-title">Add issue</div></div><form className="evidence-form" onSubmit={issueSubmit}><label>Code<input name="code" required placeholder="breach_of_contract"/></label><label>Issue title<input name="title" required placeholder="Whether the agreement was breached"/></label><label>Priority<select name="priority" defaultValue="3"><option value="1">1 — critical</option><option value="2">2 — high</option><option value="3">3 — normal</option><option value="4">4 — low</option><option value="5">5 — background</option></select></label><label>Description<textarea name="description"/></label><button className="primary-button" disabled={busy}>Add issue</button></form></aside></div>:null}

    {tab==="witnesses"?<div className="evidence-grid"><section className="card"><div className="card-header"><div><div className="card-title">Witness register</div><div className="quiet-text">Detected witness markers never replace lawyer confirmation.</div></div></div>{witnesses.map(w=><button className="witness-row" key={w.id} onClick={()=>void prep(w)}><div className="evidence-icon"><UsersIcon/></div><div><strong>{w.name}</strong><small>{nice(w.kind)} · {w.side||"side not assigned"} · {nice(w.source)}</small></div><span>Prepare →</span></button>)}</section><aside className="card"><div className="card-header"><div className="card-title">Add witness</div></div><form className="evidence-form" onSubmit={witnessSubmit}><label>Name<input name="name" required/></label><label>Kind<select name="kind" defaultValue="fact"><option value="fact">Fact</option><option value="expert">Expert</option><option value="formal">Formal</option><option value="party">Party</option><option value="unknown">Unknown</option></select></label><label>Side<input name="side" placeholder="petitioner / respondent"/></label><label>Role<input name="role" placeholder="Accounts manager"/></label><button className="primary-button" disabled={busy}>Add witness</button></form></aside></div>:null}

    {tab==="gaps"?<section className="card"><div className="card-header"><div><div className="card-title">Evidence gaps</div><div className="quiet-text">Missing support and unresolved factual contradictions.</div></div></div>{gaps.length?gaps.map(g=><div className={`gap-row ${g.status}`} key={g.id}><span className={`severity-dot ${g.severity}`}/><div><strong>{g.title}</strong><p>{g.explanation}</p>{g.suggested_action?<small>{g.suggested_action}</small>:null}</div><div className="finance-actions">{g.status==="open"?<><button className="text-button" onClick={()=>void gapAction(g,"resolved")}>Resolve</button><button className="text-button" onClick={()=>void gapAction(g,"dismissed")}>Dismiss</button></>:<span className="verified-badge">{nice(g.status)}</span>}</div></div>):<div className="empty-state compact"><div className="empty-state-title">No evidence gaps found</div></div>}</section>:null}

    {tab==="bundles"?<div className="evidence-grid"><section className="card"><div className="card-header"><div><div className="card-title">Hearing / trial bundles</div><div className="quiet-text">ZIP exports include an index, manifest and source documents with hashes.</div></div></div>{bundles.map(b=><div className="bundle-row" key={b.id}><div><strong>{b.title}</strong><small>{nice(b.bundle_type)} · {b.metadata_json.item_count as number||0} items · {b.sha256?.slice(0,12)||"no hash"}…</small></div><div className="finance-actions">{b.status==="draft"?<button className="text-button" disabled={busy} onClick={()=>void finalizeBundle(b.id)}>Finalize</button>:<span className="verified-badge">Final</span>}<a className="secondary-button" href={evidenceBundleDownloadUrl(b.id)}>Download</a></div></div>)}</section><aside className="card"><div className="card-header"><div className="card-title">Generate bundle</div></div><form className="evidence-form" onSubmit={bundleSubmit}><label>Title<input name="title" required placeholder="Hearing bundle — 12 Aug 2026"/></label><label>Type<select name="bundle_type" defaultValue="hearing"><option value="hearing">Hearing</option><option value="trial">Trial</option><option value="discovery">Discovery</option><option value="client_review">Client review</option></select></label><label>Description<textarea name="description"/></label><div className="quiet-text">Includes all non-rejected evidence currently in the register. Export policy is enforced.</div><button className="primary-button" disabled={busy||items.length===0}>Generate ZIP</button></form></aside></div>:null}

    {tab==="graph"?<section className="card"><div className="card-header"><div><div className="card-title">Evidence graph</div><div className="quiet-text">Issue ↔ evidence ↔ witness relationships. This is a deterministic relationship graph, not an AI inference graph.</div></div></div><div className="graph-summary"><div><strong>{graph?.nodes.length||0}</strong><span>nodes</span></div><div><strong>{graph?.edges.length||0}</strong><span>links</span></div></div><div className="graph-list">{graph?.edges.slice(0,40).map((edge,idx)=>{const from=graph.nodes.find(n=>n.id===edge.source);const to=graph.nodes.find(n=>n.id===edge.target);return <div className="graph-edge" key={`${edge.source}-${edge.target}-${idx}`}><span>{from?.label||edge.source}</span><strong>{nice(edge.type)}</strong><span>{to?.label||edge.target}</span></div>})}</div></section>:null}

    {prepWitness?<div className="drawer-backdrop" onClick={()=>setPrepWitness(null)}><section className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><div className="eyebrow">Witness preparation</div><h2>{prepWitness.name}</h2></div><button className="icon-button" onClick={()=>setPrepWitness(null)}>×</button></div><div className="drawer-form"><div className="notice-panel"><strong>Preparation aid</strong><span>Generated questions are prompts for counsel, not a script to coach testimony or alter a witness&apos;s recollection.</span></div><button className="secondary-button" disabled={busy} onClick={()=>void generatePrep()}>Generate foundation questions</button>{questions.map(q=><div className="prep-question" key={q.id}><span>{nice(q.question_type)}</span><strong>{q.question}</strong>{q.purpose?<small>{q.purpose}</small>:null}</div>)}</div></section></div>:null}
  </main>
}
