"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { BellIcon } from "@/components/icons";
import {
  BackgroundJobDetailRecord, BackgroundJobRecord, BackgroundQueueRecord, JobsDashboardRecord,
  cancelBackgroundJob, createBackgroundJob, getBackgroundJob, getBackgroundJobs, getBackgroundQueues,
  getJobsDashboard, retryBackgroundJob, updateBackgroundQueue,
} from "@/lib/api";

type Tab="jobs"|"queues"|"workers";
const nice=(v:string)=>v.replaceAll("_"," ").replaceAll("."," · ").replace(/\b\w/g,c=>c.toUpperCase());
const dateText=(v:string|null)=>v?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const pct=(j:BackgroundJobRecord)=>Math.max(0,Math.min(100,Math.round((j.progress_current||0)*100/Math.max(1,j.progress_total||100))));

export function JobsWorkspace(){
  const [tab,setTab]=useState<Tab>("jobs"); const [dash,setDash]=useState<JobsDashboardRecord|null>(null); const [jobs,setJobs]=useState<BackgroundJobRecord[]>([]); const [queues,setQueues]=useState<BackgroundQueueRecord[]>([]);
  const [selected,setSelected]=useState<BackgroundJobDetailRecord|null>(null); const [status,setStatus]=useState(""); const [queue,setQueue]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
  const refresh=useCallback(async()=>{try{const [d,j,q]=await Promise.all([getJobsDashboard(),getBackgroundJobs(status||undefined,queue||undefined),getBackgroundQueues()]);setDash(d);setJobs(j);setQueues(q);setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load jobs");}},[status,queue]);
  useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),5000);return()=>clearInterval(t)},[refresh]);
  const active=useMemo(()=>jobs.filter(j=>["queued","leased","running","retry_wait"].includes(j.status)).length,[jobs]);
  async function inspect(id:string){try{setSelected(await getBackgroundJob(id))}catch(e){setError(e instanceof Error?e.message:"Unable to load job")}}
  async function action(id:string,kind:"cancel"|"retry"){setBusy(true);try{kind==="cancel"?await cancelBackgroundJob(id):await retryBackgroundJob(id);setMessage(kind==="cancel"?"Cancellation requested":"Job requeued");await refresh();if(selected?.job.id===id)setSelected(await getBackgroundJob(id));}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
  async function maintenance(kind:string){setBusy(true);try{await createBackgroundJob({kind,payload:{},priority:"normal"});setMessage(`${nice(kind)} queued`);await refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to queue maintenance job")}finally{setBusy(false)}}
  async function queueSubmit(e:FormEvent<HTMLFormElement>,row:BackgroundQueueRecord){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await updateBackgroundQueue(row.id,{enabled:f.get("enabled")==="on",max_concurrency:Number(f.get("max_concurrency")),max_per_minute:Number(f.get("max_per_minute")),default_max_attempts:Number(f.get("default_max_attempts")),lease_seconds:Number(f.get("lease_seconds"))});setMessage(`${row.name} queue updated`);await refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to update queue")}finally{setBusy(false)}}
  return <main className="page jobs-page">
    <header className="search-header"><div><div className="eyebrow">Operations infrastructure</div><h1>Background jobs</h1><p>Durable OCR, indexing, corpus, evidence, analytics and bundle work. Jobs survive API restarts, retry deterministically, and dead-letter instead of disappearing.</p></div><div className="jobs-header-actions"><button className="secondary-button" disabled={busy} onClick={()=>void maintenance("search.duplicate_scan")}>Scan duplicates</button><button className="primary-button" disabled={busy} onClick={()=>void maintenance("analytics.risk_rebuild")}>Refresh risk signals</button></div></header>
    {error?<div className="alert error">{error}</div>:null}{message?<div className="jobs-message">{message}</div>:null}
    <section className="metrics"><div className="metric"><div className="metric-label">Active</div><div className="metric-value">{active}</div><div className="metric-note">queued, leased, running or retrying</div></div><div className="metric"><div className="metric-label">Succeeded</div><div className="metric-value">{dash?.by_status.succeeded||0}</div><div className="metric-note">completed durable jobs</div></div><div className="metric"><div className="metric-label">Dead letter</div><div className="metric-value">{dash?.dead_letter||0}</div><div className="metric-note">manual review required</div></div><div className="metric"><div className="metric-label">Workers online</div><div className="metric-value">{dash?.online_workers||0}</div><div className="metric-note">heartbeat within 90 seconds</div></div></section>
    <div className="workspace-tabs"><button className={tab==="jobs"?"active":""} onClick={()=>setTab("jobs")}>Jobs</button><button className={tab==="queues"?"active":""} onClick={()=>setTab("queues")}>Queues</button><button className={tab==="workers"?"active":""} onClick={()=>setTab("workers")}>Workers</button></div>
    {tab==="jobs"?<section className="premium-panel jobs-panel"><div className="jobs-toolbar"><div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{["queued","leased","running","retry_wait","succeeded","failed","cancelled","dead_letter"].map(x=><option key={x} value={x}>{nice(x)}</option>)}</select><select value={queue} onChange={e=>setQueue(e.target.value)}><option value="">All queues</option>{queues.map(q=><option key={q.id} value={q.name}>{nice(q.name)}</option>)}</select></div><button className="ghost-button" onClick={()=>void refresh()}>Refresh</button></div>{jobs.length?jobs.map(j=><button className="job-row" key={j.id} onClick={()=>void inspect(j.id)}><span className={`job-state ${j.status}`}></span><div className="job-main"><strong>{nice(j.kind)}</strong><small>{nice(j.queue_name)} · attempt {j.attempt_count}/{j.max_attempts} · {dateText(j.created_at)}</small><div className="job-progress"><span style={{width:`${pct(j)}%`}}></span></div></div><div className="job-status-copy"><strong>{nice(j.status)}</strong><small>{j.progress_message||`${pct(j)}%`}</small></div></button>):<div className="empty-state compact"><div className="empty-state-title">No matching jobs</div><div className="empty-state-copy">Large processing work will appear here when it is queued.</div></div>}</section>:null}
    {tab==="queues"?<section className="jobs-queue-grid">{queues.map(q=><form key={q.id} className="premium-panel queue-card" onSubmit={e=>void queueSubmit(e,q)}><div className="queue-card-head"><div><strong>{nice(q.name)}</strong><small>Durable queue policy</small></div><label className="queue-switch"><input name="enabled" type="checkbox" defaultChecked={q.enabled}/><span>{q.enabled?"Enabled":"Disabled"}</span></label></div><label>Concurrent jobs<input name="max_concurrency" type="number" min="1" max="128" defaultValue={q.max_concurrency}/></label><label>Claims per minute<input name="max_per_minute" type="number" min="1" defaultValue={q.max_per_minute}/></label><label>Maximum attempts<input name="default_max_attempts" type="number" min="1" max="20" defaultValue={q.default_max_attempts}/></label><label>Lease seconds<input name="lease_seconds" type="number" min="30" defaultValue={q.lease_seconds}/></label><button className="secondary-button" disabled={busy}>Save queue</button></form>)}</section>:null}
    {tab==="workers"?<section className="premium-panel jobs-panel"><div className="panel-title-row"><h2>Worker health</h2><span>{dash?.workers.length||0} visible</span></div>{dash?.workers.length?dash.workers.map(w=><div className="worker-row" key={w.id}><span className={`job-state ${new Date().getTime()-new Date(w.heartbeat_at).getTime()<90000?"running":"failed"}`}></span><div><strong>{w.worker_key}</strong><small>{w.hostname} · PID {w.pid} · {w.queues_json.join(", ")}</small></div><div><strong>{w.jobs_succeeded} ✓</strong><small>{w.jobs_failed} failed · heartbeat {dateText(w.heartbeat_at)}</small></div></div>):<div className="empty-state compact"><div className="empty-state-title">No worker heartbeat yet</div><div className="empty-state-copy">Start <code>python scripts/run_worker.py --organization-id ...</code> to process queued work.</div></div>}</section>:null}
    {selected?<div className="drawer-overlay" onClick={()=>setSelected(null)}><aside className="invoice-detail job-detail" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><div className="eyebrow">Background job</div><h2>{nice(selected.job.kind)}</h2></div><button className="ghost-button" onClick={()=>setSelected(null)}>Close</button></div><div className="invoice-detail-body"><section><div className="job-detail-grid"><span>Status<strong>{nice(selected.job.status)}</strong></span><span>Queue<strong>{nice(selected.job.queue_name)}</strong></span><span>Attempts<strong>{selected.job.attempt_count}/{selected.job.max_attempts}</strong></span><span>Progress<strong>{pct(selected.job)}%</strong></span></div>{selected.job.last_error?<div className="jobs-error-detail">{selected.job.last_error}</div>:null}<div className="invoice-detail-actions">{!["succeeded","failed","cancelled","dead_letter"].includes(selected.job.status)?<button className="secondary-button" disabled={busy} onClick={()=>void action(selected.job.id,"cancel")}>Cancel</button>:null}{["failed","cancelled","dead_letter"].includes(selected.job.status)?<button className="primary-button" disabled={busy} onClick={()=>void action(selected.job.id,"retry")}>Retry</button>:null}</div></section><section><div className="section-kicker">Attempts</div>{selected.attempts.map(a=><div className="job-event" key={a.id}><span>{a.attempt_number}</span><div><strong>{nice(a.status)}</strong><small>{a.error_message||dateText(a.started_at||a.leased_at)}</small></div></div>)}</section><section><div className="section-kicker">Event log</div>{selected.events.map(ev=><div className="job-event" key={ev.id}><span><BellIcon/></span><div><strong>{ev.message}</strong><small>{nice(ev.event_type)} · {dateText(ev.created_at)}</small></div></div>)}</section></div></aside></div>:null}
  </main>;
}
