"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import {
  KnowledgeAssetKind, KnowledgeAssetRecord, KnowledgeCollectionRecord, KnowledgeDashboard,
  KnowledgeSearchResultRecord, MatterPlaybookRecord, ResearchCollectionRecord,
  approveKnowledgeAsset, createKnowledgeAsset, createKnowledgeCollection, getAuthorityCollections,
  getKnowledgeAssets, getKnowledgeCollections, getKnowledgeDashboard, getMatterPlaybooks,
  searchKnowledge, submitKnowledgeAsset,
} from "@/lib/api";
import { BookIcon, GridIcon, ScaleIcon, SparklesIcon } from "@/components/icons";

type Tab="library"|"review"|"playbooks"|"authorities";
const nice=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const pct=(v:number)=>`${Math.round(v*100)}%`;

export function KnowledgeWorkspace(){
  const [tab,setTab]=useState<Tab>("library");
  const [dashboard,setDashboard]=useState<KnowledgeDashboard|null>(null);
  const [assets,setAssets]=useState<KnowledgeAssetRecord[]>([]);
  const [collections,setCollections]=useState<KnowledgeCollectionRecord[]>([]);
  const [playbooks,setPlaybooks]=useState<MatterPlaybookRecord[]>([]);
  const [authorities,setAuthorities]=useState<ResearchCollectionRecord[]>([]);
  const [results,setResults]=useState<KnowledgeSearchResultRecord[]>([]);
  const [query,setQuery]=useState(""); const [searching,setSearching]=useState(false);
  const [composer,setComposer]=useState<"asset"|"collection"|null>(null);
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);

  const load=useCallback(async()=>{try{const[d,a,c,p,r]=await Promise.all([getKnowledgeDashboard(),getKnowledgeAssets(),getKnowledgeCollections(),getMatterPlaybooks(),getAuthorityCollections()]);setDashboard(d);setAssets(a);setCollections(c);setPlaybooks(p);setAuthorities(r);setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load firm knowledge");}},[]);
  useEffect(()=>{void load()},[load]);
  const review=useMemo(()=>assets.filter(a=>a.status==="in_review"||a.status==="draft"),[assets]);

  async function search(e:FormEvent){e.preventDefault();if(query.trim().length<2)return;setSearching(true);try{const data=await searchKnowledge(query.trim());setResults(data.results);setTab("library");setError(null);}catch(e){setError(e instanceof Error?e.message:"Search failed");}finally{setSearching(false)}}
  async function createAsset(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);try{await createKnowledgeAsset({title:String(fd.get("title")||""),kind:String(fd.get("kind")||"practice_note") as KnowledgeAssetKind,language:String(fd.get("language")||"en"),body_en:String(fd.get("body_en")||"")||null,body_hi:String(fd.get("body_hi")||"")||null,summary:String(fd.get("summary")||"")||null,practice_area:String(fd.get("practice_area")||"")||null,matter_type:String(fd.get("matter_type")||"")||null,collection_id:String(fd.get("collection_id")||"")||null,tags:String(fd.get("tags")||"").split(",").map(v=>v.trim()).filter(Boolean),sources:[]});setMessage("Knowledge draft created. It is not firm-wide until reviewed and approved.");setComposer(null);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create asset");}finally{setBusy(false)}}
  async function createCollection(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);try{await createKnowledgeCollection({name:String(fd.get("name")||""),description:String(fd.get("description")||"")||undefined,practice_area:String(fd.get("practice_area")||"")||undefined});setMessage("Collection created.");setComposer(null);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create collection");}finally{setBusy(false)}}
  async function submit(id:string){setBusy(true);try{await submitKnowledgeAsset(id);setMessage("Submitted for partner/admin review.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to submit");}finally{setBusy(false)}}
  async function approve(asset:KnowledgeAssetRecord){setBusy(true);try{await approveKnowledgeAsset(asset.id,asset.source_matter_id?"reviewed":"not_required","Approved for firm precedent reuse after review.");setMessage("Approved for firm-wide reuse.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to approve");}finally{setBusy(false)}}

  const displayResults=results.length?results.map(r=>({asset:r.asset,score:r.score,snippet:r.snippet,tags:r.tags})):assets.filter(a=>a.status==="approved").map(asset=>({asset,score:null as number|null,snippet:asset.summary||asset.body_en||asset.body_hi||"",tags:[] as string[]}));

  return <main className="page knowledge-page">
    <div className="hero-row"><div><div className="eyebrow">Firm intelligence</div><h1 className="page-title">Knowledge & precedents</h1><p className="page-subtitle">Turn approved work product into reusable institutional memory without training a model on confidential client files.</p></div><button className="primary-button" onClick={()=>setComposer("asset")}><SparklesIcon/>New knowledge</button></div>
    {error?<div className="notice-panel"><strong>Attention</strong><span>{error}</span></div>:null}{message?<div className="notice-panel"><strong>Updated</strong><span>{message}</span></div>:null}
    <div className="metrics"><div className="metric"><div className="metric-label">Approved assets</div><div className="metric-value">{dashboard?.approved_assets??0}</div><div className="metric-note">Firm-wide reusable knowledge</div></div><div className="metric"><div className="metric-label">In review</div><div className="metric-value">{dashboard?.drafts_in_review??0}</div><div className="metric-note">Awaiting approval</div></div><div className="metric"><div className="metric-label">Playbooks</div><div className="metric-value">{dashboard?.approved_playbooks??0}</div><div className="metric-note">Approved matter workflows</div></div><div className="metric"><div className="metric-label">Reuse</div><div className="metric-value">{dashboard?.total_reuse_count??0}</div><div className="metric-note">Search-result reuse signals</div></div></div>
    <form className="knowledge-search card" onSubmit={search}><BookIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search firm precedents in English, हिन्दी or Hinglish…"/><button className="secondary-button" disabled={searching}>{searching?"Searching…":"Search"}</button>{results.length?<button type="button" className="secondary-button" onClick={()=>{setResults([]);setQuery("")}}>Clear</button>:null}</form>
    <div className="workspace-tabs"><button className={`workspace-tab${tab==="library"?" active":""}`} onClick={()=>setTab("library")}>Library</button><button className={`workspace-tab${tab==="review"?" active":""}`} onClick={()=>setTab("review")}>Review queue · {review.length}</button><button className={`workspace-tab${tab==="playbooks"?" active":""}`} onClick={()=>setTab("playbooks")}>Matter playbooks</button><button className={`workspace-tab${tab==="authorities"?" active":""}`} onClick={()=>setTab("authorities")}>Authority collections</button></div>
    {tab==="library"?<section className="knowledge-grid">{displayResults.length?displayResults.map(({asset,score,snippet,tags})=><article className="card knowledge-card" key={asset.id}><div className="knowledge-card-top"><span className="status">{nice(asset.kind)}</span><span className="quiet-text">{score===null?pct(asset.quality_score):`${pct(score)} match`}</span></div><h3>{asset.title}</h3><p>{String(snippet).slice(0,420)}</p><div className="knowledge-meta"><span>{asset.practice_area||"General"}</span><span>{nice(asset.language)}</span><span>{asset.outcome_label||"Approved precedent"}</span></div>{(tags ?? []).length?<div className="knowledge-tags">{(tags ?? []).map(t=><span key={t}>{t}</span>)}</div>:null}<div className="knowledge-hash">SHA-256 · {asset.content_hash.slice(0,14)}…</div></article>):<div className="card empty-state"><div className="empty-state-title">No approved knowledge yet</div><div className="empty-state-copy">Create or promote reviewed work product, then send it through sanitization and approval before it appears here.</div></div>}</section>:null}
    {tab==="review"?<section className="card"><div className="card-header"><div><div className="card-title">Review queue</div><div className="card-action">Matter-derived knowledge cannot go firm-wide until sanitization and provenance are reviewed.</div></div></div>{review.length?review.map(asset=><div className="knowledge-review-row" key={asset.id}><div><div className="matter-title">{asset.title}</div><div className="matter-meta">{nice(asset.kind)} · {nice(asset.sanitization_status)} · {asset.source_matter_id?"Matter-derived":"Manual"}</div></div><span className="status">{nice(asset.status)}</span><div className="knowledge-actions">{asset.status==="draft"?<button className="secondary-button" disabled={busy} onClick={()=>void submit(asset.id)}>Submit</button>:<button className="primary-button" disabled={busy} onClick={()=>void approve(asset)}>Approve reuse</button>}</div></div>):<div className="empty-state compact"><div className="empty-state-title">Review queue is clear</div></div>}</section>:null}
    {tab==="playbooks"?<section className="grid-2"><div className="card"><div className="card-header"><div className="card-title">Matter playbooks</div></div>{playbooks.length?playbooks.map(p=><div className="task-row" key={p.id}><GridIcon/><div><div className="task-title">{p.name_en}{p.name_hi?` · ${p.name_hi}`:""}</div><div className="task-meta">{p.practice_area||"General"} · {p.matter_type||"Any matter"} · v{p.version}</div></div><span className="status">{nice(p.status)}</span></div>):<div className="empty-state compact"><div className="empty-state-copy">Playbooks combine approved precedent assets with ordered matter-stage instructions.</div></div>}</div><div className="card"><div className="card-header"><div className="card-title">Collections</div><button className="card-action" onClick={()=>setComposer("collection")}>New collection</button></div>{collections.map(c=><div className="task-row" key={c.id}><BookIcon/><div><div className="task-title">{c.name}</div><div className="task-meta">{c.practice_area||"Firm-wide"}</div></div></div>)}</div></section>:null}
    {tab==="authorities"?<section className="card"><div className="card-header"><div><div className="card-title">Approved authority collections</div><div className="card-action">Curated judgment sets must contain only verified authorities before approval.</div></div></div>{authorities.length?authorities.map(c=><div className="knowledge-review-row" key={c.id}><ScaleIcon/><div><div className="matter-title">{c.name}</div><div className="matter-meta">{c.practice_area||"General"} · {c.issue_key||"Multiple issues"}</div></div><span className="status">{nice(c.status)}</span></div>):<div className="empty-state compact"><div className="empty-state-copy">No authority collections yet. The API can curate verified judgments and paragraph-level propositions into reusable research sets.</div></div>}</section>:null}
    {composer?<div className="drawer-backdrop" onMouseDown={()=>setComposer(null)}><div className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-header"><div><div className="eyebrow">Firm knowledge</div><h2>{composer==="asset"?"Create knowledge draft":"Create collection"}</h2></div><button className="icon-button" onClick={()=>setComposer(null)}>×</button></div>{composer==="collection"?<form className="drawer-form" onSubmit={createCollection}><label>Name<input name="name" required/></label><label>Practice area<input name="practice_area" placeholder="Commercial litigation"/></label><label>Description<textarea name="description" rows={5}/></label><button className="primary-button" disabled={busy}>Create collection</button></form>:<form className="drawer-form" onSubmit={createAsset}><label>Title<input name="title" required/></label><label>Type<select name="kind" defaultValue="practice_note"><option value="pleading_section">Pleading section</option><option value="contract_clause">Contract clause</option><option value="argument">Argument</option><option value="research_memo">Research memo</option><option value="authority_note">Authority note</option><option value="checklist">Checklist</option><option value="template">Template</option><option value="practice_note">Practice note</option></select></label><label>Language<select name="language" defaultValue="en"><option value="en">English</option><option value="hi">हिन्दी</option><option value="bilingual">Bilingual</option></select></label><label>Collection<select name="collection_id" defaultValue=""><option value="">No collection</option>{collections.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Practice area<input name="practice_area"/></label><label>Matter type<input name="matter_type"/></label><label>Summary<textarea name="summary" rows={3}/></label><label>English body<textarea name="body_en" rows={8}/></label><label>हिन्दी content<textarea name="body_hi" rows={8}/></label><label>Tags<input name="tags" placeholder="arbitration, injunction, धारा 9"/></label><div className="procedure-source-warning">Manual entries remain drafts. Matter-derived work product should be promoted with provenance and then sanitized/reviewed before firm-wide reuse.</div><button className="primary-button" disabled={busy}>Create draft</button></form>}</div></div>:null}
  </main>;
}
