"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  createJurisdictionPack, createLegalDataFeed, getJurisdictionPacks, getLegalDataAmendments,
  getLegalDataDashboard, getLegalDataFeeds, getLegalDataRuns, getResearchSources,
  reviewLegalDataAmendment, runLegalDataIntegritySweep, syncLegalDataFeed,
  type JurisdictionPackRecord, type LegalDataAmendmentRecord, type LegalDataDashboardRecord,
  type LegalDataFeedRecord, type LegalDataRunRecord, type LegalSourceRecord,
} from "@/lib/api";
import { BookIcon, ShieldIcon } from "@/components/icons";

type Tab="feeds"|"amendments"|"runs"|"packs";
const nice=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const dt=(v:string|null)=>v?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"Never";

export function LegalDataWorkspace(){
  const [tab,setTab]=useState<Tab>("feeds"); const [dash,setDash]=useState<LegalDataDashboardRecord|null>(null);
  const [feeds,setFeeds]=useState<LegalDataFeedRecord[]>([]); const [runs,setRuns]=useState<LegalDataRunRecord[]>([]);
  const [amendments,setAmendments]=useState<LegalDataAmendmentRecord[]>([]); const [packs,setPacks]=useState<JurisdictionPackRecord[]>([]); const [sources,setSources]=useState<LegalSourceRecord[]>([]);
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [showFeed,setShowFeed]=useState(false); const [showPack,setShowPack]=useState(false);
  const [feedForm,setFeedForm]=useState({source_id:"",code:"",name:"",content_kind:"mixed",mode:"manual_manifest",domains:"",import_path:"",schedule_interval_minutes:1440,stale_after_hours:72});
  const [packForm,setPackForm]=useState({pack_key:"india-core",name:"India Core",jurisdiction:"India",state:"",languages:"en,hi"});
  const sourceById=useMemo(()=>Object.fromEntries(sources.map(s=>[s.id,s])),[sources]);
  const refresh=useCallback(async()=>{try{const [d,f,r,a,p,s]=await Promise.all([getLegalDataDashboard(),getLegalDataFeeds(),getLegalDataRuns(),getLegalDataAmendments(),getJurisdictionPacks(),getResearchSources()]);setDash(d);setFeeds(f);setRuns(r);setAmendments(a);setPacks(p);setSources(s);setError(null)}catch(e){setError(e instanceof Error?e.message:"Unable to load legal data operations")}},[]);
  useEffect(()=>{void refresh()},[refresh]);
  async function sweep(){setBusy(true);try{await runLegalDataIntegritySweep();setMessage("Source freshness and integrity sweep completed.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Integrity sweep failed")}finally{setBusy(false)}}
  async function sync(id:string){setBusy(true);try{await syncLegalDataFeed(id);setMessage("Feed check completed. Protected court pages are never scraped by this action.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Feed sync failed")}finally{setBusy(false)}}
  async function review(id:string){setBusy(true);try{await reviewLegalDataAmendment(id,"reviewed");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to review amendment")}finally{setBusy(false)}}
  async function addFeed(){setBusy(true);try{const selected=sourceById[feedForm.source_id];await createLegalDataFeed({source_id:feedForm.source_id,code:feedForm.code,name:feedForm.name,content_kind:feedForm.content_kind,mode:feedForm.mode,allowed_domains:(feedForm.domains||new URL(selected?.base_url||"https://example.invalid").hostname).split(",").map(v=>v.trim()).filter(Boolean),schedule_interval_minutes:feedForm.schedule_interval_minutes,stale_after_hours:feedForm.stale_after_hours,import_path:feedForm.mode==="filesystem_drop"?feedForm.import_path||feedForm.code:null,metadata:{}});setShowFeed(false);setMessage("Legal-data feed created.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to create feed")}finally{setBusy(false)}}
  async function addPack(){setBusy(true);try{await createJurisdictionPack({pack_key:packForm.pack_key,name:packForm.name,jurisdiction:packForm.jurisdiction,state:packForm.state||null,languages:packForm.languages.split(",").map(v=>v.trim()).filter(Boolean),metadata:{}});setShowPack(false);await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to create jurisdiction pack")}finally{setBusy(false)}}
  return <main className="workspace-page">
    <header className="workspace-header"><div><div className="eyebrow">Authoritative corpus operations</div><h1>Legal data</h1><p>Versioned statute and judgment ingestion, amendment review, source integrity and jurisdiction packs.</p></div><div className="health-header-actions"><button className="secondary-button" disabled={busy} onClick={()=>void sweep()}>Integrity sweep</button><button className="primary-button" onClick={()=>setShowFeed(true)}>New feed</button></div></header>
    {error?<div className="error-banner">{error}</div>:null}{message?<div className="jobs-message">{message}</div>:null}
    <section className="metrics-grid"><div className="metric-card"><span>Feeds</span><strong>{dash?.feeds??0}</strong><small>{dash?.stale_feeds??0} stale</small></div><div className="metric-card"><span>Pending changes</span><strong>{dash?.pending_amendments??0}</strong><small>Lawyer review required</small></div><div className="metric-card"><span>Open alerts</span><strong>{dash?.open_alerts??0}</strong><small>Source / integrity notices</small></div><div className="metric-card"><span>Corpus checkpoint</span><strong>{dash?.latest_checkpoint?.judgments??0}</strong><small>{dash?.latest_checkpoint?.sections??0} statute sections</small></div></section>
    <div className="workspace-tabs">{(["feeds","amendments","runs","packs"] as Tab[]).map(t=><button className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{nice(t)}</button>)}</div>
    {tab==="feeds"?<div className="deployment-grid"><section className="premium-panel"><div className="panel-title-row"><h2>Source feeds</h2><span>{feeds.length}</span></div>{feeds.map(f=><div className="deployment-env" key={f.id}><div><strong>{f.name}</strong><small>{sourceById[f.source_id]?.name??f.source_id} · {nice(f.mode)} · {nice(f.content_kind)}</small><small>Last success {dt(f.last_success_at)} · stale after {f.stale_after_hours}h</small></div><div className="health-header-actions"><span className={`release-pill ${f.enabled?"passed":"pending"}`}>{f.enabled?"Enabled":"Disabled"}</span><button className="ghost-button" disabled={busy} onClick={()=>void sync(f.id)}>Check now</button></div></div>)}{!feeds.length?<div className="empty-state compact"><div className="empty-state-title">No legal-data feeds</div><div className="empty-state-copy">Create a controlled manifest feed for India Code, eCourts/Supreme Court exports, or another approved official source.</div></div>:null}</section><section className="premium-panel"><div className="panel-title-row"><h2>Open alerts</h2><span>{dash?.alerts.length??0}</span></div>{dash?.alerts.map(a=><div className="incident-card" key={a.id}><div className="incident-card-head"><span className={`health-dot ${a.severity==="critical"?"down":a.severity==="high"?"degraded":"unknown"}`}/><div><strong>{a.title}</strong><small>{nice(a.kind)} · {dt(a.last_seen_at)}</small></div></div><p>{a.message}</p></div>)}{!dash?.alerts.length?<div className="empty-state compact"><div className="empty-state-title">No open legal-data alerts</div></div>:null}</section></div>:null}
    {tab==="amendments"?<section className="premium-panel"><div className="panel-title-row"><h2>Statutory change review</h2><span>{amendments.filter(a=>a.review_status==="pending").length} pending</span></div>{amendments.map(a=><div className="deployment-env" key={a.id}><div><strong>{nice(a.event_kind)}{a.section_number?` · Section ${a.section_number}`:""}</strong><small>Detected {dt(a.detected_at)}{a.effective_date?` · source effective ${a.effective_date}`:" · no effective date asserted"}</small><small>{a.previous_sha256?.slice(0,10)??"new"} → {a.new_sha256?.slice(0,10)??"removed"}</small></div><div className="health-header-actions"><span className={`release-pill ${a.review_status==="reviewed"?"passed":"pending"}`}>{nice(a.review_status)}</span>{a.review_status==="pending"?<button className="secondary-button" disabled={busy} onClick={()=>void review(a.id)}>Mark reviewed</button>:null}</div></div>)}{!amendments.length?<div className="empty-state compact"><div className="empty-state-title">No statute changes detected yet</div></div>:null}</section>:null}
    {tab==="runs"?<section className="premium-panel"><div className="panel-title-row"><h2>Ingestion history</h2><span>{runs.length}</span></div>{runs.map(r=><div className="deployment-service" key={r.id}><span className={`health-dot ${r.status==="succeeded"?"healthy":r.status==="partial"?"degraded":r.status==="failed"?"down":"unknown"}`}/><div><strong>{r.source_label||`Run ${r.id.slice(0,8)}`}</strong><small>{nice(r.trigger)} · {dt(r.started_at)} · manifest {r.manifest_sha256?.slice(0,12)??"—"}</small><small>{r.items_succeeded}/{r.items_total} accepted · {r.items_changed} changed · {r.items_failed} failed</small></div><span>{nice(r.status)}</span></div>)}</section>:null}
    {tab==="packs"?<div className="deployment-grid"><section className="premium-panel"><div className="panel-title-row"><h2>Jurisdiction packs</h2><button className="ghost-button" onClick={()=>setShowPack(true)}>New pack</button></div>{packs.map(p=><div className="deployment-env" key={p.id}><div><strong>{p.name}</strong><small>{p.jurisdiction}{p.state?` · ${p.state}`:""} · {p.languages_json.join(" / ")}</small><small>Active release {p.active_release_version??"not activated"}</small></div><span className={`release-pill ${p.status==="active"?"passed":"pending"}`}>{nice(p.status)}</span></div>)}</section><section className="premium-panel"><div className="deployment-secret-note"><ShieldIcon/><div><strong>Pack activation is review-gated.</strong><p>Required sources must be official, enabled, freshness-tracked and within the release threshold. Unreviewed statutory changes block activation.</p></div></div><div className="deployment-secret-note"><BookIcon/><div><strong>No hidden legal effective dates.</strong><p>If an official normalized source does not provide an effective date, Junior Lawyer records the change for review rather than inventing one.</p></div></div></section></div>:null}
    {showFeed?<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setShowFeed(false)}}><div className="modal-card deployment-create"><div className="panel-title-row"><h2>New legal-data feed</h2><button className="ghost-button" onClick={()=>setShowFeed(false)}>Close</button></div><label>Official source<select value={feedForm.source_id} onChange={e=>{const s=sourceById[e.target.value];setFeedForm({...feedForm,source_id:e.target.value,domains:s?.base_url?new URL(s.base_url).hostname:""})}}><option value="">Choose source</option>{sources.filter(s=>s.official).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Feed code<input value={feedForm.code} onChange={e=>setFeedForm({...feedForm,code:e.target.value})} placeholder="india-code-central"/></label><label>Name<input value={feedForm.name} onChange={e=>setFeedForm({...feedForm,name:e.target.value})} placeholder="India Code · Central Acts"/></label><label>Content<select value={feedForm.content_kind} onChange={e=>setFeedForm({...feedForm,content_kind:e.target.value})}><option value="mixed">Mixed</option><option value="statute">Statutes</option><option value="judgment">Judgments</option></select></label><label>Mode<select value={feedForm.mode} onChange={e=>setFeedForm({...feedForm,mode:e.target.value})}><option value="manual_manifest">Manual manifest</option><option value="filesystem_drop">Controlled file drop</option><option value="integration_push">Integration push</option></select></label><label>Allowed domains<input value={feedForm.domains} onChange={e=>setFeedForm({...feedForm,domains:e.target.value})}/></label>{feedForm.mode==="filesystem_drop"?<label>Import subfolder<input value={feedForm.import_path} onChange={e=>setFeedForm({...feedForm,import_path:e.target.value})} placeholder="india-code"/></label>:null}<button className="primary-button" disabled={busy||!feedForm.source_id||!feedForm.code||!feedForm.name} onClick={()=>void addFeed()}>Create feed</button></div></div>:null}
    {showPack?<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setShowPack(false)}}><div className="modal-card deployment-create"><div className="panel-title-row"><h2>New jurisdiction pack</h2><button className="ghost-button" onClick={()=>setShowPack(false)}>Close</button></div><label>Pack key<input value={packForm.pack_key} onChange={e=>setPackForm({...packForm,pack_key:e.target.value})}/></label><label>Name<input value={packForm.name} onChange={e=>setPackForm({...packForm,name:e.target.value})}/></label><label>Jurisdiction<input value={packForm.jurisdiction} onChange={e=>setPackForm({...packForm,jurisdiction:e.target.value})}/></label><label>State / region<input value={packForm.state} onChange={e=>setPackForm({...packForm,state:e.target.value})}/></label><label>Languages<input value={packForm.languages} onChange={e=>setPackForm({...packForm,languages:e.target.value})}/></label><button className="primary-button" disabled={busy||!packForm.pack_key||!packForm.name} onClick={()=>void addPack()}>Create pack</button></div></div>:null}
  </main>
}
