"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import {
  CourtChangeRecord, CourtTrackerRecord, Matter, OperationsAgendaItem, OperationsDashboard,
  WorkflowTaskRecord, WorkflowTemplateRecord, captureCourtSnapshot, createCourtTracker,
  getCourtChanges, getCourtSources, getCourtTrackers, getMatters, getOperationsAgenda,
  getOperationsDashboard, getOperationsSupervision, getWorkflowTasks, getWorkflowTemplates,
  reviewCourtChange, runOperationsSweep, seedWorkflowTemplates, updateWorkflowTask,
} from "@/lib/api";
import { BellIcon, CalendarIcon, ScaleIcon, ShieldIcon } from "@/components/icons";

type Tab = "agenda" | "court" | "workflows" | "supervision";
const nice=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const when=(v:string|null)=>v?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:v.includes("T")?"short":undefined}).format(new Date(v)):"—";

export function OperationsWorkspace(){
  const [tab,setTab]=useState<Tab>("agenda"); const [dashboard,setDashboard]=useState<OperationsDashboard|null>(null);
  const [agenda,setAgenda]=useState<OperationsAgendaItem[]>([]); const [tasks,setTasks]=useState<WorkflowTaskRecord[]>([]);
  const [templates,setTemplates]=useState<WorkflowTemplateRecord[]>([]); const [matters,setMatters]=useState<Matter[]>([]);
  const [matterId,setMatterId]=useState(""); const [trackers,setTrackers]=useState<CourtTrackerRecord[]>([]); const [changes,setChanges]=useState<CourtChangeRecord[]>([]);
  const [supervision,setSupervision]=useState<{team:Record<string,{name:string;role:string;open:number;overdue:number;high:number}>;total_open:number}|null>(null);
  const [composer,setComposer]=useState<"tracker"|"snapshot"|null>(null); const [trackerId,setTrackerId]=useState("");
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);

  const refresh=useCallback(async()=>{ try{
    const [d,a,t,m,w,c]=await Promise.all([getOperationsDashboard(),getOperationsAgenda(7),getWorkflowTasks(false),getMatters(),getWorkflowTemplates(),getCourtChanges(undefined,true)]);
    setDashboard(d);setAgenda(a);setTasks(t);setMatters(m);setTemplates(w);setChanges(c); const chosen=matterId||m[0]?.id||""; setMatterId(chosen);
    setTrackers(await getCourtTrackers(chosen||undefined));
    try{setSupervision(await getOperationsSupervision());}catch{setSupervision(null)}
    setError(null);
  }catch(e){setError(e instanceof Error?e.message:"Unable to load operations workspace");}},[matterId]);
  useEffect(()=>{void refresh();},[refresh]);
  const matter=useMemo(()=>matters.find(m=>m.id===matterId)||null,[matters,matterId]);

  async function selectMatter(id:string){setMatterId(id);setTrackers(await getCourtTrackers(id));setChanges(await getCourtChanges(id,true));}
  async function seed(){setBusy(true);try{const r=await seedWorkflowTemplates();setMessage(`${r.created} workflow template${r.created===1?"":"s"} added.`);await refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to seed workflows");}finally{setBusy(false)}}
  async function sweep(){setBusy(true);try{const r=await runOperationsSweep();setMessage(`${r.events_created} due event(s), ${r.escalations_created} escalation(s).`);await refresh();}catch(e){setError(e instanceof Error?e.message:"Sweep failed");}finally{setBusy(false)}}
  async function completeTask(id:string){setBusy(true);try{await updateWorkflowTask(id,{status:"done"});await refresh();}catch(e){setError(e instanceof Error?e.message:"Task update failed");}finally{setBusy(false)}}
  async function reviewChange(id:string){setBusy(true);try{await reviewCourtChange(id);await refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to review change");}finally{setBusy(false)}}
  async function trackerSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const row=await createCourtTracker({matter_id:matterId,source_kind:String(f.get("source_kind")||"ecourts_manual"),cnr_number:String(f.get("cnr")||"")||null,case_number:String(f.get("case_number")||"")||null,court_name:String(f.get("court_name")||"")||null,source_url:String(f.get("source_url")||"")||null,config_json:{check_interval_hours:24}});setTrackerId(row.id);setComposer("snapshot");await refresh();}catch(err){setError(err instanceof Error?err.message:"Unable to create tracker");}finally{setBusy(false)}}
  async function snapshotSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const result=await captureCourtSnapshot(trackerId,{case_status:String(f.get("case_status")||"")||null,stage:String(f.get("stage")||"")||null,next_hearing_date:String(f.get("next_hearing_date")||"")||null,judge_or_bench:String(f.get("judge")||"")||null,order_count:Number(f.get("order_count")||0),latest_order_date:String(f.get("latest_order_date")||"")||null,latest_order_reference:String(f.get("order_reference")||"")||null,source_payload_json:{entered_by:"legal_team"}});setMessage(result.changes.length?`${result.changes.length} court change(s) detected and routed into workflow review.`:"Snapshot recorded; no material change detected.");setComposer(null);await refresh();}catch(err){setError(err instanceof Error?err.message:"Unable to record snapshot");}finally{setBusy(false)}}

  const visibleChanges=changes.filter(c=>!matterId||c.matter_id===matterId);
  return <main className="page operations-page">
    <div className="hero-row"><div><div className="eyebrow">Legal operations</div><h1 className="page-title">Court operations</h1><p className="page-subtitle">Deterministic workflows for court changes, deadlines, task escalation and daily lawyer supervision. Court-source snapshots stay reviewable and provenance-aware.</p></div><div className="finance-actions"><button className="secondary-button" disabled={busy} onClick={()=>void sweep()}><BellIcon/>Run due sweep</button><button className="primary-button" disabled={busy||!matterId} onClick={()=>setComposer("tracker")}><ScaleIcon/>Track case</button></div></div>
    {message?<div className="success-panel operations-message">{message}</div>:null}{error?<div className="notice-panel operations-message"><strong>Attention</strong><span>{error}</span></div>:null}
    <div className="metrics operations-metrics"><div className="metric"><div className="metric-label">Open work</div><div className="metric-value">{dashboard?.open_tasks||0}</div><div className="metric-note">{dashboard?.overdue_tasks||0} overdue</div></div><div className="metric"><div className="metric-label">Court changes</div><div className="metric-value">{dashboard?.unreviewed_court_changes||0}</div><div className="metric-note">awaiting lawyer review</div></div><div className="metric"><div className="metric-label">Upcoming hearings</div><div className="metric-value">{dashboard?.upcoming_hearings||0}</div><div className="metric-note">visible matters</div></div><div className="metric"><div className="metric-label">Tracked cases</div><div className="metric-value">{dashboard?.active_trackers||0}</div><div className="metric-note">approved/manual sources</div></div></div>
    <div className="workspace-tabs">{(["agenda","court","workflows","supervision"] as Tab[]).map(t=><button key={t} className={`workspace-tab ${tab===t?"active":""}`} onClick={()=>setTab(t)}>{nice(t)}</button>)}</div>

    {tab==="agenda"?<div className="operations-grid"><section className="card"><div className="card-header"><div><div className="card-title">My next 7 days</div><div className="quiet-text">Court dates, workflow tasks and unreviewed court changes</div></div></div>{agenda.length?agenda.map(i=><div className="ops-agenda-row" key={`${i.kind}-${i.id}`}><div className={`ops-kind ${i.priority||""}`}>{i.kind==="hearing"?<CalendarIcon/>:<BellIcon/>}</div><div><span className="agenda-kind">{nice(i.kind)}</span><strong>{i.title}</strong><small>{i.matter_title||"Firm operations"} · {when(i.when)}</small>{i.detail?<p>{i.detail}</p>:null}</div><span className={`processing-badge ${i.priority==="high"?"failed":"pending"}`}>{i.priority||i.status}</span></div>):<div className="empty-state compact"><div className="empty-state-title">No agenda items</div></div>}</section><aside className="card"><div className="card-header"><div><div className="card-title">My operational tasks</div><div className="quiet-text">Automation creates tasks; lawyers remain responsible for completion.</div></div></div>{tasks.filter(t=>t.status!=="done"&&t.status!=="cancelled").slice(0,8).map(t=><div className="ops-task" key={t.id}><div><strong>{t.title}</strong><small>{t.due_at?`Due ${when(t.due_at)}`:"No due date"} · escalation {t.escalation_level}</small></div><button className="text-button" disabled={busy} onClick={()=>void completeTask(t.id)}>Complete</button></div>)}</aside></div>:null}

    {tab==="court"?<><section className="card operations-picker"><label>Matter<select value={matterId} onChange={e=>void selectMatter(e.target.value)}>{matters.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><div className="operations-case-meta"><strong>{matter?.case_number||"Case number not recorded"}</strong><span>{matter?.cnr_number||"CNR not recorded"} · {matter?.court_name||"Court not recorded"}</span></div><button className="secondary-button" disabled={!matterId} onClick={()=>setComposer("tracker")}>Add tracker</button></section><div className="operations-grid"><section className="card"><div className="card-header"><div><div className="card-title">Court trackers</div><div className="quiet-text">No CAPTCHA bypass or hidden scraping.</div></div></div>{trackers.length?trackers.map(t=><button className="ops-tracker" key={t.id} onClick={()=>{setTrackerId(t.id);setComposer("snapshot")}}><span className="ops-source">{nice(t.source_kind)}</span><div><strong>{t.case_number||matter?.case_number||"Tracked matter"}</strong><small>{t.cnr_number||"No CNR"} · last checked {when(t.last_checked_at)}</small></div><span className="verified-badge">{t.status}</span></button>):<div className="empty-state compact"><div className="empty-state-title">No court tracker yet</div><div className="empty-state-copy">Create one, then record official/manual snapshots as court information changes.</div></div>}</section><section className="card"><div className="card-header"><div><div className="card-title">Detected changes</div><div className="quiet-text">Changes become tasks/notifications through deterministic workflows.</div></div></div>{visibleChanges.length?visibleChanges.map(c=><div className="ops-change" key={c.id}><div><span className={`severity-dot ${c.severity}`}/><strong>{c.summary}</strong><small>{c.old_value||"—"} → {c.new_value||"—"}</small></div><button className="text-button" disabled={busy} onClick={()=>void reviewChange(c.id)}>Reviewed</button></div>):<div className="empty-state compact"><div className="empty-state-title">No unreviewed changes</div></div>}</section></div></>:null}

    {tab==="workflows"?<section className="card"><div className="card-header"><div><div className="card-title">Deterministic workflow library</div><div className="quiet-text">Rules run from events; AI is not needed to decide whether an operational trigger fired.</div></div><button className="secondary-button" disabled={busy} onClick={()=>void seed()}>Seed built-ins</button></div>{templates.length?templates.map(t=><div className="ops-template" key={t.id}><div className="ops-template-code">{t.code}</div><div><strong>{t.name_en}</strong><small>{t.name_hi||t.description||"Operational workflow"}</small></div><div><span>{nice(t.trigger_type)}</span><small>{t.actions_json.length} action(s)</small></div></div>):<div className="empty-state compact"><div className="empty-state-title">No workflow templates</div><div className="empty-state-copy">Seed the built-in court/deadline workflows to start.</div></div>}</section>:null}

    {tab==="supervision"?<section className="card"><div className="card-header"><div><div className="card-title">Partner supervision</div><div className="quiet-text">Workload summary respects matter visibility and ethical walls.</div></div><ShieldIcon/></div>{supervision?<><div className="ops-supervision-total"><strong>{supervision.total_open}</strong><span>open operational tasks across visible work</span></div>{Object.entries(supervision.team).map(([id,v])=><div className="ops-team-row" key={id}><span>{v.name}<small>{v.role?nice(v.role):id==="unassigned"?"":"Member"}</small></span><strong>{v.open} open</strong><span>{v.high} high</span><span>{v.overdue} overdue</span></div>)}</>:<div className="empty-state compact"><div className="empty-state-title">Partner view unavailable</div><div className="empty-state-copy">This view is restricted to partner/admin/owner roles.</div></div>}</section>:null}

    {composer?<div className="drawer-backdrop" onClick={()=>setComposer(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><div className="eyebrow">Court operations</div><h2>{composer==="tracker"?"Track a court case":"Record court snapshot"}</h2></div><button className="ghost-button" onClick={()=>setComposer(null)}>Close</button></div>{composer==="tracker"?<form className="drawer-form" onSubmit={trackerSubmit}><label>Source<select name="source_kind" defaultValue="ecourts_manual"><option value="ecourts_manual">eCourts · manual/approved import</option><option value="official_import">Other official import</option><option value="manual">Manual record</option></select></label><label>CNR<input name="cnr" defaultValue={matter?.cnr_number||""}/></label><label>Case number<input name="case_number" defaultValue={matter?.case_number||""}/></label><label>Court<input name="court_name" defaultValue={matter?.court_name||""}/></label><label>Official/source URL<input name="source_url" placeholder="Optional provenance URL"/></label><div className="procedure-source-warning">Record information from an official/approved source. This feature does not bypass CAPTCHA or access controls.</div><button className="primary-button" disabled={busy}>Create tracker</button></form>:<form className="drawer-form" onSubmit={snapshotSubmit}><label>Tracker<select value={trackerId} onChange={e=>setTrackerId(e.target.value)}>{trackers.map(t=><option key={t.id} value={t.id}>{t.case_number||t.cnr_number||t.id.slice(0,8)}</option>)}</select></label><label>Case status<input name="case_status" placeholder="Pending / Disposed"/></label><label>Stage<input name="stage" placeholder="Arguments / Evidence / etc."/></label><label>Next hearing date<input name="next_hearing_date" type="date"/></label><label>Judge / bench<input name="judge"/></label><label>Total orders/proceedings detected<input name="order_count" type="number" min="0" defaultValue="0"/></label><label>Latest order date<input name="latest_order_date" type="date"/></label><label>Latest order reference<input name="order_reference" placeholder="Order date / reference"/></label><button className="primary-button" disabled={busy||!trackerId}>Record & compare</button></form>}</div></div>:null}
  </main>;
}
