"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createReleaseRun, decideDeployment, evaluateReleaseRun, getReleaseDashboard, getReleaseRun, type ReleaseDashboardRecord, type ReleaseRunDetailRecord } from "@/lib/api";
import { PulseIcon, ShieldIcon } from "@/components/icons";

type Tab="gate"|"performance"|"security"|"history";
const nice=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const dt=(v:string|null|undefined)=>v?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const bool=(v:boolean|null)=>v===true?"Pass":v===false?"Fail":"Pending";

export function ReleaseWorkspace(){
  const [tab,setTab]=useState<Tab>("gate");
  const [data,setData]=useState<ReleaseDashboardRecord|null>(null);
  const [detail,setDetail]=useState<ReleaseRunDetailRecord|null>(null);
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState<string|null>(null);
  const [error,setError]=useState<string|null>(null);
  const refresh=useCallback(async()=>{try{const d=await getReleaseDashboard();setData(d);setError(null);if(d.latest_runs[0])setDetail(await getReleaseRun(d.latest_runs[0].id))}catch(e){setError(e instanceof Error?e.message:"Unable to load release engineering")}},[]);
  useEffect(()=>{void refresh()},[refresh]);
  const latest=data?.latest_runs[0]??null;
  const gatePassed=Boolean(latest?.summary_json?.passed);
  const reasons=Array.isArray(latest?.summary_json?.reasons)?latest?.summary_json?.reasons as string[]:[];
  const stages=useMemo(()=>detail?.stages??[],[detail]);
  async function newRun(){setBusy(true);setMessage(null);try{await createReleaseRun({environment:"candidate",build_ref:`manual-${new Date().toISOString()}`});setMessage("Release candidate created. CI or staging probes must now submit every gate result.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to create release run")}finally{setBusy(false)}}
  async function evaluate(){if(!latest)return;setBusy(true);try{const result=await evaluateReleaseRun(latest.id);setMessage(result.passed?"Release gate passed.":"Release is held. Resolve every required gate before approval.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to evaluate release")}finally{setBusy(false)}}
  async function approval(decision:"approve"|"reject"){if(!latest)return;setBusy(true);try{await decideDeployment(latest.id,decision,decision==="approve"?"Deployment approved after recorded release gates.":"Deployment rejected by reviewer.");setMessage(decision==="approve"?"Deployment approval recorded.":"Release rejected.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to record decision")}finally{setBusy(false)}}
  return <main className="workspace-page release-workspace">
    <header className="workspace-header"><div><div className="eyebrow">Production controls</div><h1>Release engineering</h1><p>Legal accuracy, security, migrations, performance and rollback proof before deployment.</p></div><div className="health-header-actions"><button className="secondary-button" disabled={busy} onClick={()=>void refresh()}>Refresh</button><button className="primary-button" disabled={busy} onClick={()=>void newRun()}>New candidate</button></div></header>
    {error?<div className="error-banner">{error}</div>:null}{message?<div className="jobs-message">{message}</div>:null}
    <section className="metrics-grid release-metrics"><div className="metric-card"><span>Current version</span><strong>{data?.summary.app_version as string||"0.29.0-rc.1"}</strong><small>Candidate build</small></div><div className="metric-card"><span>Latest gate</span><strong className={`release-state ${gatePassed?"passed":latest?"held":"pending"}`}>{latest?nice(latest.status):"Not run"}</strong><small>{latest?dt(latest.created_at):"Create a candidate"}</small></div><div className="metric-card"><span>Security cases</span><strong>{String(data?.summary.security_cases??0)}</strong><small>{String(data?.summary.critical_security_cases??0)} critical</small></div><div className="metric-card"><span>Load scenarios</span><strong>{String(data?.summary.performance_scenarios??0)}</strong><small>Staging thresholds</small></div></section>
    <div className="workspace-tabs"><button className={tab==="gate"?"active":""} onClick={()=>setTab("gate")}>Release gate</button><button className={tab==="performance"?"active":""} onClick={()=>setTab("performance")}>Performance</button><button className={tab==="security"?"active":""} onClick={()=>setTab("security")}>Security</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>History</button></div>
    {tab==="gate"?<div className="release-grid"><section className="premium-panel"><div className="panel-title-row"><h2>Candidate gates</h2><span>{latest?.app_version??"No candidate"}</span></div>{stages.length?stages.map(s=><div className="release-stage" key={s.id}><span className={`health-dot ${s.status==="passed"?"healthy":s.status==="failed"?"down":"unknown"}`}></span><div><strong>{nice(s.kind)}</strong><small>{nice(s.status)}{s.duration_ms?` · ${s.duration_ms} ms`:""}</small></div><span className={`release-pill ${s.status}`}>{nice(s.status)}</span></div>):<div className="empty-state compact"><div className="empty-state-title">No release candidate</div><div className="empty-state-copy">Create one, then run the source gate plus representative staging load/security probes.</div></div>}</section><section className="premium-panel release-decision"><div className="panel-title-row"><h2>Deployment decision</h2><span>{gatePassed?"Eligible":"Held"}</span></div><div className={`release-gate-box ${gatePassed?"passed":"held"}`}>{gatePassed?<><ShieldIcon/><strong>All recorded gates passed</strong><p>A manager can record deployment approval. This does not deploy automatically.</p></>:<><PulseIcon/><strong>Release hold</strong><p>{reasons.length?reasons.join(" · "):"The release has not yet satisfied every required gate."}</p></>}</div><div className="release-decision-actions"><button className="secondary-button" disabled={busy||!latest} onClick={()=>void evaluate()}>Evaluate gates</button><button className="primary-button" disabled={busy||!gatePassed||!latest} onClick={()=>void approval("approve")}>Approve deployment</button>{latest?<button className="ghost-button" disabled={busy} onClick={()=>void approval("reject")}>Reject</button>:null}</div></section></div>:null}
    {tab==="performance"?<section className="premium-panel"><div className="panel-title-row"><h2>Performance scenarios</h2><span>Live staging required</span></div>{data?.performance_scenarios.map(s=><div className="release-scenario" key={s.id}><div><strong>{s.name}</strong><small>{s.method} {s.path} · {s.concurrency} concurrent · {s.request_count} requests</small></div><div><strong>p95 ≤ {s.max_p95_ms.toFixed(0)} ms</strong><small>Success ≥ {(s.min_success_rate*100).toFixed(1)}%</small></div></div>)}</section>:null}
    {tab==="security"?<section className="premium-panel"><div className="panel-title-row"><h2>Security release cases</h2><span>Zero critical failures</span></div>{data?.security_cases.map(s=><div className="release-security" key={s.id}><span className={`health-dot ${s.critical?"down":"degraded"}`}></span><div><strong>{s.title}</strong><small>{nice(s.kind)} · {s.description}</small></div><span>{s.critical?"Critical":"Standard"}</span></div>)}</section>:null}
    {tab==="history"?<section className="premium-panel"><div className="panel-title-row"><h2>Release history</h2><span>{data?.latest_runs.length??0}</span></div>{data?.latest_runs.map(r=><button className="release-history-row" key={r.id} onClick={()=>void getReleaseRun(r.id).then(setDetail)}><div><strong>{r.app_version} · {r.build_ref||r.id.slice(0,8)}</strong><small>{dt(r.created_at)} · {r.environment}</small></div><span className={`release-pill ${r.status}`}>{nice(r.status)}</span></button>)}</section>:null}
  </main>;
}
