"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  createValidationCampaign, evaluateValidationCampaign, getDeploymentDashboard, getReleaseDashboard,
  getValidationCampaign, getValidationDashboard, seedValidationScenarios, signoffValidationCampaign,
  updatePilotReadiness, type DeploymentDashboardRecord, type ReleaseDashboardRecord,
  type ValidationCampaignDetailRecord, type ValidationDashboardRecord,
} from "@/lib/api";
import { ShieldIcon, PulseIcon } from "@/components/icons";

type Tab="gate"|"scenarios"|"pilot"|"datasets";
const nice=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const dt=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";

export function ValidationWorkspace(){
  const [tab,setTab]=useState<Tab>("gate");
  const [data,setData]=useState<ValidationDashboardRecord|null>(null);
  const [detail,setDetail]=useState<ValidationCampaignDetailRecord|null>(null);
  const [release,setRelease]=useState<ReleaseDashboardRecord|null>(null);
  const [deployment,setDeployment]=useState<DeploymentDashboardRecord|null>(null);
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState<string|null>(null);
  const [error,setError]=useState<string|null>(null);
  const refresh=useCallback(async()=>{try{const [v,r,d]=await Promise.all([getValidationDashboard(),getReleaseDashboard(),getDeploymentDashboard()]);setData(v);setRelease(r);setDeployment(d);if(v.campaigns[0])setDetail(await getValidationCampaign(v.campaigns[0].id));else setDetail(null);setError(null)}catch(e){setError(e instanceof Error?e.message:"Unable to load release-candidate validation")}},[]);
  useEffect(()=>{void refresh()},[refresh]);
  const latest=data?.campaigns[0]??null;
  const scenarios=detail?.scenarios??data?.scenarios??[];
  const runByScenario=useMemo(()=>new Map((detail?.runs??[]).map(row=>[row.scenario_id,row])),[detail]);
  const reasons=Array.isArray(detail?.gate?.reasons)?detail!.gate.reasons as string[]:[];
  const passed=Boolean(detail?.gate?.passed)||detail?.manifest?.status==="approved";
  const approvedRelease=release?.latest_runs.find(row=>row.status==="approved")??null;
  const staging=deployment?.environments.find(row=>row.kind==="staging"&&row.enabled)??null;
  async function seed(){setBusy(true);try{await seedValidationScenarios();setMessage("RC validation scenarios seeded.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to seed scenarios")}finally{setBusy(false)}}
  async function create(){setBusy(true);try{const row=await createValidationCampaign({name:"Release Candidate 1 validation",candidate_version:"0.29.0-rc.1",release_run_id:approvedRelease?.id??null,environment_id:staging?.id??null,build_ref:`rc1-${new Date().toISOString()}`});setMessage("RC1 validation campaign created. Staging evidence is still required.");setDetail(await getValidationCampaign(row.id));await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to create campaign")}finally{setBusy(false)}}
  async function evaluate(){if(!latest)return;setBusy(true);try{const result=await evaluateValidationCampaign(latest.id);setMessage(result.gate.passed?"RC1 gate passed. Candidate is ready for controlled pilot.":"RC1 remains on HOLD. Missing staging/pilot evidence is listed below.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to evaluate RC gate")}finally{setBusy(false)}}
  async function signoff(){if(!latest)return;setBusy(true);try{await signoffValidationCampaign(latest.id,"approve","Reviewed release-candidate validation evidence.");setMessage("Validation sign-off recorded. Re-evaluate the gate to incorporate it.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to sign off")}finally{setBusy(false)}}
  async function check(id:string,status:"passed"|"failed"){if(!latest)return;setBusy(true);try{await updatePilotReadiness(latest.id,id,status,status==="passed"?"Reviewed for pilot readiness.":"Requires remediation before pilot.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to update pilot check")}finally{setBusy(false)}}
  return <main className="workspace-page validation-workspace">
    <header className="workspace-header"><div><div className="eyebrow">Feature freeze · RC1</div><h1>Production validation</h1><p>Staging evidence, authenticated security, recovery, scale and pilot readiness before real-lawyer use.</p></div><div className="health-header-actions"><button className="secondary-button" disabled={busy} onClick={()=>void refresh()}>Refresh</button><button className="secondary-button" disabled={busy} onClick={()=>void seed()}>Seed scenarios</button><button className="primary-button" disabled={busy} onClick={()=>void create()}>New RC1 campaign</button></div></header>
    {error?<div className="error-banner">{error}</div>:null}{message?<div className="jobs-message">{message}</div>:null}
    <section className="metrics-grid validation-metrics"><div className="metric-card"><span>Candidate</span><strong>{latest?.candidate_version??"0.29.0-rc.1"}</strong><small>Feature frozen</small></div><div className="metric-card"><span>RC gate</span><strong className={`release-state ${passed?"passed":latest?"held":"pending"}`}>{passed?"PASS":latest?"HOLD":"Not run"}</strong><small>{latest?dt(latest.created_at):"Create campaign"}</small></div><div className="metric-card"><span>Scenarios</span><strong>{scenarios.length}</strong><small>{scenarios.filter(s=>s.severity==="critical").length} critical</small></div><div className="metric-card"><span>Pilot checks</span><strong>{detail?.checks.filter(c=>c.status==="passed"||c.status==="waived").length??0}/{detail?.checks.length??0}</strong><small>Human-reviewed</small></div></section>
    <div className="workspace-tabs"><button className={tab==="gate"?"active":""} onClick={()=>setTab("gate")}>RC gate</button><button className={tab==="scenarios"?"active":""} onClick={()=>setTab("scenarios")}>Scenarios</button><button className={tab==="pilot"?"active":""} onClick={()=>setTab("pilot")}>Pilot readiness</button><button className={tab==="datasets"?"active":""} onClick={()=>setTab("datasets")}>Evidence & datasets</button></div>
    {tab==="gate"?<div className="release-grid"><section className="premium-panel"><div className="panel-title-row"><h2>Candidate requirements</h2><span>{detail?.manifest?.snapshot_hash?.slice(0,12)??"No manifest"}</span></div><div className={`release-gate-box ${passed?"passed":"held"}`}>{passed?<><ShieldIcon/><strong>RC1 validation passed</strong><p>Recorded critical/required scenarios, pilot checks, rollback, artifact and sign-off requirements are satisfied.</p></>:<><PulseIcon/><strong>Release candidate on hold</strong><p>{reasons.length?reasons.join(" · "):"Create a campaign and submit real staging evidence. Local source tests alone cannot pass RC1."}</p></>}</div><div className="release-decision-actions"><button className="secondary-button" disabled={!latest||busy} onClick={()=>void evaluate()}>Evaluate RC gate</button><button className="primary-button" disabled={!latest||busy} onClick={()=>void signoff()}>Record sign-off</button></div></section><section className="premium-panel"><div className="panel-title-row"><h2>Environment evidence</h2><span>Staging required</span></div><div className="validation-evidence-list"><div><strong>Approved release</strong><span>{approvedRelease?`${approvedRelease.app_version} · ${approvedRelease.build_ref||approvedRelease.id.slice(0,8)}`:"Missing"}</span></div><div><strong>Staging environment</strong><span>{staging?staging.name:"Missing"}</span></div><div><strong>Rollback verified</strong><span>{String(Boolean(detail?.gate?.rollback_verified))}</span></div><div><strong>Artifact integrity</strong><span>{String(Boolean(detail?.gate?.artifact_integrity))}</span></div><div><strong>Sign-offs</strong><span>{String(detail?.gate?.approval_signoffs??0)} / {String(detail?.gate?.minimum_signoffs??1)}</span></div></div></section></div>:null}
    {tab==="scenarios"?<section className="premium-panel"><div className="panel-title-row"><h2>Validation scenarios</h2><span>Critical + required must pass</span></div>{scenarios.map(s=>{const run=runByScenario.get(s.id);return <div className="validation-scenario-row" key={s.id}><span className={`risk-pip ${s.severity==="critical"?"critical":s.severity==="required"?"high":"medium"}`}/><div><strong>{s.name}</strong><small>{nice(s.kind)} · {nice(s.execution_mode)} · {s.description}</small></div><span className={`release-pill ${run?.status??"pending"}`}>{nice(run?.status??"pending")}</span></div>})}</section>:null}
    {tab==="pilot"?<section className="premium-panel"><div className="panel-title-row"><h2>Pilot readiness</h2><span>Manual review</span></div>{detail?.checks.map(c=><div className="validation-check-row" key={c.id}><div><strong>{c.label}</strong><small>{nice(c.category)} · {c.required?"Required":"Advisory"}{c.note?` · ${c.note}`:""}</small></div><span className={`release-pill ${c.status}`}>{nice(c.status)}</span><div><button className="ghost-button" disabled={busy} onClick={()=>void check(c.id,"passed")}>Pass</button><button className="ghost-button" disabled={busy} onClick={()=>void check(c.id,"failed")}>Fail</button></div></div>)??<div className="empty-state compact">Create an RC campaign first.</div>}</section>:null}
    {tab==="datasets"?<div className="release-grid"><section className="premium-panel"><div className="panel-title-row"><h2>Validation datasets</h2><span>Synthetic / de-identified</span></div>{detail?.datasets.length?detail.datasets.map(d=><div className="validation-dataset-row" key={d.id}><div><strong>{d.name}</strong><small>{nice(d.kind)} · {d.record_count.toLocaleString()} records · {d.page_count.toLocaleString()} pages</small></div><code>{d.sha256.slice(0,12)}…</code></div>):<div className="empty-state compact"><div className="empty-state-title">No dataset evidence recorded</div><div className="empty-state-copy">Use the synthetic fixture generator or register a de-identified staging dataset through the API.</div></div>}</section><section className="premium-panel"><div className="panel-title-row"><h2>RC manifest</h2><span>SHA-256</span></div>{detail?.manifest?<div className="validation-manifest"><strong>{nice(detail.manifest.status)}</strong><code>{detail.manifest.snapshot_hash}</code><small>DB {detail.manifest.database_revision??"—"} · artifact {detail.manifest.artifact_sha256?.slice(0,12)??"missing"}</small></div>:<div className="empty-state compact">Evaluate the campaign to create a manifest.</div>}</section></div>:null}
  </main>;
}
