"""legal data operations jurisdiction packs

Revision ID: 20260808_0025
Revises: 20260808_0024
Create Date: 2026-08-08 13:57:29.620386
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0025'
down_revision: Union[str, None] = '20260808_0024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdiction_packs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('pack_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('jurisdiction', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=160), nullable=True),
    sa.Column('languages_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active_release_version', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jurisdiction_packs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdiction_packs')),
    sa.UniqueConstraint('organization_id', 'pack_key', name='uq_jurisdiction_pack_org_key')
    )
    with op.batch_alter_table('jurisdiction_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jurisdiction_packs_jurisdiction'), ['jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_packs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_packs_pack_key'), ['pack_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_packs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_packs_status'), ['status'], unique=False)

    op.create_table('jurisdiction_pack_releases',
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_jurisdiction_pack_releases_approved_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pack_id'], ['jurisdiction_packs.id'], name=op.f('fk_jurisdiction_pack_releases_pack_id_jurisdiction_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdiction_pack_releases')),
    sa.UniqueConstraint('pack_id', 'version', name='uq_jurisdiction_pack_release_version')
    )
    with op.batch_alter_table('jurisdiction_pack_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jurisdiction_pack_releases_manifest_sha256'), ['manifest_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_pack_releases_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_pack_releases_status'), ['status'], unique=False)

    op.create_table('legal_data_feeds',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('jurisdiction', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=160), nullable=True),
    sa.Column('content_kind', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_domains_json', sa.JSON(), nullable=False),
    sa.Column('schedule_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('stale_after_hours', sa.Integer(), nullable=False),
    sa.Column('import_path', sa.String(length=800), nullable=True),
    sa.Column('cursor_json', sa.JSON(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_legal_data_feeds_connection_id_integration_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_legal_data_feeds_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['legal_sources.id'], name=op.f('fk_legal_data_feeds_source_id_legal_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_data_feeds')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_legal_data_feed_org_code')
    )
    with op.batch_alter_table('legal_data_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_content_kind'), ['content_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_jurisdiction'), ['jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_last_checked_at'), ['last_checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_last_manifest_sha256'), ['last_manifest_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_last_success_at'), ['last_success_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_next_due_at'), ['next_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_feeds_state'), ['state'], unique=False)

    op.create_table('jurisdiction_pack_sources',
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('maximum_age_hours', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['legal_data_feeds.id'], name=op.f('fk_jurisdiction_pack_sources_feed_id_legal_data_feeds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['jurisdiction_pack_releases.id'], name=op.f('fk_jurisdiction_pack_sources_release_id_jurisdiction_pack_releases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['legal_sources.id'], name=op.f('fk_jurisdiction_pack_sources_source_id_legal_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdiction_pack_sources')),
    sa.UniqueConstraint('release_id', 'source_id', 'feed_id', name='uq_jurisdiction_pack_release_source')
    )
    with op.batch_alter_table('jurisdiction_pack_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jurisdiction_pack_sources_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_pack_sources_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdiction_pack_sources_source_id'), ['source_id'], unique=False)

    op.create_table('legal_data_ingestion_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_label', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('items_succeeded', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('items_unchanged', sa.Integer(), nullable=False),
    sa.Column('items_changed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['legal_data_feeds.id'], name=op.f('fk_legal_data_ingestion_runs_feed_id_legal_data_feeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiated_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_legal_data_ingestion_runs_initiated_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_legal_data_ingestion_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_data_ingestion_runs'))
    )
    with op.batch_alter_table('legal_data_ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_runs_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_runs_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_runs_initiated_by_membership_id'), ['initiated_by_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_runs_manifest_sha256'), ['manifest_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_runs_trigger'), ['trigger'], unique=False)

    op.create_table('legal_corpus_checkpoints',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('statutes', sa.Integer(), nullable=False),
    sa.Column('sections', sa.Integer(), nullable=False),
    sa.Column('judgments', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.Integer(), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('aggregate_sha256', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_legal_corpus_checkpoints_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['legal_data_ingestion_runs.id'], name=op.f('fk_legal_corpus_checkpoints_run_id_legal_data_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_corpus_checkpoints'))
    )
    with op.batch_alter_table('legal_corpus_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_corpus_checkpoints_aggregate_sha256'), ['aggregate_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_corpus_checkpoints_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_corpus_checkpoints_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_corpus_checkpoints_run_id'), ['run_id'], unique=False)

    op.create_table('legal_data_alerts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['legal_data_feeds.id'], name=op.f('fk_legal_data_alerts_feed_id_legal_data_feeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_legal_data_alerts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_legal_data_alerts_resolved_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['legal_data_ingestion_runs.id'], name=op.f('fk_legal_data_alerts_run_id_legal_data_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_data_alerts'))
    )
    with op.batch_alter_table('legal_data_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_alerts_status'), ['status'], unique=False)

    op.create_table('legal_data_ingestion_items',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('declared_sha256', sa.String(length=64), nullable=True),
    sa.Column('actual_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('change_kind', sa.String(length=30), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('before_sha256', sa.String(length=64), nullable=True),
    sa.Column('after_sha256', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['legal_data_ingestion_runs.id'], name=op.f('fk_legal_data_ingestion_items_run_id_legal_data_ingestion_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_data_ingestion_items')),
    sa.UniqueConstraint('run_id', 'position', name='uq_legal_data_ingestion_item_position')
    )
    with op.batch_alter_table('legal_data_ingestion_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_items_actual_sha256'), ['actual_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_items_change_kind'), ['change_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_items_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_items_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_items_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_ingestion_items_status'), ['status'], unique=False)

    op.create_table('legal_data_source_snapshots',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('previous_sha256', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['legal_data_feeds.id'], name=op.f('fk_legal_data_source_snapshots_feed_id_legal_data_feeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_legal_data_source_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['legal_data_ingestion_runs.id'], name=op.f('fk_legal_data_source_snapshots_run_id_legal_data_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_data_source_snapshots')),
    sa.UniqueConstraint('feed_id', 'kind', 'external_id', 'content_sha256', name='uq_legal_data_source_snapshot_hash')
    )
    with op.batch_alter_table('legal_data_source_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_data_source_snapshots_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_source_snapshots_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_source_snapshots_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_source_snapshots_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_source_snapshots_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_source_snapshots_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_source_snapshots_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_source_snapshots_verification_status'), ['verification_status'], unique=False)

    op.create_table('legal_data_integrity_checks',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('feed_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('ingestion_item_id', sa.Uuid(), nullable=True),
    sa.Column('check_kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['legal_data_feeds.id'], name=op.f('fk_legal_data_integrity_checks_feed_id_legal_data_feeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_item_id'], ['legal_data_ingestion_items.id'], name=op.f('fk_legal_data_integrity_checks_ingestion_item_id_legal_data_ingestion_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_legal_data_integrity_checks_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['legal_data_ingestion_runs.id'], name=op.f('fk_legal_data_integrity_checks_run_id_legal_data_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_data_integrity_checks'))
    )
    with op.batch_alter_table('legal_data_integrity_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_data_integrity_checks_check_kind'), ['check_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_integrity_checks_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_integrity_checks_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_integrity_checks_ingestion_item_id'), ['ingestion_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_integrity_checks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_integrity_checks_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_data_integrity_checks_status'), ['status'], unique=False)

    op.create_table('statute_amendment_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('statute_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('ingestion_item_id', sa.Uuid(), nullable=True),
    sa.Column('event_kind', sa.String(length=60), nullable=False),
    sa.Column('section_number', sa.String(length=100), nullable=True),
    sa.Column('previous_sha256', sa.String(length=64), nullable=True),
    sa.Column('new_sha256', sa.String(length=64), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=False),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_item_id'], ['legal_data_ingestion_items.id'], name=op.f('fk_statute_amendment_events_ingestion_item_id_legal_data_ingestion_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_statute_amendment_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_statute_amendment_events_reviewed_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['statute_sections.id'], name=op.f('fk_statute_amendment_events_section_id_statute_sections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statute_id'], ['statutes.id'], name=op.f('fk_statute_amendment_events_statute_id_statutes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statute_amendment_events'))
    )
    with op.batch_alter_table('statute_amendment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_event_kind'), ['event_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_ingestion_item_id'), ['ingestion_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_section_number'), ['section_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_statute_amendment_events_statute_id'), ['statute_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statute_amendment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_statute_id'))
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_section_number'))
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_section_id'))
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_review_status'))
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_ingestion_item_id'))
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_event_kind'))
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_effective_date'))
        batch_op.drop_index(batch_op.f('ix_statute_amendment_events_detected_at'))

    op.drop_table('statute_amendment_events')
    with op.batch_alter_table('legal_data_integrity_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_data_integrity_checks_status'))
        batch_op.drop_index(batch_op.f('ix_legal_data_integrity_checks_run_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_integrity_checks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_integrity_checks_ingestion_item_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_integrity_checks_feed_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_integrity_checks_checked_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_integrity_checks_check_kind'))

    op.drop_table('legal_data_integrity_checks')
    with op.batch_alter_table('legal_data_source_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_data_source_snapshots_verification_status'))
        batch_op.drop_index(batch_op.f('ix_legal_data_source_snapshots_run_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_source_snapshots_organization_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_source_snapshots_observed_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_source_snapshots_kind'))
        batch_op.drop_index(batch_op.f('ix_legal_data_source_snapshots_feed_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_source_snapshots_external_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_source_snapshots_content_sha256'))

    op.drop_table('legal_data_source_snapshots')
    with op.batch_alter_table('legal_data_ingestion_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_items_status'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_items_run_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_items_resource_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_items_kind'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_items_external_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_items_change_kind'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_items_actual_sha256'))

    op.drop_table('legal_data_ingestion_items')
    with op.batch_alter_table('legal_data_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_run_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_kind'))
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_first_seen_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_feed_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_alerts_dedupe_key'))

    op.drop_table('legal_data_alerts')
    with op.batch_alter_table('legal_corpus_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_corpus_checkpoints_run_id'))
        batch_op.drop_index(batch_op.f('ix_legal_corpus_checkpoints_organization_id'))
        batch_op.drop_index(batch_op.f('ix_legal_corpus_checkpoints_captured_at'))
        batch_op.drop_index(batch_op.f('ix_legal_corpus_checkpoints_aggregate_sha256'))

    op.drop_table('legal_corpus_checkpoints')
    with op.batch_alter_table('legal_data_ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_runs_trigger'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_runs_status'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_runs_manifest_sha256'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_runs_initiated_by_membership_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_runs_finished_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_ingestion_runs_feed_id'))

    op.drop_table('legal_data_ingestion_runs')
    with op.batch_alter_table('jurisdiction_pack_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jurisdiction_pack_sources_source_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_pack_sources_release_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_pack_sources_feed_id'))

    op.drop_table('jurisdiction_pack_sources')
    with op.batch_alter_table('legal_data_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_state'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_source_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_organization_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_next_due_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_mode'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_last_success_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_last_manifest_sha256'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_last_checked_at'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_jurisdiction'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_enabled'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_content_kind'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_connection_id'))
        batch_op.drop_index(batch_op.f('ix_legal_data_feeds_code'))

    op.drop_table('legal_data_feeds')
    with op.batch_alter_table('jurisdiction_pack_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jurisdiction_pack_releases_status'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_pack_releases_pack_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_pack_releases_manifest_sha256'))

    op.drop_table('jurisdiction_pack_releases')
    with op.batch_alter_table('jurisdiction_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jurisdiction_packs_status'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_packs_state'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_packs_pack_key'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_packs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdiction_packs_jurisdiction'))

    op.drop_table('jurisdiction_packs')
    # ### end Alembic commands ###
