"""release engineering load security testing

Revision ID: 20260808_0022
Revises: 20260808_0021
Create Date: 2026-08-08 12:43:08.812214
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0022'
down_revision: Union[str, None] = '20260808_0021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_scenarios',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_key', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('max_p95_ms', sa.Float(), nullable=False),
    sa.Column('min_success_rate', sa.Float(), nullable=False),
    sa.Column('max_error_rate', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('headers_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_performance_scenarios_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_scenarios')),
    sa.UniqueConstraint('organization_id', 'scenario_key', name='uq_performance_scenario_org_key')
    )
    with op.batch_alter_table('performance_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_scenarios_critical'), ['critical'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_scenarios_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_scenarios_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_scenarios_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_scenarios_scenario_key'), ['scenario_key'], unique=False)

    op.create_table('release_pipelines',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('require_qa_gate', sa.Boolean(), nullable=False),
    sa.Column('require_security_zero_critical', sa.Boolean(), nullable=False),
    sa.Column('require_migration_roundtrip', sa.Boolean(), nullable=False),
    sa.Column('require_frontend_static', sa.Boolean(), nullable=False),
    sa.Column('require_load_gate', sa.Boolean(), nullable=False),
    sa.Column('thresholds_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_release_pipelines_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_pipelines')),
    sa.UniqueConstraint('organization_id', 'pipeline_key', name='uq_release_pipeline_org_key')
    )
    with op.batch_alter_table('release_pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_pipelines_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_pipelines_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_pipelines_pipeline_key'), ['pipeline_key'], unique=False)

    op.create_table('security_test_cases',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('case_key', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('expected_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_security_test_cases_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_test_cases')),
    sa.UniqueConstraint('organization_id', 'case_key', name='uq_security_test_case_org_key')
    )
    with op.batch_alter_table('security_test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_test_cases_case_key'), ['case_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_test_cases_critical'), ['critical'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_test_cases_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_test_cases_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_test_cases_organization_id'), ['organization_id'], unique=False)

    op.create_table('release_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('app_version', sa.String(length=80), nullable=False),
    sa.Column('build_ref', sa.String(length=180), nullable=True),
    sa.Column('commit_ref', sa.String(length=180), nullable=True),
    sa.Column('environment', sa.String(length=60), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qa_passed', sa.Boolean(), nullable=True),
    sa.Column('security_passed', sa.Boolean(), nullable=True),
    sa.Column('load_passed', sa.Boolean(), nullable=True),
    sa.Column('migration_passed', sa.Boolean(), nullable=True),
    sa.Column('frontend_passed', sa.Boolean(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_release_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['release_pipelines.id'], name=op.f('fk_release_runs_pipeline_id_release_pipelines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_release_runs_requested_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_runs'))
    )
    with op.batch_alter_table('release_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_runs_app_version'), ['app_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_runs_build_ref'), ['build_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_runs_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_runs_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_runs_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_runs_status'), ['status'], unique=False)

    op.create_table('deployment_approvals',
    sa.Column('release_run_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_deployment_approvals_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_deployment_approvals_release_run_id_release_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_approvals')),
    sa.UniqueConstraint('release_run_id', 'membership_id', name='uq_deployment_approval_run_member')
    )
    with op.batch_alter_table('deployment_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_approvals_decided_at'), ['decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_approvals_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_approvals_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_approvals_release_run_id'), ['release_run_id'], unique=False)

    op.create_table('performance_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('release_run_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('requests_per_second', sa.Float(), nullable=False),
    sa.Column('p50_ms', sa.Float(), nullable=False),
    sa.Column('p95_ms', sa.Float(), nullable=False),
    sa.Column('p99_ms', sa.Float(), nullable=False),
    sa.Column('max_ms', sa.Float(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_performance_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_performance_runs_release_run_id_release_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['performance_scenarios.id'], name=op.f('fk_performance_runs_scenario_id_performance_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_runs'))
    )
    with op.batch_alter_table('performance_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_runs_release_run_id'), ['release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_runs_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_runs_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_runs_status'), ['status'], unique=False)

    op.create_table('release_artifacts',
    sa.Column('release_run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_release_artifacts_release_run_id_release_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_artifacts'))
    )
    with op.batch_alter_table('release_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_artifacts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_artifacts_release_run_id'), ['release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('release_stage_runs',
    sa.Column('release_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_key', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_release_stage_runs_release_run_id_release_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_stage_runs')),
    sa.UniqueConstraint('release_run_id', 'stage_key', name='uq_release_stage_run_key')
    )
    with op.batch_alter_table('release_stage_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_stage_runs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_stage_runs_release_run_id'), ['release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_stage_runs_stage_key'), ['stage_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_stage_runs_status'), ['status'], unique=False)

    op.create_table('security_test_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('release_run_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_json', sa.JSON(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['security_test_cases.id'], name=op.f('fk_security_test_runs_case_id_security_test_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_security_test_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_security_test_runs_release_run_id_release_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_test_runs'))
    )
    with op.batch_alter_table('security_test_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_test_runs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_test_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_test_runs_release_run_id'), ['release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_test_runs_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_test_runs_status'), ['status'], unique=False)

    op.create_table('rollback_points',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('release_run_id', sa.Uuid(), nullable=False),
    sa.Column('app_version', sa.String(length=80), nullable=False),
    sa.Column('database_revision', sa.String(length=160), nullable=True),
    sa.Column('release_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('backup_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backup_run_id'], ['backup_runs.id'], name=op.f('fk_rollback_points_backup_run_id_backup_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rollback_points_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_artifact_id'], ['release_artifacts.id'], name=op.f('fk_rollback_points_release_artifact_id_release_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_rollback_points_release_run_id_release_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rollback_points'))
    )
    with op.batch_alter_table('rollback_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rollback_points_app_version'), ['app_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollback_points_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollback_points_release_run_id'), ['release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollback_points_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollback_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollback_points_status'))
        batch_op.drop_index(batch_op.f('ix_rollback_points_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_rollback_points_organization_id'))
        batch_op.drop_index(batch_op.f('ix_rollback_points_app_version'))

    op.drop_table('rollback_points')
    with op.batch_alter_table('security_test_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_test_runs_status'))
        batch_op.drop_index(batch_op.f('ix_security_test_runs_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_security_test_runs_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_security_test_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_security_test_runs_case_id'))

    op.drop_table('security_test_runs')
    with op.batch_alter_table('release_stage_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_stage_runs_status'))
        batch_op.drop_index(batch_op.f('ix_release_stage_runs_stage_key'))
        batch_op.drop_index(batch_op.f('ix_release_stage_runs_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_release_stage_runs_kind'))

    op.drop_table('release_stage_runs')
    with op.batch_alter_table('release_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_artifacts_sha256'))
        batch_op.drop_index(batch_op.f('ix_release_artifacts_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_release_artifacts_kind'))

    op.drop_table('release_artifacts')
    with op.batch_alter_table('performance_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_runs_status'))
        batch_op.drop_index(batch_op.f('ix_performance_runs_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_performance_runs_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_performance_runs_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_performance_runs_organization_id'))

    op.drop_table('performance_runs')
    with op.batch_alter_table('deployment_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_membership_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_decision'))
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_decided_at'))

    op.drop_table('deployment_approvals')
    with op.batch_alter_table('release_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_runs_status'))
        batch_op.drop_index(batch_op.f('ix_release_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_release_runs_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_release_runs_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_release_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_release_runs_environment'))
        batch_op.drop_index(batch_op.f('ix_release_runs_build_ref'))
        batch_op.drop_index(batch_op.f('ix_release_runs_app_version'))

    op.drop_table('release_runs')
    with op.batch_alter_table('security_test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_test_cases_organization_id'))
        batch_op.drop_index(batch_op.f('ix_security_test_cases_kind'))
        batch_op.drop_index(batch_op.f('ix_security_test_cases_enabled'))
        batch_op.drop_index(batch_op.f('ix_security_test_cases_critical'))
        batch_op.drop_index(batch_op.f('ix_security_test_cases_case_key'))

    op.drop_table('security_test_cases')
    with op.batch_alter_table('release_pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_pipelines_pipeline_key'))
        batch_op.drop_index(batch_op.f('ix_release_pipelines_organization_id'))
        batch_op.drop_index(batch_op.f('ix_release_pipelines_enabled'))

    op.drop_table('release_pipelines')
    with op.batch_alter_table('performance_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_scenarios_scenario_key'))
        batch_op.drop_index(batch_op.f('ix_performance_scenarios_organization_id'))
        batch_op.drop_index(batch_op.f('ix_performance_scenarios_kind'))
        batch_op.drop_index(batch_op.f('ix_performance_scenarios_enabled'))
        batch_op.drop_index(batch_op.f('ix_performance_scenarios_critical'))

    op.drop_table('performance_scenarios')
    # ### end Alembic commands ###
