"""law firm security and multi user workspace

Revision ID: 20260808_0009
Revises: 20260808_0008
Create Date: 2026-08-08 05:01:49.052232
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260808_0009"
down_revision: Union[str, None] = '20260808_0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='organizationstatus', native_enum=False), nullable=False),
    sa.Column('default_language', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_status'), ['status'], unique=False)

    op.create_table('security_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=250), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus', native_enum=False), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('mfa_enrolled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_users'))
    )
    with op.batch_alter_table('security_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_security_users_mfa_enrolled'), ['mfa_enrolled'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_users_status'), ['status'], unique=False)

    op.create_table('audit_chain_heads',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('head_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_chain_heads_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_chain_heads')),
    sa.UniqueConstraint('organization_id', name='uq_audit_chain_head_org')
    )
    with op.batch_alter_table('audit_chain_heads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_chain_heads_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'PARTNER', 'LAWYER', 'JUNIOR', 'PARALEGAL', 'BILLING', 'READ_ONLY', name='organizationrole', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'SUSPENDED', name='membershipstatus', native_enum=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['security_users.id'], name=op.f('fk_organization_memberships_invited_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['security_users.id'], name=op.f('fk_organization_memberships_user_id_security_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_memberships_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('organization_security_policies',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('session_idle_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('session_absolute_lifetime_hours', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=False),
    sa.Column('max_failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_minutes', sa.Integer(), nullable=False),
    sa.Column('allow_remote_ai_default', sa.Boolean(), nullable=False),
    sa.Column('allow_exports_default', sa.Boolean(), nullable=False),
    sa.Column('require_mfa_for_remote_ai', sa.Boolean(), nullable=False),
    sa.Column('require_mfa_for_highly_confidential', sa.Boolean(), nullable=False),
    sa.Column('audit_log_retention_days', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_security_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_security_policies')),
    sa.UniqueConstraint('organization_id', name='uq_security_policy_organization')
    )
    with op.batch_alter_table('organization_security_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_security_policies_organization_id'), ['organization_id'], unique=False)

    op.create_table('retention_policies',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('MATTER', 'DOCUMENT', 'AI_RUN', 'DRAFT', 'CONTRACT', 'AUDIT', name='retentionresourcetype', native_enum=False), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_delete_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_retention_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policies')),
    sa.UniqueConstraint('organization_id', 'resource_type', name='uq_retention_org_resource')
    )
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_policies_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_policies_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_policies_resource_type'), ['resource_type'], unique=False)

    op.create_table('legal_holds',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RELEASED', name='legalholdstatus', native_enum=False), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('released_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['security_users.id'], name=op.f('fk_legal_holds_created_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_legal_holds_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_legal_holds_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by_user_id'], ['security_users.id'], name=op.f('fk_legal_holds_released_by_user_id_security_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_holds'))
    )
    with op.batch_alter_table('legal_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_holds_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_holds_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_holds_status'), ['status'], unique=False)

    op.create_table('matter_access_grants',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('effect', sa.Enum('ALLOW', 'DENY', name='accesseffect', native_enum=False), nullable=False),
    sa.Column('access_level', sa.Enum('VIEW', 'WORK', 'MANAGE', name='matteraccesslevel', native_enum=False), nullable=False),
    sa.Column('allow_remote_ai', sa.Boolean(), nullable=True),
    sa.Column('allow_export', sa.Boolean(), nullable=True),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['security_users.id'], name=op.f('fk_matter_access_grants_granted_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_matter_access_grants_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_matter_access_grants_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_access_grants')),
    sa.UniqueConstraint('matter_id', 'membership_id', name='uq_matter_grant_membership')
    )
    with op.batch_alter_table('matter_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matter_access_grants_access_level'), ['access_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_access_grants_effect'), ['effect'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_access_grants_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_access_grants_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_access_grants_membership_id'), ['membership_id'], unique=False)

    op.create_table('matter_security_profiles',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.Enum('INTERNAL', 'CONFIDENTIAL', 'HIGHLY_CONFIDENTIAL', 'ETHICAL_WALL', name='confidentialitylevel', native_enum=False), nullable=False),
    sa.Column('access_mode', sa.Enum('ORGANIZATION', 'EXPLICIT', name='matteraccessmode', native_enum=False), nullable=False),
    sa.Column('remote_ai_policy', sa.Enum('INHERIT', 'ALLOW', 'DENY', name='policydecision', native_enum=False), nullable=False),
    sa.Column('export_policy', sa.Enum('INHERIT', 'ALLOW', 'DENY', name='policydecision', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['security_users.id'], name=op.f('fk_matter_security_profiles_created_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_matter_security_profiles_matter_id_matters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_security_profiles')),
    sa.UniqueConstraint('matter_id', name='uq_matter_security_profile_matter')
    )
    with op.batch_alter_table('matter_security_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matter_security_profiles_access_mode'), ['access_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_security_profiles_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_security_profiles_export_policy'), ['export_policy'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_security_profiles_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_security_profiles_remote_ai_policy'), ['remote_ai_policy'], unique=False)

    op.create_table('security_audit_entries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_membership_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.Enum('SUCCESS', 'FAILURE', 'ALLOWED', 'DENIED', name='auditoutcome', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(length=700), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_mode', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_membership_id'], ['organization_memberships.id'], name=op.f('fk_security_audit_entries_actor_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['security_users.id'], name=op.f('fk_security_audit_entries_actor_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_security_audit_entries_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_audit_entries')),
    sa.UniqueConstraint('event_hash', name='uq_audit_event_hash'),
    sa.UniqueConstraint('organization_id', 'sequence', name='uq_audit_org_sequence')
    )
    with op.batch_alter_table('security_audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_audit_entries_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_actor_membership_id'), ['actor_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_event_hash'), ['event_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_sequence'), ['sequence'], unique=False)

    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('password_version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=300), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('auth_method', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_user_sessions_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['security_users.id'], name=op.f('fk_user_sessions_user_id_security_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_absolute_expires_at'), ['absolute_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('deletion_requests',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('MATTER', 'DOCUMENT', 'AI_RUN', 'DRAFT', 'CONTRACT', 'AUDIT', name='retentionresourcetype', native_enum=False), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'BLOCKED', 'APPROVED', 'CANCELLED', 'EXECUTED', name='deletionstatus', native_enum=False), nullable=False),
    sa.Column('hold_id', sa.Uuid(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['security_users.id'], name=op.f('fk_deletion_requests_approved_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hold_id'], ['legal_holds.id'], name=op.f('fk_deletion_requests_hold_id_legal_holds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_deletion_requests_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['security_users.id'], name=op.f('fk_deletion_requests_requested_by_user_id_security_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deletion_requests'))
    )
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deletion_requests_hold_id'), ['hold_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_requests_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_requests_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_requests_status'), ['status'], unique=False)

    op.create_table('document_access_grants',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('effect', sa.Enum('ALLOW', 'DENY', name='accesseffect', native_enum=False), nullable=False),
    sa.Column('access_level', sa.Enum('VIEW', 'DOWNLOAD', 'EDIT', name='documentaccesslevel', native_enum=False), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_access_grants_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['security_users.id'], name=op.f('fk_document_access_grants_granted_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_document_access_grants_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_access_grants')),
    sa.UniqueConstraint('document_id', 'membership_id', name='uq_document_grant_membership')
    )
    with op.batch_alter_table('document_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_access_grants_access_level'), ['access_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_access_grants_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_access_grants_effect'), ['effect'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_access_grants_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_access_grants_membership_id'), ['membership_id'], unique=False)

    with op.batch_alter_table('contract_playbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_contract_playbook_name_type'), type_='unique')
        batch_op.create_index(batch_op.f('ix_contract_playbooks_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_playbooks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_unique_constraint('uq_contract_playbook_org_name_type', ['organization_id', 'name', 'contract_type'])
        batch_op.create_foreign_key(batch_op.f('fk_contract_playbooks_organization_id_organizations'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_contract_playbooks_created_by_user_id_security_users'), 'security_users', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contracts_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_contracts_organization_id_organizations'), 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_contracts_created_by_user_id_security_users'), 'security_users', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('legal_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_sources_code'))
        batch_op.create_index(batch_op.f('ix_legal_sources_code'), ['code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_legal_sources_code'), ['code'])

    with op.batch_alter_table('counterparty_contract_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_counterparty_contract_reviews_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_contract_reviews_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_counterparty_contract_reviews_created_by_user_id_security_users'), 'security_users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_counterparty_contract_reviews_organization_id_organizations'), 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')

    # Normalize two legacy uniqueness definitions to the current ORM representation.
    # Semantics remain unique; SQLite stores these as unique indexes in the current model.
    with op.batch_alter_table('legal_sources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_legal_sources_code'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_legal_sources_code'))
        batch_op.create_index(batch_op.f('ix_legal_sources_code'), ['code'], unique=True)

    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_matters_reference_number'), type_='unique')
        batch_op.create_index(batch_op.f('ix_matters_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matters_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_matters_created_by_user_id_security_users'), 'security_users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_matters_organization_id_organizations'), 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_matters_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_matters_created_by_user_id_security_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_matters_organization_id'))
        batch_op.drop_index(batch_op.f('ix_matters_created_by_user_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_matters_reference_number'), ['reference_number'])
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('counterparty_contract_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_counterparty_contract_reviews_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_counterparty_contract_reviews_created_by_user_id_security_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_counterparty_contract_reviews_organization_id'))
        batch_op.drop_index(batch_op.f('ix_counterparty_contract_reviews_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contracts_created_by_user_id_security_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contracts_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('contract_playbooks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contract_playbooks_created_by_user_id_security_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contract_playbooks_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint('uq_contract_playbook_org_name_type', type_='unique')
        batch_op.drop_index(batch_op.f('ix_contract_playbooks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contract_playbooks_created_by_user_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_contract_playbook_name_type'), ['name', 'contract_type'])
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('document_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_access_grants_membership_id'))
        batch_op.drop_index(batch_op.f('ix_document_access_grants_expires_at'))
        batch_op.drop_index(batch_op.f('ix_document_access_grants_effect'))
        batch_op.drop_index(batch_op.f('ix_document_access_grants_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_access_grants_access_level'))

    op.drop_table('document_access_grants')
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deletion_requests_status'))
        batch_op.drop_index(batch_op.f('ix_deletion_requests_resource_type'))
        batch_op.drop_index(batch_op.f('ix_deletion_requests_resource_id'))
        batch_op.drop_index(batch_op.f('ix_deletion_requests_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_deletion_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deletion_requests_hold_id'))

    op.drop_table('deletion_requests')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_membership_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_absolute_expires_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('security_audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_sequence'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_resource_type'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_resource_id'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_request_id'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_outcome'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_event_hash'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_actor_membership_id'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_action'))

    op.drop_table('security_audit_entries')
    with op.batch_alter_table('matter_security_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matter_security_profiles_remote_ai_policy'))
        batch_op.drop_index(batch_op.f('ix_matter_security_profiles_matter_id'))
        batch_op.drop_index(batch_op.f('ix_matter_security_profiles_export_policy'))
        batch_op.drop_index(batch_op.f('ix_matter_security_profiles_classification'))
        batch_op.drop_index(batch_op.f('ix_matter_security_profiles_access_mode'))

    op.drop_table('matter_security_profiles')
    with op.batch_alter_table('matter_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matter_access_grants_membership_id'))
        batch_op.drop_index(batch_op.f('ix_matter_access_grants_matter_id'))
        batch_op.drop_index(batch_op.f('ix_matter_access_grants_expires_at'))
        batch_op.drop_index(batch_op.f('ix_matter_access_grants_effect'))
        batch_op.drop_index(batch_op.f('ix_matter_access_grants_access_level'))

    op.drop_table('matter_access_grants')
    with op.batch_alter_table('legal_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_holds_status'))
        batch_op.drop_index(batch_op.f('ix_legal_holds_organization_id'))
        batch_op.drop_index(batch_op.f('ix_legal_holds_matter_id'))

    op.drop_table('legal_holds')
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_policies_resource_type'))
        batch_op.drop_index(batch_op.f('ix_retention_policies_organization_id'))
        batch_op.drop_index(batch_op.f('ix_retention_policies_enabled'))

    op.drop_table('retention_policies')
    with op.batch_alter_table('organization_security_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_security_policies_organization_id'))

    op.drop_table('organization_security_policies')
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_status'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_role'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_is_default'))

    op.drop_table('organization_memberships')
    with op.batch_alter_table('audit_chain_heads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_chain_heads_organization_id'))

    op.drop_table('audit_chain_heads')
    with op.batch_alter_table('security_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_users_status'))
        batch_op.drop_index(batch_op.f('ix_security_users_mfa_enrolled'))
        batch_op.drop_index(batch_op.f('ix_security_users_email'))

    op.drop_table('security_users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_status'))
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_name'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
