"""workflow automation court operations

Revision ID: 20260808_0013
Revises: 20260808_0012
Create Date: 2026-08-08 07:51:11.456554
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0013'
down_revision: Union[str, None] = '20260808_0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=False),
    sa.Column('name_hi', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DISABLED', name='workflowtemplatestatus', native_enum=False), nullable=False),
    sa.Column('trigger_type', sa.String(length=160), nullable=False),
    sa.Column('conditions_json', sa.JSON(), nullable=False),
    sa.Column('actions_json', sa.JSON(), nullable=False),
    sa.Column('source_label', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflow_templates_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_templates')),
    sa.UniqueConstraint('organization_id', 'code', 'version', name='uq_workflow_template_org_code_version')
    )
    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_templates_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_templates_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_templates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_templates_trigger_type'), ['trigger_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_templates_version'), ['version'], unique=False)

    op.create_table('court_case_trackers',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('source_kind', sa.Enum('MANUAL', 'ECOURTS_MANUAL', 'OFFICIAL_IMPORT', 'MOCK', name='courtsourcekind', native_enum=False), nullable=False),
    sa.Column('cnr_number', sa.String(length=32), nullable=True),
    sa.Column('case_number', sa.String(length=160), nullable=True),
    sa.Column('court_name', sa.String(length=300), nullable=True),
    sa.Column('bench_name', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CLOSED', name='courttrackerstatus', native_enum=False), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_court_case_trackers_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_court_case_trackers_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_court_case_trackers')),
    sa.UniqueConstraint('matter_id', 'source_kind', name='uq_court_tracker_matter_source')
    )
    with op.batch_alter_table('court_case_trackers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_case_trackers_case_number'), ['case_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_trackers_cnr_number'), ['cnr_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_trackers_court_name'), ['court_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_trackers_last_checked_at'), ['last_checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_trackers_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_trackers_next_check_at'), ['next_check_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_trackers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_trackers_source_kind'), ['source_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_trackers_status'), ['status'], unique=False)

    op.create_table('operations_preferences',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('daily_agenda_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_agenda_hour_local', sa.Integer(), nullable=False),
    sa.Column('due_soon_hours', sa.Integer(), nullable=False),
    sa.Column('overdue_escalation_hours', sa.Integer(), nullable=False),
    sa.Column('channels_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_operations_preferences_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_operations_preferences_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations_preferences')),
    sa.UniqueConstraint('membership_id', name='uq_operations_preference_membership')
    )
    with op.batch_alter_table('operations_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_preferences_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_preferences_organization_id'), ['organization_id'], unique=False)

    op.create_table('workflow_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=120), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_workflow_events_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflow_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_events')),
    sa.UniqueConstraint('organization_id', 'dedupe_key', name='uq_workflow_event_org_dedupe')
    )
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_events_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_source_type'), ['source_type'], unique=False)

    op.create_table('court_case_snapshots',
    sa.Column('tracker_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_status', sa.String(length=160), nullable=True),
    sa.Column('stage', sa.String(length=240), nullable=True),
    sa.Column('next_hearing_date', sa.Date(), nullable=True),
    sa.Column('judge_or_bench', sa.String(length=300), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('latest_order_date', sa.Date(), nullable=True),
    sa.Column('latest_order_reference', sa.String(length=300), nullable=True),
    sa.Column('source_payload_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['court_case_trackers.id'], name=op.f('fk_court_case_snapshots_tracker_id_court_case_trackers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_court_case_snapshots'))
    )
    with op.batch_alter_table('court_case_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_case_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_snapshots_case_status'), ['case_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_snapshots_latest_order_date'), ['latest_order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_snapshots_next_hearing_date'), ['next_hearing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_snapshots_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_snapshots_tracker_id'), ['tracker_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowrunstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_workflow_runs_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflow_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], name=op.f('fk_workflow_runs_template_id_workflow_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['workflow_events.id'], name=op.f('fk_workflow_runs_trigger_event_id_workflow_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_trigger_event_id'), ['trigger_event_id'], unique=False)

    op.create_table('court_case_changes',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('tracker_id', sa.Uuid(), nullable=False),
    sa.Column('previous_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('current_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.Enum('NEW_ORDER', 'HEARING_DATE_CHANGED', 'CASE_STATUS_CHANGED', 'STAGE_CHANGED', 'JUDGE_CHANGED', name='courtchangetype', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'MEDIUM', 'HIGH', name='changeseverity', native_enum=False), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['court_case_snapshots.id'], name=op.f('fk_court_case_changes_current_snapshot_id_court_case_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_court_case_changes_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_court_case_changes_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['court_case_snapshots.id'], name=op.f('fk_court_case_changes_previous_snapshot_id_court_case_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['security_users.id'], name=op.f('fk_court_case_changes_reviewed_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_id'], ['court_case_trackers.id'], name=op.f('fk_court_case_changes_tracker_id_court_case_trackers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_event_id'], ['workflow_events.id'], name=op.f('fk_court_case_changes_workflow_event_id_workflow_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_court_case_changes'))
    )
    with op.batch_alter_table('court_case_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_case_changes_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_changes_current_snapshot_id'), ['current_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_changes_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_changes_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_changes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_changes_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_changes_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_changes_tracker_id'), ['tracker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_case_changes_workflow_event_id'), ['workflow_event_id'], unique=False)

    op.create_table('workflow_tasks',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_membership_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=350), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='workflowtaskstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='workflowtaskpriority', native_enum=False), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_membership_id'], ['organization_memberships.id'], name=op.f('fk_workflow_tasks_assigned_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['security_users.id'], name=op.f('fk_workflow_tasks_created_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_workflow_tasks_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflow_tasks_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_event_id'], ['workflow_events.id'], name=op.f('fk_workflow_tasks_source_event_id_workflow_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_workflow_tasks_workflow_run_id_workflow_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_tasks'))
    )
    with op.batch_alter_table('workflow_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_tasks_assigned_membership_id'), ['assigned_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_escalation_level'), ['escalation_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_tasks_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('workflow_escalations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('escalated_to_membership_id', sa.Uuid(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['security_users.id'], name=op.f('fk_workflow_escalations_acknowledged_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalated_to_membership_id'], ['organization_memberships.id'], name=op.f('fk_workflow_escalations_escalated_to_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflow_escalations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_tasks.id'], name=op.f('fk_workflow_escalations_task_id_workflow_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_escalations'))
    )
    with op.batch_alter_table('workflow_escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_escalations_escalated_at'), ['escalated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_escalations_escalated_to_membership_id'), ['escalated_to_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_escalations_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_escalations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_escalations_task_id'), ['task_id'], unique=False)

    op.create_table('workflow_notifications',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_membership_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'CONSOLE', name='notificationchannel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('subject', sa.String(length=350), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_workflow_notifications_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflow_notifications_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_membership_id'], ['organization_memberships.id'], name=op.f('fk_workflow_notifications_recipient_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_tasks.id'], name=op.f('fk_workflow_notifications_task_id_workflow_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_notifications')),
    sa.UniqueConstraint('organization_id', 'dedupe_key', name='uq_workflow_notification_org_dedupe')
    )
    with op.batch_alter_table('workflow_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_notifications_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_notifications_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_notifications_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_notifications_recipient_membership_id'), ['recipient_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_notifications_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_notifications_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_notifications_task_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_notifications_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_notifications_recipient_membership_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_notifications_matter_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_notifications_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_workflow_notifications_channel'))

    op.drop_table('workflow_notifications')
    with op.batch_alter_table('workflow_escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_escalations_task_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_escalations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_escalations_level'))
        batch_op.drop_index(batch_op.f('ix_workflow_escalations_escalated_to_membership_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_escalations_escalated_at'))

    op.drop_table('workflow_escalations')
    with op.batch_alter_table('workflow_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_matter_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_escalation_level'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_due_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_tasks_assigned_membership_id'))

    op.drop_table('workflow_tasks')
    with op.batch_alter_table('court_case_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_case_changes_workflow_event_id'))
        batch_op.drop_index(batch_op.f('ix_court_case_changes_tracker_id'))
        batch_op.drop_index(batch_op.f('ix_court_case_changes_severity'))
        batch_op.drop_index(batch_op.f('ix_court_case_changes_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_court_case_changes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_court_case_changes_matter_id'))
        batch_op.drop_index(batch_op.f('ix_court_case_changes_detected_at'))
        batch_op.drop_index(batch_op.f('ix_court_case_changes_current_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_court_case_changes_change_type'))

    op.drop_table('court_case_changes')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_trigger_event_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_template_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_matter_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('court_case_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_case_snapshots_tracker_id'))
        batch_op.drop_index(batch_op.f('ix_court_case_snapshots_stage'))
        batch_op.drop_index(batch_op.f('ix_court_case_snapshots_next_hearing_date'))
        batch_op.drop_index(batch_op.f('ix_court_case_snapshots_latest_order_date'))
        batch_op.drop_index(batch_op.f('ix_court_case_snapshots_content_hash'))
        batch_op.drop_index(batch_op.f('ix_court_case_snapshots_case_status'))
        batch_op.drop_index(batch_op.f('ix_court_case_snapshots_captured_at'))

    op.drop_table('court_case_snapshots')
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_events_source_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_source_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_matter_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_dedupe_key'))

    op.drop_table('workflow_events')
    with op.batch_alter_table('operations_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_preferences_organization_id'))
        batch_op.drop_index(batch_op.f('ix_operations_preferences_membership_id'))

    op.drop_table('operations_preferences')
    with op.batch_alter_table('court_case_trackers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_status'))
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_source_kind'))
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_next_check_at'))
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_matter_id'))
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_last_checked_at'))
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_court_name'))
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_cnr_number'))
        batch_op.drop_index(batch_op.f('ix_court_case_trackers_case_number'))

    op.drop_table('court_case_trackers')
    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_templates_version'))
        batch_op.drop_index(batch_op.f('ix_workflow_templates_trigger_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_templates_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_templates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_templates_code'))

    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
