"""observability backup disaster recovery system health

Revision ID: 20260808_0020
Revises: 20260808_0019
Create Date: 2026-08-08 12:01:55.086502
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0020'
down_revision: Union[str, None] = '20260808_0019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_policies',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('include_database', sa.Boolean(), nullable=False),
    sa.Column('include_documents', sa.Boolean(), nullable=False),
    sa.Column('schedule_rrule', sa.String(length=500), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('max_backups', sa.Integer(), nullable=False),
    sa.Column('destination_kind', sa.String(length=40), nullable=False),
    sa.Column('destination_path', sa.String(length=1200), nullable=True),
    sa.Column('encryption_mode', sa.String(length=60), nullable=False),
    sa.Column('rpo_minutes', sa.Integer(), nullable=False),
    sa.Column('rto_minutes', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_backup_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_policies'))
    )
    with op.batch_alter_table('backup_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_policies_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_policies_last_run_at'), ['last_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_policies_organization_id'), ['organization_id'], unique=False)

    op.create_table('system_metric_snapshots',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('database_latency_ms', sa.Integer(), nullable=True),
    sa.Column('storage_free_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_total_bytes', sa.Integer(), nullable=True),
    sa.Column('queue_oldest_age_seconds', sa.Integer(), nullable=False),
    sa.Column('dead_letter_count', sa.Integer(), nullable=False),
    sa.Column('slow_job_count', sa.Integer(), nullable=False),
    sa.Column('online_worker_count', sa.Integer(), nullable=False),
    sa.Column('stale_worker_count', sa.Integer(), nullable=False),
    sa.Column('search_index_age_seconds', sa.Integer(), nullable=True),
    sa.Column('tesseract_available', sa.Boolean(), nullable=False),
    sa.Column('local_ai_configured', sa.Boolean(), nullable=False),
    sa.Column('remote_ai_configured', sa.Boolean(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_system_metric_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_metric_snapshots'))
    )
    with op.batch_alter_table('system_metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_metric_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_metric_snapshots_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_metric_snapshots_overall_status'), ['overall_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_metric_snapshots_snapshot_hash'), ['snapshot_hash'], unique=False)

    op.create_table('backup_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('database_status', sa.String(length=60), nullable=True),
    sa.Column('documents_status', sa.String(length=60), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_backup_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['backup_policies.id'], name=op.f('fk_backup_runs_policy_id_backup_policies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_backup_runs_requested_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_runs'))
    )
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_runs_manifest_sha256'), ['manifest_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_trigger'), ['trigger'], unique=False)

    op.create_table('recovery_objectives',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('target_rpo_minutes', sa.Integer(), nullable=False),
    sa.Column('target_rto_minutes', sa.Integer(), nullable=False),
    sa.Column('restore_verification_days', sa.Integer(), nullable=False),
    sa.Column('max_queue_lag_seconds', sa.Integer(), nullable=False),
    sa.Column('worker_stale_seconds', sa.Integer(), nullable=False),
    sa.Column('slow_job_seconds', sa.Integer(), nullable=False),
    sa.Column('min_storage_free_percent', sa.Integer(), nullable=False),
    sa.Column('max_database_latency_ms', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_recovery_objectives_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_recovery_objectives_updated_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_objectives')),
    sa.UniqueConstraint('organization_id', name='uq_recovery_objective_org')
    )
    with op.batch_alter_table('recovery_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_objectives_organization_id'), ['organization_id'], unique=False)

    op.create_table('system_health_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_system_health_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_system_health_runs_requested_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_health_runs'))
    )
    with op.batch_alter_table('system_health_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_health_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_runs_requested_by_membership_id'), ['requested_by_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_runs_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_runs_trigger'), ['trigger'], unique=False)

    op.create_table('system_incidents',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('component_key', sa.String(length=120), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_system_incidents_acknowledged_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_system_incidents_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_system_incidents_resolved_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_incidents')),
    sa.UniqueConstraint('organization_id', 'fingerprint', name='uq_system_incident_org_fingerprint')
    )
    with op.batch_alter_table('system_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_incidents_component_key'), ['component_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incidents_status'), ['status'], unique=False)

    op.create_table('backup_artifacts',
    sa.Column('backup_run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('storage_path', sa.String(length=1400), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backup_run_id'], ['backup_runs.id'], name=op.f('fk_backup_artifacts_backup_run_id_backup_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_artifacts'))
    )
    with op.batch_alter_table('backup_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_artifacts_backup_run_id'), ['backup_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_artifacts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('restore_drills',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('backup_run_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('database_verified', sa.Boolean(), nullable=False),
    sa.Column('documents_verified', sa.Boolean(), nullable=False),
    sa.Column('artifact_hashes_verified', sa.Boolean(), nullable=False),
    sa.Column('document_count_verified', sa.Integer(), nullable=False),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backup_run_id'], ['backup_runs.id'], name=op.f('fk_restore_drills_backup_run_id_backup_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_restore_drills_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_restore_drills_requested_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_restore_drills_reviewed_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restore_drills'))
    )
    with op.batch_alter_table('restore_drills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restore_drills_backup_run_id'), ['backup_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restore_drills_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restore_drills_result_hash'), ['result_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_restore_drills_status'), ['status'], unique=False)

    op.create_table('system_health_components',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('component_key', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('message_en', sa.String(length=900), nullable=False),
    sa.Column('message_hi', sa.String(length=900), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['system_health_runs.id'], name=op.f('fk_system_health_components_run_id_system_health_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_health_components')),
    sa.UniqueConstraint('run_id', 'component_key', name='uq_system_health_component_run_key')
    )
    with op.batch_alter_table('system_health_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_health_components_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_components_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_components_component_key'), ['component_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_components_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_health_components_status'), ['status'], unique=False)

    op.create_table('system_incident_events',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=1200), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['system_incidents.id'], name=op.f('fk_system_incident_events_incident_id_system_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_system_incident_events_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_incident_events'))
    )
    with op.batch_alter_table('system_incident_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_incident_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_incident_events_incident_id'), ['incident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_incident_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_incident_events_incident_id'))
        batch_op.drop_index(batch_op.f('ix_system_incident_events_event_type'))

    op.drop_table('system_incident_events')
    with op.batch_alter_table('system_health_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_health_components_status'))
        batch_op.drop_index(batch_op.f('ix_system_health_components_run_id'))
        batch_op.drop_index(batch_op.f('ix_system_health_components_component_key'))
        batch_op.drop_index(batch_op.f('ix_system_health_components_checked_at'))
        batch_op.drop_index(batch_op.f('ix_system_health_components_category'))

    op.drop_table('system_health_components')
    with op.batch_alter_table('restore_drills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restore_drills_status'))
        batch_op.drop_index(batch_op.f('ix_restore_drills_result_hash'))
        batch_op.drop_index(batch_op.f('ix_restore_drills_organization_id'))
        batch_op.drop_index(batch_op.f('ix_restore_drills_backup_run_id'))

    op.drop_table('restore_drills')
    with op.batch_alter_table('backup_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_artifacts_sha256'))
        batch_op.drop_index(batch_op.f('ix_backup_artifacts_kind'))
        batch_op.drop_index(batch_op.f('ix_backup_artifacts_backup_run_id'))

    op.drop_table('backup_artifacts')
    with op.batch_alter_table('system_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_first_seen_at'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_system_incidents_component_key'))

    op.drop_table('system_incidents')
    with op.batch_alter_table('system_health_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_health_runs_trigger'))
        batch_op.drop_index(batch_op.f('ix_system_health_runs_status'))
        batch_op.drop_index(batch_op.f('ix_system_health_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_system_health_runs_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_system_health_runs_requested_by_membership_id'))
        batch_op.drop_index(batch_op.f('ix_system_health_runs_organization_id'))

    op.drop_table('system_health_runs')
    with op.batch_alter_table('recovery_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_objectives_organization_id'))

    op.drop_table('recovery_objectives')
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_runs_trigger'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_status'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_policy_id'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_manifest_sha256'))

    op.drop_table('backup_runs')
    with op.batch_alter_table('system_metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_metric_snapshots_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_system_metric_snapshots_overall_status'))
        batch_op.drop_index(batch_op.f('ix_system_metric_snapshots_organization_id'))
        batch_op.drop_index(batch_op.f('ix_system_metric_snapshots_captured_at'))

    op.drop_table('system_metric_snapshots')
    with op.batch_alter_table('backup_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_policies_organization_id'))
        batch_op.drop_index(batch_op.f('ix_backup_policies_last_run_at'))
        batch_op.drop_index(batch_op.f('ix_backup_policies_enabled'))

    op.drop_table('backup_policies')
    # ### end Alembic commands ###
