"""background jobs large scale processing

Revision ID: 20260808_0019
Revises: 20260808_0018
Create Date: 2026-08-08 10:34:12.419746
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0019'
down_revision: Union[str, None] = '20260808_0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_queues',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('max_per_minute', sa.Integer(), nullable=False),
    sa.Column('default_max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_seconds', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_background_queues_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_queues')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_background_queue_org_name')
    )
    with op.batch_alter_table('background_queues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_queues_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_queues_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_queues_organization_id'), ['organization_id'], unique=False)

    op.create_table('background_workers',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('worker_key', sa.String(length=220), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('queues_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_job_id', sa.Uuid(), nullable=True),
    sa.Column('jobs_succeeded', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_background_workers_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_workers')),
    sa.UniqueConstraint('organization_id', 'worker_key', name='uq_background_worker_org_key')
    )
    with op.batch_alter_table('background_workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_workers_current_job_id'), ['current_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_workers_heartbeat_at'), ['heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_workers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_workers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_workers_worker_key'), ['worker_key'], unique=False)

    op.create_table('background_jobs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('queue_name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('priority_value', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=240), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('backoff_base_seconds', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_id', sa.Uuid(), nullable=True),
    sa.Column('leased_by_worker_id', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('handler_version', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['leased_by_worker_id'], ['background_workers.id'], name=op.f('fk_background_jobs_leased_by_worker_id_background_workers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_background_jobs_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_background_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_background_jobs_requested_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_jobs')),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_background_job_org_idempotency')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_cancellation_requested_at'), ['cancellation_requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_lease_id'), ['lease_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_leased_by_worker_id'), ['leased_by_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_priority_value'), ['priority_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_queue_name'), ['queue_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_requested_by_membership_id'), ['requested_by_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)

    op.create_table('background_job_artifacts',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('storage_key', sa.String(length=1200), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], name=op.f('fk_background_job_artifacts_job_id_background_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_job_artifacts'))
    )
    with op.batch_alter_table('background_job_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_job_artifacts_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_artifacts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('background_job_attempts',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('leased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], name=op.f('fk_background_job_attempts_job_id_background_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['background_workers.id'], name=op.f('fk_background_job_attempts_worker_id_background_workers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_job_attempts')),
    sa.UniqueConstraint('job_id', 'attempt_number', name='uq_background_job_attempt_number')
    )
    with op.batch_alter_table('background_job_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_job_attempts_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_attempts_worker_id'), ['worker_id'], unique=False)

    op.create_table('background_job_dependencies',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_job_id', sa.Uuid(), nullable=False),
    sa.Column('required_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_job_id'], ['background_jobs.id'], name=op.f('fk_background_job_dependencies_depends_on_job_id_background_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], name=op.f('fk_background_job_dependencies_job_id_background_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_job_dependencies')),
    sa.UniqueConstraint('job_id', 'depends_on_job_id', name='uq_background_job_dependency')
    )
    with op.batch_alter_table('background_job_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_job_dependencies_depends_on_job_id'), ['depends_on_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_dependencies_job_id'), ['job_id'], unique=False)

    op.create_table('background_job_events',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], name=op.f('fk_background_job_events_job_id_background_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_job_events'))
    )
    with op.batch_alter_table('background_job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_job_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_events_level'), ['level'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_job_events_level'))
        batch_op.drop_index(batch_op.f('ix_background_job_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_background_job_events_event_type'))

    op.drop_table('background_job_events')
    with op.batch_alter_table('background_job_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_job_dependencies_job_id'))
        batch_op.drop_index(batch_op.f('ix_background_job_dependencies_depends_on_job_id'))

    op.drop_table('background_job_dependencies')
    with op.batch_alter_table('background_job_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_job_attempts_worker_id'))
        batch_op.drop_index(batch_op.f('ix_background_job_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_background_job_attempts_job_id'))

    op.drop_table('background_job_attempts')
    with op.batch_alter_table('background_job_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_job_artifacts_sha256'))
        batch_op.drop_index(batch_op.f('ix_background_job_artifacts_kind'))
        batch_op.drop_index(batch_op.f('ix_background_job_artifacts_job_id'))

    op.drop_table('background_job_artifacts')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_requested_by_membership_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_queue_name'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_priority_value'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_priority'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_matter_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_leased_by_worker_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_lease_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_cancellation_requested_at'))

    op.drop_table('background_jobs')
    with op.batch_alter_table('background_workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_workers_worker_key'))
        batch_op.drop_index(batch_op.f('ix_background_workers_status'))
        batch_op.drop_index(batch_op.f('ix_background_workers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_background_workers_heartbeat_at'))
        batch_op.drop_index(batch_op.f('ix_background_workers_current_job_id'))

    op.drop_table('background_workers')
    with op.batch_alter_table('background_queues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_queues_organization_id'))
        batch_op.drop_index(batch_op.f('ix_background_queues_name'))
        batch_op.drop_index(batch_op.f('ix_background_queues_enabled'))

    op.drop_table('background_queues')
    # ### end Alembic commands ###
