"""billing accounting client portal

Revision ID: 20260808_0011
Revises: 20260808_0010
Create Date: 2026-08-08 06:09:07.352840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0011'
down_revision: Union[str, None] = '20260808_0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_rate_cards',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_billing_rate_cards_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_rate_cards'))
    )
    with op.batch_alter_table('billing_rate_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_rate_cards_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_rate_cards_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_rate_cards_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_rate_cards_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_billing_profiles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('gstin', sa.String(length=32), nullable=True),
    sa.Column('pan_last4', sa.String(length=4), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('default_currency', sa.String(length=8), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=40), nullable=False),
    sa.Column('next_invoice_sequence', sa.Integer(), nullable=False),
    sa.Column('default_payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('bank_details_json', sa.JSON(), nullable=False),
    sa.Column('tax_configuration_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_billing_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_billing_profiles')),
    sa.UniqueConstraint('organization_id', name='uq_org_billing_profile_org')
    )
    with op.batch_alter_table('organization_billing_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_billing_profiles_gstin'), ['gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_billing_profiles_organization_id'), ['organization_id'], unique=False)

    op.create_table('billing_rates',
    sa.Column('rate_card_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('role_label', sa.String(length=120), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_billing_rates_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_card_id'], ['billing_rate_cards.id'], name=op.f('fk_billing_rates_rate_card_id_billing_rate_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_rates'))
    )
    with op.batch_alter_table('billing_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_rates_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_rates_rate_card_id'), ['rate_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_rates_role_label'), ['role_label'], unique=False)

    op.create_table('billing_expenses',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('incurred_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'BILLED', 'REJECTED', name='expensestatus', native_enum=False), nullable=False),
    sa.Column('receipt_document_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_billing_expenses_client_id_clients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incurred_by_user_id'], ['security_users.id'], name=op.f('fk_billing_expenses_incurred_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_billing_expenses_matter_id_matters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_billing_expenses_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_document_id'], ['documents.id'], name=op.f('fk_billing_expenses_receipt_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_expenses'))
    )
    with op.batch_alter_table('billing_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_expenses_billable'), ['billable'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_expenses_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_expenses_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_expenses_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_expenses_status'), ['status'], unique=False)

    op.create_table('fee_arrangements',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('rate_card_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('fee_model', sa.Enum('HOURLY', 'FIXED', 'RETAINER', 'CAPPED', 'CONTINGENCY', 'CUSTOM', name='feemodel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='feearrangementstatus', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('default_hourly_rate', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('fixed_fee', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('retainer_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('fee_cap', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('contingency_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('billing_frequency', sa.String(length=60), nullable=True),
    sa.Column('tax_treatment_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_fee_arrangements_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_fee_arrangements_engagement_id_engagements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_fee_arrangements_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_fee_arrangements_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_card_id'], ['billing_rate_cards.id'], name=op.f('fk_fee_arrangements_rate_card_id_billing_rate_cards'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_arrangements'))
    )
    with op.batch_alter_table('fee_arrangements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_arrangements_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_arrangements_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_arrangements_fee_model'), ['fee_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_arrangements_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_arrangements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_arrangements_rate_card_id'), ['rate_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_arrangements_status'), ['status'], unique=False)

    op.create_table('client_portal_messages',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('portal_access_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('sender_type', sa.Enum('FIRM', 'CLIENT', name='portalsendertype', native_enum=False), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_portal_messages_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_client_portal_messages_matter_id_matters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_client_portal_messages_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_access_id'], ['client_portal_access.id'], name=op.f('fk_client_portal_messages_portal_access_id_client_portal_access'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['security_users.id'], name=op.f('fk_client_portal_messages_sender_user_id_security_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_portal_messages'))
    )
    with op.batch_alter_table('client_portal_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_portal_messages_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_messages_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_messages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_messages_portal_access_id'), ['portal_access_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_messages_sender_type'), ['sender_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_messages_sent_at'), ['sent_at'], unique=False)

    op.create_table('client_portal_requests',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('portal_access_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('request_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='portalrequeststatus', native_enum=False), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_portal_requests_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['security_users.id'], name=op.f('fk_client_portal_requests_created_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_client_portal_requests_matter_id_matters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_client_portal_requests_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_access_id'], ['client_portal_access.id'], name=op.f('fk_client_portal_requests_portal_access_id_client_portal_access'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_portal_requests'))
    )
    with op.batch_alter_table('client_portal_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_portal_requests_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_requests_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_requests_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_requests_portal_access_id'), ['portal_access_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_requests_status'), ['status'], unique=False)

    op.create_table('client_portal_shares',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('portal_access_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('share_type', sa.Enum('DOCUMENT', 'INVOICE', 'MATTER_UPDATE', name='portalsharetype', native_enum=False), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('shared_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_portal_shares_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_client_portal_shares_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_client_portal_shares_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_access_id'], ['client_portal_access.id'], name=op.f('fk_client_portal_shares_portal_access_id_client_portal_access'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['security_users.id'], name=op.f('fk_client_portal_shares_shared_by_user_id_security_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_portal_shares'))
    )
    with op.batch_alter_table('client_portal_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_portal_shares_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_shares_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_shares_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_shares_portal_access_id'), ['portal_access_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_shares_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_shares_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_shares_share_type'), ['share_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_shares_shared_at'), ['shared_at'], unique=False)

    op.create_table('client_portal_users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('portal_access_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='portaluserstatus', native_enum=False), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_portal_users_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_client_portal_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portal_access_id'], ['client_portal_access.id'], name=op.f('fk_client_portal_users_portal_access_id_client_portal_access'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_portal_users')),
    sa.UniqueConstraint('organization_id', 'email', name='uq_portal_user_org_email'),
    sa.UniqueConstraint('portal_access_id', name='uq_portal_user_access')
    )
    with op.batch_alter_table('client_portal_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_portal_users_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_users_portal_access_id'), ['portal_access_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_users_status'), ['status'], unique=False)

    op.create_table('invoices',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('fee_arrangement_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'VOID', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('supplier_name', sa.String(length=300), nullable=True),
    sa.Column('supplier_address', sa.Text(), nullable=True),
    sa.Column('supplier_gstin', sa.String(length=32), nullable=True),
    sa.Column('supplier_state_code', sa.String(length=10), nullable=True),
    sa.Column('supplier_email', sa.String(length=320), nullable=True),
    sa.Column('client_name', sa.String(length=300), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('client_gstin', sa.String(length=32), nullable=True),
    sa.Column('client_state_code', sa.String(length=10), nullable=True),
    sa.Column('place_of_supply', sa.String(length=160), nullable=True),
    sa.Column('reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cgst_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('sgst_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('igst_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cess_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_treatment_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('irn', sa.String(length=128), nullable=True),
    sa.Column('acknowledgement_number', sa.String(length=128), nullable=True),
    sa.Column('acknowledgement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_invoices_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fee_arrangement_id'], ['fee_arrangements.id'], name=op.f('fk_invoices_fee_arrangement_id_fee_arrangements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['security_users.id'], name=op.f('fk_invoices_issued_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_invoices_matter_id_matters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invoices_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['security_users.id'], name=op.f('fk_invoices_reviewed_by_user_id_security_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('organization_id', 'invoice_number', name='uq_invoice_org_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_irn'), ['irn'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tax_treatment_reviewed'), ['tax_treatment_reviewed'], unique=False)

    op.create_table('client_portal_sessions',
    sa.Column('portal_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portal_user_id'], ['client_portal_users.id'], name=op.f('fk_client_portal_sessions_portal_user_id_client_portal_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_portal_sessions'))
    )
    with op.batch_alter_table('client_portal_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_portal_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_sessions_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_sessions_portal_user_id'), ['portal_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_sessions_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('TIME', 'EXPENSE', 'FEE', 'ADJUSTMENT', name='invoicelinekind', native_enum=False), nullable=False),
    sa.Column('source_time_entry_id', sa.Uuid(), nullable=True),
    sa.Column('source_expense_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('service_code', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_expense_id'], ['billing_expenses.id'], name=op.f('fk_invoice_lines_source_expense_id_billing_expenses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_time_entry_id'], ['time_entries.id'], name=op.f('fk_invoice_lines_source_time_entry_id_time_entries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_lines_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_lines_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_lines_service_code'), ['service_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_lines_source_expense_id'), ['source_expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_lines_source_time_entry_id'), ['source_time_entry_id'], unique=False)

    op.create_table('invoice_versions',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['security_users.id'], name=op.f('fk_invoice_versions_created_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_versions_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_versions')),
    sa.UniqueConstraint('invoice_id', 'version_number', name='uq_invoice_version_number')
    )
    with op.batch_alter_table('invoice_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_versions_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('payments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'UPI', 'CHEQUE', 'CASH', 'CARD', 'OTHER', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLEARED', 'FAILED', 'REVERSED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_payments_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['security_users.id'], name=op.f('fk_payments_recorded_by_user_id_security_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('client_ledger_entries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.Enum('INVOICE', 'PAYMENT', 'CREDIT', 'ADJUSTMENT', name='ledgerentrytype', native_enum=False), nullable=False),
    sa.Column('debit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_ledger_entries_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_client_ledger_entries_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_client_ledger_entries_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_client_ledger_entries_payment_id_payments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_ledger_entries'))
    )
    with op.batch_alter_table('client_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_ledger_entries_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_ledger_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_ledger_entries_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_ledger_entries_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_ledger_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_ledger_entries_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('client_portal_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_client_portal_access_invite_expires_at'), ['invite_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_portal_access_invite_token_hash'), ['invite_token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_portal_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_portal_access_invite_token_hash'))
        batch_op.drop_index(batch_op.f('ix_client_portal_access_invite_expires_at'))
        batch_op.drop_column('invite_expires_at')
        batch_op.drop_column('invite_token_hash')

    with op.batch_alter_table('client_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_ledger_entries_payment_id'))
        batch_op.drop_index(batch_op.f('ix_client_ledger_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_ledger_entries_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_client_ledger_entries_entry_type'))
        batch_op.drop_index(batch_op.f('ix_client_ledger_entries_entry_date'))
        batch_op.drop_index(batch_op.f('ix_client_ledger_entries_client_id'))

    op.drop_table('client_ledger_entries')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payments_method'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_client_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_versions_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_versions_content_hash'))

    op.drop_table('invoice_versions')
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_lines_source_time_entry_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_lines_source_expense_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_lines_service_code'))
        batch_op.drop_index(batch_op.f('ix_invoice_lines_kind'))
        batch_op.drop_index(batch_op.f('ix_invoice_lines_invoice_id'))

    op.drop_table('invoice_lines')
    with op.batch_alter_table('client_portal_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_portal_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_client_portal_sessions_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_client_portal_sessions_portal_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_sessions_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_client_portal_sessions_expires_at'))

    op.drop_table('client_portal_sessions')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_tax_treatment_reviewed'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_matter_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_issue_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_irn'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_content_hash'))
        batch_op.drop_index(batch_op.f('ix_invoices_client_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('client_portal_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_portal_users_status'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_portal_access_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_email'))
        batch_op.drop_index(batch_op.f('ix_client_portal_users_client_id'))

    op.drop_table('client_portal_users')
    with op.batch_alter_table('client_portal_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_portal_shares_shared_at'))
        batch_op.drop_index(batch_op.f('ix_client_portal_shares_share_type'))
        batch_op.drop_index(batch_op.f('ix_client_portal_shares_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_client_portal_shares_resource_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_shares_portal_access_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_shares_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_shares_matter_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_shares_client_id'))

    op.drop_table('client_portal_shares')
    with op.batch_alter_table('client_portal_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_portal_requests_status'))
        batch_op.drop_index(batch_op.f('ix_client_portal_requests_request_type'))
        batch_op.drop_index(batch_op.f('ix_client_portal_requests_portal_access_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_requests_matter_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_requests_due_at'))
        batch_op.drop_index(batch_op.f('ix_client_portal_requests_client_id'))

    op.drop_table('client_portal_requests')
    with op.batch_alter_table('client_portal_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_portal_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_client_portal_messages_sender_type'))
        batch_op.drop_index(batch_op.f('ix_client_portal_messages_portal_access_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_messages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_messages_matter_id'))
        batch_op.drop_index(batch_op.f('ix_client_portal_messages_client_id'))

    op.drop_table('client_portal_messages')
    with op.batch_alter_table('fee_arrangements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_arrangements_status'))
        batch_op.drop_index(batch_op.f('ix_fee_arrangements_rate_card_id'))
        batch_op.drop_index(batch_op.f('ix_fee_arrangements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_fee_arrangements_matter_id'))
        batch_op.drop_index(batch_op.f('ix_fee_arrangements_fee_model'))
        batch_op.drop_index(batch_op.f('ix_fee_arrangements_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_fee_arrangements_client_id'))

    op.drop_table('fee_arrangements')
    with op.batch_alter_table('billing_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_expenses_status'))
        batch_op.drop_index(batch_op.f('ix_billing_expenses_organization_id'))
        batch_op.drop_index(batch_op.f('ix_billing_expenses_matter_id'))
        batch_op.drop_index(batch_op.f('ix_billing_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_billing_expenses_client_id'))
        batch_op.drop_index(batch_op.f('ix_billing_expenses_category'))
        batch_op.drop_index(batch_op.f('ix_billing_expenses_billable'))

    op.drop_table('billing_expenses')
    with op.batch_alter_table('billing_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_rates_role_label'))
        batch_op.drop_index(batch_op.f('ix_billing_rates_rate_card_id'))
        batch_op.drop_index(batch_op.f('ix_billing_rates_membership_id'))

    op.drop_table('billing_rates')
    with op.batch_alter_table('organization_billing_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_billing_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_billing_profiles_gstin'))

    op.drop_table('organization_billing_profiles')
    with op.batch_alter_table('billing_rate_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_rate_cards_organization_id'))
        batch_op.drop_index(batch_op.f('ix_billing_rate_cards_name'))
        batch_op.drop_index(batch_op.f('ix_billing_rate_cards_is_default'))
        batch_op.drop_index(batch_op.f('ix_billing_rate_cards_is_active'))

    op.drop_table('billing_rate_cards')
    # ### end Alembic commands ###
