"""real integrations provider webhooks

Revision ID: 20260808_0024
Revises: 20260808_0023
Create Date: 2026-08-08 13:29:31.340540
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0024'
down_revision: Union[str, None] = '20260808_0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_connections',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connection_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=220), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1200), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_integration_connections_created_by_membership_id_organization_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integration_connections_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_connections')),
    sa.UniqueConstraint('organization_id', 'connection_key', name='uq_integration_connection_org_key')
    )
    with op.batch_alter_table('integration_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_connections_connection_key'), ['connection_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_connections_created_by_membership_id'), ['created_by_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_connections_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_connections_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_connections_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_connections_status'), ['status'], unique=False)

    op.create_table('integration_accounts',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('external_subject', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=250), nullable=True),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('sync_cursor', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_accounts_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_accounts')),
    sa.UniqueConstraint('connection_id', 'external_subject', name='uq_integration_account_subject')
    )
    with op.batch_alter_table('integration_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_accounts_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_accounts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_accounts_external_subject'), ['external_subject'], unique=False)

    op.create_table('integration_delivery_attempts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=240), nullable=True),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('external_resource_id', sa.String(length=700), nullable=True),
    sa.Column('external_url', sa.String(length=1400), nullable=True),
    sa.Column('response_metadata_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.String(length=1600), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_delivery_attempts_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integration_delivery_attempts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_delivery_attempts'))
    )
    with op.batch_alter_table('integration_delivery_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_delivery_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_delivery_attempts_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_delivery_attempts_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_delivery_attempts_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_delivery_attempts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_delivery_attempts_request_sha256'), ['request_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_delivery_attempts_status'), ['status'], unique=False)

    op.create_table('integration_health_checks',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('live_probe', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('checks_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.String(length=1200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_health_checks_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_health_checks'))
    )
    with op.batch_alter_table('integration_health_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_health_checks_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_health_checks_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_health_checks_status'), ['status'], unique=False)

    op.create_table('integration_oauth_states',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.String(length=1000), nullable=False),
    sa.Column('requested_scopes_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_oauth_states_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_oauth_states'))
    )
    with op.batch_alter_table('integration_oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_oauth_states_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_oauth_states_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_oauth_states_state_hash'), ['state_hash'], unique=True)

    op.create_table('integration_resource_mappings',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('internal_resource_type', sa.String(length=100), nullable=False),
    sa.Column('internal_resource_id', sa.String(length=120), nullable=False),
    sa.Column('external_resource_type', sa.String(length=100), nullable=False),
    sa.Column('external_resource_id', sa.String(length=700), nullable=False),
    sa.Column('external_url', sa.String(length=1400), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_resource_mappings_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_resource_mappings')),
    sa.UniqueConstraint('connection_id', 'internal_resource_type', 'internal_resource_id', 'external_resource_type', name='uq_integration_mapping_internal_external_type')
    )
    with op.batch_alter_table('integration_resource_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_resource_mappings_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_resource_mappings_external_resource_id'), ['external_resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_resource_mappings_external_resource_type'), ['external_resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_resource_mappings_internal_resource_id'), ['internal_resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_resource_mappings_internal_resource_type'), ['internal_resource_type'], unique=False)

    op.create_table('integration_secret_references',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('secret_key', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=1000), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_secret_references_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_secret_references')),
    sa.UniqueConstraint('connection_id', 'secret_key', name='uq_integration_secret_connection_key')
    )
    with op.batch_alter_table('integration_secret_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_secret_references_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_secret_references_secret_key'), ['secret_key'], unique=False)

    op.create_table('integration_sync_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('cursor_before', sa.Text(), nullable=True),
    sa.Column('cursor_after', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=1600), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_sync_runs_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integration_sync_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_sync_runs'))
    )
    with op.batch_alter_table('integration_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_sync_runs_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_sync_runs_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_sync_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_sync_runs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_sync_runs_status'), ['status'], unique=False)

    op.create_table('integration_webhook_endpoints',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_key', sa.String(length=160), nullable=False),
    sa.Column('signing_secret_reference', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('event_types_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_webhook_endpoints_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integration_webhook_endpoints_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_webhook_endpoints')),
    sa.UniqueConstraint('endpoint_key', name='uq_integration_webhook_endpoint_key')
    )
    with op.batch_alter_table('integration_webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_webhook_endpoints_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_webhook_endpoints_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_webhook_endpoints_endpoint_key'), ['endpoint_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_webhook_endpoints_organization_id'), ['organization_id'], unique=False)

    op.create_table('integration_webhook_events',
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('external_event_id', sa.String(length=500), nullable=False),
    sa.Column('event_type', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('body_sha256', sa.String(length=64), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('normalized_payload_json', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=1200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['integration_webhook_endpoints.id'], name=op.f('fk_integration_webhook_events_endpoint_id_integration_webhook_endpoints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_webhook_events')),
    sa.UniqueConstraint('endpoint_id', 'external_event_id', name='uq_integration_webhook_event_external')
    )
    with op.batch_alter_table('integration_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_webhook_events_body_sha256'), ['body_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_webhook_events_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_webhook_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_webhook_events_external_event_id'), ['external_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_webhook_events_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_webhook_events_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_webhook_events_status'))
        batch_op.drop_index(batch_op.f('ix_integration_webhook_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_integration_webhook_events_external_event_id'))
        batch_op.drop_index(batch_op.f('ix_integration_webhook_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_integration_webhook_events_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_integration_webhook_events_body_sha256'))

    op.drop_table('integration_webhook_events')
    with op.batch_alter_table('integration_webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_webhook_endpoints_organization_id'))
        batch_op.drop_index(batch_op.f('ix_integration_webhook_endpoints_endpoint_key'))
        batch_op.drop_index(batch_op.f('ix_integration_webhook_endpoints_enabled'))
        batch_op.drop_index(batch_op.f('ix_integration_webhook_endpoints_connection_id'))

    op.drop_table('integration_webhook_endpoints')
    with op.batch_alter_table('integration_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_sync_runs_status'))
        batch_op.drop_index(batch_op.f('ix_integration_sync_runs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_integration_sync_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_integration_sync_runs_direction'))
        batch_op.drop_index(batch_op.f('ix_integration_sync_runs_connection_id'))

    op.drop_table('integration_sync_runs')
    with op.batch_alter_table('integration_secret_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_secret_references_secret_key'))
        batch_op.drop_index(batch_op.f('ix_integration_secret_references_connection_id'))

    op.drop_table('integration_secret_references')
    with op.batch_alter_table('integration_resource_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_resource_mappings_internal_resource_type'))
        batch_op.drop_index(batch_op.f('ix_integration_resource_mappings_internal_resource_id'))
        batch_op.drop_index(batch_op.f('ix_integration_resource_mappings_external_resource_type'))
        batch_op.drop_index(batch_op.f('ix_integration_resource_mappings_external_resource_id'))
        batch_op.drop_index(batch_op.f('ix_integration_resource_mappings_connection_id'))

    op.drop_table('integration_resource_mappings')
    with op.batch_alter_table('integration_oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_oauth_states_state_hash'))
        batch_op.drop_index(batch_op.f('ix_integration_oauth_states_expires_at'))
        batch_op.drop_index(batch_op.f('ix_integration_oauth_states_connection_id'))

    op.drop_table('integration_oauth_states')
    with op.batch_alter_table('integration_health_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_health_checks_status'))
        batch_op.drop_index(batch_op.f('ix_integration_health_checks_connection_id'))
        batch_op.drop_index(batch_op.f('ix_integration_health_checks_checked_at'))

    op.drop_table('integration_health_checks')
    with op.batch_alter_table('integration_delivery_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_delivery_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_integration_delivery_attempts_request_sha256'))
        batch_op.drop_index(batch_op.f('ix_integration_delivery_attempts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_integration_delivery_attempts_operation'))
        batch_op.drop_index(batch_op.f('ix_integration_delivery_attempts_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_integration_delivery_attempts_connection_id'))
        batch_op.drop_index(batch_op.f('ix_integration_delivery_attempts_attempted_at'))

    op.drop_table('integration_delivery_attempts')
    with op.batch_alter_table('integration_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_accounts_external_subject'))
        batch_op.drop_index(batch_op.f('ix_integration_accounts_email'))
        batch_op.drop_index(batch_op.f('ix_integration_accounts_connection_id'))

    op.drop_table('integration_accounts')
    with op.batch_alter_table('integration_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_connections_status'))
        batch_op.drop_index(batch_op.f('ix_integration_connections_provider'))
        batch_op.drop_index(batch_op.f('ix_integration_connections_organization_id'))
        batch_op.drop_index(batch_op.f('ix_integration_connections_enabled'))
        batch_op.drop_index(batch_op.f('ix_integration_connections_created_by_membership_id'))
        batch_op.drop_index(batch_op.f('ix_integration_connections_connection_key'))

    op.drop_table('integration_connections')
    # ### end Alembic commands ###
