"""case lookup legal remedy analysis

Revision ID: 20260808_0028
Revises: 20260808_0027
Create Date: 2026-08-08 15:59:23.847619
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0028'
down_revision: Union[str, None] = '20260808_0027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remedy_rule_packs',
    sa.Column('code', sa.String(length=180), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=False),
    sa.Column('name_hi', sa.String(length=300), nullable=True),
    sa.Column('jurisdiction', sa.String(length=120), nullable=False),
    sa.Column('proceeding_type', sa.String(length=180), nullable=True),
    sa.Column('court_level', sa.String(length=120), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='remedypackstatus', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_name', sa.String(length=350), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_citation', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remedy_rule_packs')),
    sa.UniqueConstraint('code', 'version', name='uq_remedy_pack_code_version')
    )
    with op.batch_alter_table('remedy_rule_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedy_rule_packs_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_packs_court_level'), ['court_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_packs_jurisdiction'), ['jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_packs_proceeding_type'), ['proceeding_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_packs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_packs_verified'), ['verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_packs_version'), ['version'], unique=False)

    op.create_table('remedy_rules',
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=180), nullable=False),
    sa.Column('remedy_name_en', sa.String(length=300), nullable=False),
    sa.Column('remedy_name_hi', sa.String(length=300), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_hi', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('case_stage_patterns_json', sa.JSON(), nullable=False),
    sa.Column('status_patterns_json', sa.JSON(), nullable=False),
    sa.Column('court_level_patterns_json', sa.JSON(), nullable=False),
    sa.Column('order_type_patterns_json', sa.JSON(), nullable=False),
    sa.Column('act_patterns_json', sa.JSON(), nullable=False),
    sa.Column('section_patterns_json', sa.JSON(), nullable=False),
    sa.Column('requires_final_order', sa.Boolean(), nullable=False),
    sa.Column('requires_latest_order', sa.Boolean(), nullable=False),
    sa.Column('forum_json', sa.JSON(), nullable=False),
    sa.Column('limitation_json', sa.JSON(), nullable=False),
    sa.Column('maintainability_json', sa.JSON(), nullable=False),
    sa.Column('required_documents_json', sa.JSON(), nullable=False),
    sa.Column('procedural_steps_json', sa.JSON(), nullable=False),
    sa.Column('risks_json', sa.JSON(), nullable=False),
    sa.Column('drafting_json', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['remedy_rule_packs.id'], name=op.f('fk_remedy_rules_pack_id_remedy_rule_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remedy_rules')),
    sa.UniqueConstraint('pack_id', 'code', name='uq_remedy_rule_pack_code')
    )
    with op.batch_alter_table('remedy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedy_rules_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rules_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rules_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rules_verified'), ['verified'], unique=False)

    op.create_table('case_lookup_preferences',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_state', sa.String(length=160), nullable=True),
    sa.Column('preferred_district', sa.String(length=160), nullable=True),
    sa.Column('preferred_high_court', sa.String(length=260), nullable=True),
    sa.Column('preferred_courts_json', sa.JSON(), nullable=False),
    sa.Column('recent_courts_json', sa.JSON(), nullable=False),
    sa.Column('default_refresh_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_case_lookup_preferences_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_case_lookup_preferences_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_lookup_preferences')),
    sa.UniqueConstraint('membership_id', name='uq_case_lookup_preference_membership')
    )
    with op.batch_alter_table('case_lookup_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_lookup_preferences_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_preferences_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_preferences_preferred_district'), ['preferred_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_preferences_preferred_high_court'), ['preferred_high_court'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_preferences_preferred_state'), ['preferred_state'], unique=False)

    op.create_table('case_lookup_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('raw_query', sa.String(length=300), nullable=False),
    sa.Column('detected_kind', sa.String(length=80), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=False),
    sa.Column('source_kinds_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'AMBIGUOUS', 'NOT_FOUND', 'USER_VERIFICATION_REQUIRED', 'FAILED', name='caselookupstatus', native_enum=False), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_case_lookup_runs_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_case_lookup_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_lookup_runs'))
    )
    with op.batch_alter_table('case_lookup_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_lookup_runs_detected_kind'), ['detected_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_runs_raw_query'), ['raw_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_runs_status'), ['status'], unique=False)

    op.create_table('saved_cases',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('current_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('cnr', sa.String(length=40), nullable=True),
    sa.Column('source_case_key', sa.String(length=300), nullable=False),
    sa.Column('case_type', sa.String(length=120), nullable=True),
    sa.Column('case_number', sa.String(length=160), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('case_title', sa.String(length=500), nullable=True),
    sa.Column('court_name', sa.String(length=350), nullable=False),
    sa.Column('court_code', sa.String(length=100), nullable=True),
    sa.Column('court_number', sa.String(length=120), nullable=True),
    sa.Column('court_level', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=160), nullable=True),
    sa.Column('state', sa.String(length=160), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('judge', sa.String(length=350), nullable=True),
    sa.Column('bench', sa.String(length=350), nullable=True),
    sa.Column('case_status', sa.String(length=180), nullable=True),
    sa.Column('case_stage', sa.String(length=240), nullable=True),
    sa.Column('previous_hearing_date', sa.Date(), nullable=True),
    sa.Column('next_hearing_date', sa.Date(), nullable=True),
    sa.Column('source_kind', sa.Enum('SAVED', 'DISTRICT_COURT', 'HIGH_COURT', 'SUPREME_COURT', 'OFFICIAL_IMPORT', 'USER_ASSISTED', name='casesourcekind', native_enum=False), nullable=False),
    sa.Column('source_name', sa.String(length=260), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=400), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_status', sa.Enum('ACTIVE', 'CLOSED', 'ARCHIVED', name='caserecordstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_saved_cases_created_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_saved_cases_matter_id_matters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_saved_cases_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_cases')),
    sa.UniqueConstraint('organization_id', 'cnr', name='uq_saved_case_org_cnr'),
    sa.UniqueConstraint('organization_id', 'source_case_key', name='uq_saved_case_org_source_key')
    )
    with op.batch_alter_table('saved_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_cases_case_number'), ['case_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_case_stage'), ['case_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_case_status'), ['case_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_case_title'), ['case_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_case_type'), ['case_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_cnr'), ['cnr'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_court_code'), ['court_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_court_level'), ['court_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_court_name'), ['court_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_current_snapshot_id'), ['current_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_next_hearing_date'), ['next_hearing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_previous_hearing_date'), ['previous_hearing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_record_status'), ['record_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_source_case_key'), ['source_case_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_source_kind'), ['source_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_stale_after'), ['stale_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_cases_year'), ['year'], unique=False)

    op.create_table('case_lookup_candidates',
    sa.Column('lookup_run_id', sa.Uuid(), nullable=False),
    sa.Column('saved_case_id', sa.Uuid(), nullable=True),
    sa.Column('source_kind', sa.Enum('SAVED', 'DISTRICT_COURT', 'HIGH_COURT', 'SUPREME_COURT', 'OFFICIAL_IMPORT', 'USER_ASSISTED', name='casesourcekind', native_enum=False), nullable=False),
    sa.Column('case_record_json', sa.JSON(), nullable=False),
    sa.Column('rank_score', sa.Integer(), nullable=False),
    sa.Column('exact_match', sa.Boolean(), nullable=False),
    sa.Column('requires_user_verification', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lookup_run_id'], ['case_lookup_runs.id'], name=op.f('fk_case_lookup_candidates_lookup_run_id_case_lookup_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_case_lookup_candidates_saved_case_id_saved_cases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_lookup_candidates'))
    )
    with op.batch_alter_table('case_lookup_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_lookup_candidates_exact_match'), ['exact_match'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_candidates_lookup_run_id'), ['lookup_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_candidates_rank_score'), ['rank_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_candidates_saved_case_id'), ['saved_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_lookup_candidates_source_kind'), ['source_kind'], unique=False)

    op.create_table('case_source_snapshots',
    sa.Column('saved_case_id', sa.Uuid(), nullable=False),
    sa.Column('source_kind', sa.Enum('SAVED', 'DISTRICT_COURT', 'HIGH_COURT', 'SUPREME_COURT', 'OFFICIAL_IMPORT', 'USER_ASSISTED', name='casesourcekind', native_enum=False), nullable=False),
    sa.Column('source_name', sa.String(length=260), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_case_source_snapshots_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_source_snapshots'))
    )
    with op.batch_alter_table('case_source_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_source_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_source_snapshots_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_source_snapshots_saved_case_id'), ['saved_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_source_snapshots_source_kind'), ['source_kind'], unique=False)

    op.create_table('remedy_analyses',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('saved_case_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW_REQUIRED', 'REVIEWED', 'SUPERSEDED', name='remedyanalysisstatus', native_enum=False), nullable=False),
    sa.Column('case_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_remedy_analyses_created_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_remedy_analyses_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_remedy_analyses_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_remedy_analyses_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remedy_analyses'))
    )
    with op.batch_alter_table('remedy_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedy_analyses_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_analyses_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_analyses_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_analyses_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_analyses_saved_case_id'), ['saved_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_analyses_status'), ['status'], unique=False)

    op.create_table('remedy_rule_authorities',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('authority_type', sa.Enum('STATUTE', 'RULE', 'JUDGMENT', 'CONSTITUTION', 'PROCEDURE', 'OTHER', name='remedyauthoritytype', native_enum=False), nullable=False),
    sa.Column('statute_section_id', sa.Uuid(), nullable=True),
    sa.Column('judgment_id', sa.Uuid(), nullable=True),
    sa.Column('citation', sa.String(length=500), nullable=True),
    sa.Column('proposition', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], name=op.f('fk_remedy_rule_authorities_judgment_id_judgments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['remedy_rules.id'], name=op.f('fk_remedy_rule_authorities_rule_id_remedy_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statute_section_id'], ['statute_sections.id'], name=op.f('fk_remedy_rule_authorities_statute_section_id_statute_sections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remedy_rule_authorities'))
    )
    with op.batch_alter_table('remedy_rule_authorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedy_rule_authorities_authority_type'), ['authority_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_authorities_citation'), ['citation'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_authorities_judgment_id'), ['judgment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_authorities_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_authorities_statute_section_id'), ['statute_section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_rule_authorities_verified'), ['verified'], unique=False)

    op.create_table('saved_case_acts',
    sa.Column('saved_case_id', sa.Uuid(), nullable=False),
    sa.Column('act_name', sa.String(length=400), nullable=False),
    sa.Column('sections_json', sa.JSON(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_saved_case_acts_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_case_acts'))
    )
    with op.batch_alter_table('saved_case_acts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_case_acts_act_name'), ['act_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_acts_saved_case_id'), ['saved_case_id'], unique=False)

    op.create_table('saved_case_advocates',
    sa.Column('saved_case_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('PETITIONER', 'RESPONDENT', name='caseside', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=350), nullable=False),
    sa.Column('enrollment_or_reference', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_saved_case_advocates_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_case_advocates'))
    )
    with op.batch_alter_table('saved_case_advocates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_case_advocates_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_advocates_saved_case_id'), ['saved_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_advocates_side'), ['side'], unique=False)

    op.create_table('saved_case_hearings',
    sa.Column('saved_case_id', sa.Uuid(), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=False),
    sa.Column('purpose_or_stage', sa.String(length=350), nullable=True),
    sa.Column('judge_or_bench', sa.String(length=350), nullable=True),
    sa.Column('result_or_note', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_saved_case_hearings_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_case_hearings'))
    )
    with op.batch_alter_table('saved_case_hearings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_case_hearings_hearing_date'), ['hearing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_hearings_saved_case_id'), ['saved_case_id'], unique=False)

    op.create_table('saved_case_judgments',
    sa.Column('saved_case_id', sa.Uuid(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('citation', sa.String(length=300), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('local_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['local_document_id'], ['documents.id'], name=op.f('fk_saved_case_judgments_local_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_saved_case_judgments_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_case_judgments'))
    )
    with op.batch_alter_table('saved_case_judgments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_case_judgments_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_judgments_citation'), ['citation'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_judgments_decision_date'), ['decision_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_judgments_local_document_id'), ['local_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_judgments_saved_case_id'), ['saved_case_id'], unique=False)

    op.create_table('saved_case_orders',
    sa.Column('saved_case_id', sa.Uuid(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('order_type', sa.String(length=180), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('local_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['local_document_id'], ['documents.id'], name=op.f('fk_saved_case_orders_local_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_saved_case_orders_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_case_orders'))
    )
    with op.batch_alter_table('saved_case_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_case_orders_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_orders_local_document_id'), ['local_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_orders_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_orders_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_orders_saved_case_id'), ['saved_case_id'], unique=False)

    op.create_table('saved_case_parties',
    sa.Column('saved_case_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('PETITIONER', 'RESPONDENT', name='caseside', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_saved_case_parties_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_case_parties'))
    )
    with op.batch_alter_table('saved_case_parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_case_parties_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_parties_saved_case_id'), ['saved_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_case_parties_side'), ['side'], unique=False)

    op.create_table('case_snapshot_changes',
    sa.Column('saved_case_id', sa.Uuid(), nullable=False),
    sa.Column('previous_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('current_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=160), nullable=False),
    sa.Column('change_type', sa.Enum('ADDED', 'REMOVED', 'CHANGED', name='casechangetype', native_enum=False), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=700), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['case_source_snapshots.id'], name=op.f('fk_case_snapshot_changes_current_snapshot_id_case_source_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['case_source_snapshots.id'], name=op.f('fk_case_snapshot_changes_previous_snapshot_id_case_source_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_case_snapshot_changes_reviewed_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['saved_case_id'], ['saved_cases.id'], name=op.f('fk_case_snapshot_changes_saved_case_id_saved_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_snapshot_changes'))
    )
    with op.batch_alter_table('case_snapshot_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_snapshot_changes_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_snapshot_changes_current_snapshot_id'), ['current_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_snapshot_changes_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_snapshot_changes_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_snapshot_changes_saved_case_id'), ['saved_case_id'], unique=False)

    op.create_table('remedy_candidates',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('remedy_code', sa.String(length=180), nullable=False),
    sa.Column('remedy_name_en', sa.String(length=300), nullable=False),
    sa.Column('remedy_name_hi', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('POSSIBLE', 'CONDITIONAL', 'NOT_MAINTAINABLE', 'NEEDS_RESEARCH', 'SELECTED', 'DISMISSED', name='remedycandidatestatus', native_enum=False), nullable=False),
    sa.Column('applicability_score', sa.Integer(), nullable=False),
    sa.Column('why_applicable_json', sa.JSON(), nullable=False),
    sa.Column('forum_json', sa.JSON(), nullable=False),
    sa.Column('deadline_json', sa.JSON(), nullable=False),
    sa.Column('maintainability_json', sa.JSON(), nullable=False),
    sa.Column('required_documents_json', sa.JSON(), nullable=False),
    sa.Column('procedural_steps_json', sa.JSON(), nullable=False),
    sa.Column('risks_json', sa.JSON(), nullable=False),
    sa.Column('drafting_json', sa.JSON(), nullable=False),
    sa.Column('lawyer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['remedy_analyses.id'], name=op.f('fk_remedy_candidates_analysis_id_remedy_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_remedy_candidates_reviewed_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['remedy_rules.id'], name=op.f('fk_remedy_candidates_rule_id_remedy_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remedy_candidates'))
    )
    with op.batch_alter_table('remedy_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedy_candidates_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidates_applicability_score'), ['applicability_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidates_remedy_code'), ['remedy_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidates_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidates_status'), ['status'], unique=False)

    op.create_table('remedy_candidate_authorities',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('authority_type', sa.Enum('STATUTE', 'RULE', 'JUDGMENT', 'CONSTITUTION', 'PROCEDURE', 'OTHER', name='remedyauthoritytype', native_enum=False), nullable=False),
    sa.Column('statute_section_id', sa.Uuid(), nullable=True),
    sa.Column('judgment_id', sa.Uuid(), nullable=True),
    sa.Column('citation', sa.String(length=500), nullable=True),
    sa.Column('proposition', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source_rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['remedy_candidates.id'], name=op.f('fk_remedy_candidate_authorities_candidate_id_remedy_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], name=op.f('fk_remedy_candidate_authorities_judgment_id_judgments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statute_section_id'], ['statute_sections.id'], name=op.f('fk_remedy_candidate_authorities_statute_section_id_statute_sections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remedy_candidate_authorities'))
    )
    with op.batch_alter_table('remedy_candidate_authorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedy_candidate_authorities_authority_type'), ['authority_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidate_authorities_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidate_authorities_citation'), ['citation'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidate_authorities_judgment_id'), ['judgment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidate_authorities_statute_section_id'), ['statute_section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_candidate_authorities_verified'), ['verified'], unique=False)

    op.create_table('remedy_draft_links',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('legal_draft_id', sa.Uuid(), nullable=False),
    sa.Column('requested_document_kind', sa.String(length=180), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['remedy_candidates.id'], name=op.f('fk_remedy_draft_links_candidate_id_remedy_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_remedy_draft_links_created_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['legal_draft_id'], ['legal_drafts.id'], name=op.f('fk_remedy_draft_links_legal_draft_id_legal_drafts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remedy_draft_links'))
    )
    with op.batch_alter_table('remedy_draft_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedy_draft_links_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_draft_links_legal_draft_id'), ['legal_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_draft_links_requested_document_kind'), ['requested_document_kind'], unique=False)

    op.create_table('remedy_memos',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW_REQUIRED', 'APPROVED', name='remedymemostatus', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('generated_deterministically', sa.Boolean(), nullable=False),
    sa.Column('ai_run_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], name=op.f('fk_remedy_memos_ai_run_id_ai_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['remedy_candidates.id'], name=op.f('fk_remedy_memos_candidate_id_remedy_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_remedy_memos_reviewed_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remedy_memos'))
    )
    with op.batch_alter_table('remedy_memos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remedy_memos_ai_run_id'), ['ai_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_memos_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remedy_memos_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedy_memos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_memos_status'))
        batch_op.drop_index(batch_op.f('ix_remedy_memos_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_memos_ai_run_id'))

    op.drop_table('remedy_memos')
    with op.batch_alter_table('remedy_draft_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_draft_links_requested_document_kind'))
        batch_op.drop_index(batch_op.f('ix_remedy_draft_links_legal_draft_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_draft_links_candidate_id'))

    op.drop_table('remedy_draft_links')
    with op.batch_alter_table('remedy_candidate_authorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_candidate_authorities_verified'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidate_authorities_statute_section_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidate_authorities_judgment_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidate_authorities_citation'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidate_authorities_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidate_authorities_authority_type'))

    op.drop_table('remedy_candidate_authorities')
    with op.batch_alter_table('remedy_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidates_rule_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidates_remedy_code'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidates_applicability_score'))
        batch_op.drop_index(batch_op.f('ix_remedy_candidates_analysis_id'))

    op.drop_table('remedy_candidates')
    with op.batch_alter_table('case_snapshot_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_snapshot_changes_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_case_snapshot_changes_field_name'))
        batch_op.drop_index(batch_op.f('ix_case_snapshot_changes_detected_at'))
        batch_op.drop_index(batch_op.f('ix_case_snapshot_changes_current_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_case_snapshot_changes_change_type'))

    op.drop_table('case_snapshot_changes')
    with op.batch_alter_table('saved_case_parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_case_parties_side'))
        batch_op.drop_index(batch_op.f('ix_saved_case_parties_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_saved_case_parties_name'))

    op.drop_table('saved_case_parties')
    with op.batch_alter_table('saved_case_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_case_orders_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_saved_case_orders_order_type'))
        batch_op.drop_index(batch_op.f('ix_saved_case_orders_order_date'))
        batch_op.drop_index(batch_op.f('ix_saved_case_orders_local_document_id'))
        batch_op.drop_index(batch_op.f('ix_saved_case_orders_checksum_sha256'))

    op.drop_table('saved_case_orders')
    with op.batch_alter_table('saved_case_judgments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_case_judgments_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_saved_case_judgments_local_document_id'))
        batch_op.drop_index(batch_op.f('ix_saved_case_judgments_decision_date'))
        batch_op.drop_index(batch_op.f('ix_saved_case_judgments_citation'))
        batch_op.drop_index(batch_op.f('ix_saved_case_judgments_checksum_sha256'))

    op.drop_table('saved_case_judgments')
    with op.batch_alter_table('saved_case_hearings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_case_hearings_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_saved_case_hearings_hearing_date'))

    op.drop_table('saved_case_hearings')
    with op.batch_alter_table('saved_case_advocates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_case_advocates_side'))
        batch_op.drop_index(batch_op.f('ix_saved_case_advocates_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_saved_case_advocates_name'))

    op.drop_table('saved_case_advocates')
    with op.batch_alter_table('saved_case_acts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_case_acts_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_saved_case_acts_act_name'))

    op.drop_table('saved_case_acts')
    with op.batch_alter_table('remedy_rule_authorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_rule_authorities_verified'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_authorities_statute_section_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_authorities_rule_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_authorities_judgment_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_authorities_citation'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_authorities_authority_type'))

    op.drop_table('remedy_rule_authorities')
    with op.batch_alter_table('remedy_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_remedy_analyses_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_analyses_organization_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_analyses_matter_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_analyses_language'))
        batch_op.drop_index(batch_op.f('ix_remedy_analyses_analyzed_at'))

    op.drop_table('remedy_analyses')
    with op.batch_alter_table('case_source_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_source_snapshots_source_kind'))
        batch_op.drop_index(batch_op.f('ix_case_source_snapshots_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_case_source_snapshots_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_case_source_snapshots_content_hash'))

    op.drop_table('case_source_snapshots')
    with op.batch_alter_table('case_lookup_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_lookup_candidates_source_kind'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_candidates_saved_case_id'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_candidates_rank_score'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_candidates_lookup_run_id'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_candidates_exact_match'))

    op.drop_table('case_lookup_candidates')
    with op.batch_alter_table('saved_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_cases_year'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_state'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_stale_after'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_source_kind'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_source_case_key'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_record_status'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_previous_hearing_date'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_organization_id'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_next_hearing_date'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_matter_id'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_district'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_current_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_court_name'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_court_level'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_court_code'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_cnr'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_case_type'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_case_title'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_case_status'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_case_stage'))
        batch_op.drop_index(batch_op.f('ix_saved_cases_case_number'))

    op.drop_table('saved_cases')
    with op.batch_alter_table('case_lookup_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_lookup_runs_status'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_runs_raw_query'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_runs_detected_kind'))

    op.drop_table('case_lookup_runs')
    with op.batch_alter_table('case_lookup_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_lookup_preferences_preferred_state'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_preferences_preferred_high_court'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_preferences_preferred_district'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_preferences_organization_id'))
        batch_op.drop_index(batch_op.f('ix_case_lookup_preferences_membership_id'))

    op.drop_table('case_lookup_preferences')
    with op.batch_alter_table('remedy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_rules_verified'))
        batch_op.drop_index(batch_op.f('ix_remedy_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_remedy_rules_pack_id'))
        batch_op.drop_index(batch_op.f('ix_remedy_rules_code'))

    op.drop_table('remedy_rules')
    with op.batch_alter_table('remedy_rule_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_rule_packs_version'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_packs_verified'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_packs_status'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_packs_proceeding_type'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_packs_jurisdiction'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_packs_court_level'))
        batch_op.drop_index(batch_op.f('ix_remedy_rule_packs_code'))

    op.drop_table('remedy_rule_packs')
    # ### end Alembic commands ###
