"""quality assurance legal accuracy evaluation

Revision ID: 20260808_0021
Revises: 20260808_0020
Create Date: 2026-08-08 12:27:02.075513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0021'
down_revision: Union[str, None] = '20260808_0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_suites',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('suite_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_gate', sa.Boolean(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evaluation_suites_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_suites')),
    sa.UniqueConstraint('organization_id', 'suite_key', name='uq_evaluation_suite_org_key')
    )
    with op.batch_alter_table('evaluation_suites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_suites_default_gate'), ['default_gate'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_suites_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_suites_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_suites_suite_key'), ['suite_key'], unique=False)

    op.create_table('release_quality_gates',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_overall_score', sa.Float(), nullable=False),
    sa.Column('max_critical_failures', sa.Integer(), nullable=False),
    sa.Column('require_security_zero_failures', sa.Boolean(), nullable=False),
    sa.Column('require_citation_zero_failures', sa.Boolean(), nullable=False),
    sa.Column('category_thresholds_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_release_quality_gates_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_quality_gates'))
    )
    with op.batch_alter_table('release_quality_gates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_quality_gates_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_quality_gates_organization_id'), ['organization_id'], unique=False)

    op.create_table('evaluation_cases',
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('case_key', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('evaluator', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('expected_json', sa.JSON(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['evaluation_suites.id'], name=op.f('fk_evaluation_cases_suite_id_evaluation_suites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_cases')),
    sa.UniqueConstraint('suite_id', 'case_key', name='uq_evaluation_case_suite_key')
    )
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_cases_case_key'), ['case_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_critical'), ['critical'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_evaluator'), ['evaluator'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_source_hash'), ['source_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_suite_id'), ['suite_id'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('app_version', sa.String(length=80), nullable=True),
    sa.Column('build_ref', sa.String(length=160), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('passed_cases', sa.Integer(), nullable=False),
    sa.Column('failed_cases', sa.Integer(), nullable=False),
    sa.Column('skipped_cases', sa.Integer(), nullable=False),
    sa.Column('critical_failures', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evaluation_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_evaluation_runs_requested_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suite_id'], ['evaluation_suites.id'], name=op.f('fk_evaluation_runs_suite_id_evaluation_suites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_suite_id'), ['suite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_trigger'), ['trigger'], unique=False)

    op.create_table('evaluation_baselines',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_evaluation_baselines_approved_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evaluation_baselines_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluation_baselines_run_id_evaluation_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['suite_id'], ['evaluation_suites.id'], name=op.f('fk_evaluation_baselines_suite_id_evaluation_suites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_baselines')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_evaluation_baseline_org_name')
    )
    with op.batch_alter_table('evaluation_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_baselines_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_baselines_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_baselines_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_baselines_suite_id'), ['suite_id'], unique=False)

    op.create_table('evaluation_case_runs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('actual_json', sa.JSON(), nullable=False),
    sa.Column('expected_json', sa.JSON(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], name=op.f('fk_evaluation_case_runs_case_id_evaluation_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluation_case_runs_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_case_runs')),
    sa.UniqueConstraint('run_id', 'case_id', name='uq_evaluation_case_run_case')
    )
    with op.batch_alter_table('evaluation_case_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_case_runs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_case_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_case_runs_status'), ['status'], unique=False)

    op.create_table('evaluation_metrics',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('metric_key', sa.String(length=180), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluation_metrics_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_metrics')),
    sa.UniqueConstraint('run_id', 'metric_key', name='uq_evaluation_metric_run_key')
    )
    with op.batch_alter_table('evaluation_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_metrics_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_metrics_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_metrics_passed'), ['passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_metrics_run_id'), ['run_id'], unique=False)

    op.create_table('release_quality_gate_runs',
    sa.Column('gate_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('category_scores_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], name=op.f('fk_release_quality_gate_runs_evaluation_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gate_id'], ['release_quality_gates.id'], name=op.f('fk_release_quality_gate_runs_gate_id_release_quality_gates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_quality_gate_runs'))
    )
    with op.batch_alter_table('release_quality_gate_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_quality_gate_runs_evaluated_at'), ['evaluated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_quality_gate_runs_evaluation_run_id'), ['evaluation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_quality_gate_runs_gate_id'), ['gate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_quality_gate_runs_passed'), ['passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_quality_gate_runs_snapshot_hash'), ['snapshot_hash'], unique=False)

    op.create_table('qa_findings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('case_run_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_run_id'], ['evaluation_case_runs.id'], name=op.f('fk_qa_findings_case_run_id_evaluation_case_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_qa_findings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_qa_findings_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_findings'))
    )
    with op.batch_alter_table('qa_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_findings_case_run_id'), ['case_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_findings_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_findings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_findings_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_findings_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_findings_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_qa_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_qa_findings_resolved'))
        batch_op.drop_index(batch_op.f('ix_qa_findings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_qa_findings_code'))
        batch_op.drop_index(batch_op.f('ix_qa_findings_category'))
        batch_op.drop_index(batch_op.f('ix_qa_findings_case_run_id'))

    op.drop_table('qa_findings')
    with op.batch_alter_table('release_quality_gate_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_quality_gate_runs_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_release_quality_gate_runs_passed'))
        batch_op.drop_index(batch_op.f('ix_release_quality_gate_runs_gate_id'))
        batch_op.drop_index(batch_op.f('ix_release_quality_gate_runs_evaluation_run_id'))
        batch_op.drop_index(batch_op.f('ix_release_quality_gate_runs_evaluated_at'))

    op.drop_table('release_quality_gate_runs')
    with op.batch_alter_table('evaluation_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_metrics_run_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_metrics_passed'))
        batch_op.drop_index(batch_op.f('ix_evaluation_metrics_metric_key'))
        batch_op.drop_index(batch_op.f('ix_evaluation_metrics_category'))

    op.drop_table('evaluation_metrics')
    with op.batch_alter_table('evaluation_case_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_case_runs_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_case_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_case_runs_case_id'))

    op.drop_table('evaluation_case_runs')
    with op.batch_alter_table('evaluation_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_baselines_suite_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_baselines_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_evaluation_baselines_run_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_baselines_organization_id'))

    op.drop_table('evaluation_baselines')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_trigger'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_suite_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_organization_id'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_suite_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_source_hash'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_evaluator'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_critical'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_category'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_case_key'))

    op.drop_table('evaluation_cases')
    with op.batch_alter_table('release_quality_gates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_quality_gates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_release_quality_gates_enabled'))

    op.drop_table('release_quality_gates')
    with op.batch_alter_table('evaluation_suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_suites_suite_key'))
        batch_op.drop_index(batch_op.f('ix_evaluation_suites_organization_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_suites_enabled'))
        batch_op.drop_index(batch_op.f('ix_evaluation_suites_default_gate'))

    op.drop_table('evaluation_suites')
    # ### end Alembic commands ###
