"""law firm analytics quality supervision

Revision ID: 20260808_0016
Revises: 20260808_0015
Create Date: 2026-08-08 09:08:19.513159
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0016'
down_revision: Union[str, None] = '20260808_0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_metric_definitions',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('metric_key', sa.String(length=180), nullable=False),
    sa.Column('name_en', sa.String(length=260), nullable=False),
    sa.Column('name_hi', sa.String(length=260), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('direction', sa.Enum('HIGHER_BETTER', 'LOWER_BETTER', 'NEUTRAL', name='metricdirection', native_enum=False), nullable=False),
    sa.Column('formula_json', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analytics_metric_definitions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_metric_definitions')),
    sa.UniqueConstraint('organization_id', 'metric_key', name='uq_analytics_metric_org_key')
    )
    with op.batch_alter_table('analytics_metric_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_metric_definitions_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metric_definitions_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metric_definitions_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metric_definitions_organization_id'), ['organization_id'], unique=False)

    op.create_table('analytics_preferences',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('rolling_window_days', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('health_weights_json', sa.JSON(), nullable=False),
    sa.Column('thresholds_json', sa.JSON(), nullable=False),
    sa.Column('enable_risk_detection', sa.Boolean(), nullable=False),
    sa.Column('show_financials_to_partners', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analytics_preferences_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_preferences')),
    sa.UniqueConstraint('organization_id', name='uq_analytics_preferences_org')
    )
    with op.batch_alter_table('analytics_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_preferences_organization_id'), ['organization_id'], unique=False)

    op.create_table('analytics_goals',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('metric_key', sa.String(length=180), nullable=False),
    sa.Column('scope_type', sa.Enum('ORGANIZATION', 'MATTER', 'MEMBER', 'CLIENT', name='analyticsscope', native_enum=False), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('comparison', sa.Enum('AT_LEAST', 'AT_MOST', 'EXACT', name='goalcomparison', native_enum=False), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='analyticsgoalstatus', native_enum=False), nullable=False),
    sa.Column('created_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_analytics_goals_created_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analytics_goals_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_goals'))
    )
    with op.batch_alter_table('analytics_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_goals_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goals_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goals_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goals_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goals_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goals_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goals_status'), ['status'], unique=False)

    op.create_table('analytics_snapshots',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('MANUAL', 'DAILY', 'WEEKLY', 'MONTHLY', name='snapshotkind', native_enum=False), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_analytics_snapshots_generated_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analytics_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_snapshots'))
    )
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_generated_by_membership_id'), ['generated_by_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_payload_hash'), ['payload_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_period_start'), ['period_start'], unique=False)

    op.create_table('analytics_goal_progress',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('target_met', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['analytics_goals.id'], name=op.f('fk_analytics_goal_progress_goal_id_analytics_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analytics_snapshots.id'], name=op.f('fk_analytics_goal_progress_snapshot_id_analytics_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_goal_progress'))
    )
    with op.batch_alter_table('analytics_goal_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_goal_progress_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goal_progress_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goal_progress_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_goal_progress_target_met'), ['target_met'], unique=False)

    op.create_table('analytics_metric_values',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.String(length=180), nullable=False),
    sa.Column('scope_type', sa.Enum('ORGANIZATION', 'MATTER', 'MEMBER', 'CLIENT', name='analyticsscope', native_enum=False), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analytics_snapshots.id'], name=op.f('fk_analytics_metric_values_snapshot_id_analytics_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_metric_values')),
    sa.UniqueConstraint('snapshot_id', 'metric_key', 'scope_type', 'scope_id', name='uq_analytics_metric_value_scope')
    )
    with op.batch_alter_table('analytics_metric_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_metric_values_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metric_values_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metric_values_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metric_values_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('matter_health_snapshots',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='analyticsriskseverity', native_enum=False), nullable=False),
    sa.Column('overdue_tasks', sa.Integer(), nullable=False),
    sa.Column('high_priority_tasks', sa.Integer(), nullable=False),
    sa.Column('deadlines_due_7d', sa.Integer(), nullable=False),
    sa.Column('open_contradictions', sa.Integer(), nullable=False),
    sa.Column('open_high_draft_findings', sa.Integer(), nullable=False),
    sa.Column('unreviewed_court_changes', sa.Integer(), nullable=False),
    sa.Column('open_evidence_gaps', sa.Integer(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_matter_health_snapshots_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analytics_snapshots.id'], name=op.f('fk_matter_health_snapshots_snapshot_id_analytics_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_health_snapshots')),
    sa.UniqueConstraint('snapshot_id', 'matter_id', name='uq_matter_health_snapshot')
    )
    with op.batch_alter_table('matter_health_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matter_health_snapshots_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_health_snapshots_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_health_snapshots_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_matter_health_snapshots_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('member_performance_snapshots',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('open_tasks', sa.Integer(), nullable=False),
    sa.Column('overdue_tasks', sa.Integer(), nullable=False),
    sa.Column('high_priority_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks_window', sa.Integer(), nullable=False),
    sa.Column('billable_minutes_window', sa.Integer(), nullable=False),
    sa.Column('submitted_minutes_window', sa.Integer(), nullable=False),
    sa.Column('workload_score', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_member_performance_snapshots_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analytics_snapshots.id'], name=op.f('fk_member_performance_snapshots_snapshot_id_analytics_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_performance_snapshots')),
    sa.UniqueConstraint('snapshot_id', 'membership_id', name='uq_member_performance_snapshot')
    )
    with op.batch_alter_table('member_performance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_performance_snapshots_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_performance_snapshots_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_performance_snapshots_workload_score'), ['workload_score'], unique=False)

    op.create_table('analytics_risk_signals',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('signal_type', sa.String(length=180), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='analyticsriskseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='analyticsriskstatus', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=350), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('metric_key', sa.String(length=180), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=320), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_analytics_risk_signals_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_analytics_risk_signals_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_analytics_risk_signals_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analytics_risk_signals_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['security_users.id'], name=op.f('fk_analytics_risk_signals_reviewed_by_user_id_security_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_risk_signals')),
    sa.UniqueConstraint('organization_id', 'dedupe_key', name='uq_analytics_risk_org_dedupe')
    )
    with op.batch_alter_table('analytics_risk_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_risk_signals_status'), ['status'], unique=False)

    op.create_table('client_health_snapshots',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('overdue_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('open_portal_requests', sa.Integer(), nullable=False),
    sa.Column('active_matters', sa.Integer(), nullable=False),
    sa.Column('last_communication_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_health_snapshots_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analytics_snapshots.id'], name=op.f('fk_client_health_snapshots_snapshot_id_analytics_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_health_snapshots')),
    sa.UniqueConstraint('snapshot_id', 'client_id', name='uq_client_health_snapshot')
    )
    with op.batch_alter_table('client_health_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_health_snapshots_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_health_snapshots_health_score'), ['health_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_health_snapshots_last_communication_at'), ['last_communication_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_health_snapshots_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_health_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_health_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_client_health_snapshots_last_communication_at'))
        batch_op.drop_index(batch_op.f('ix_client_health_snapshots_health_score'))
        batch_op.drop_index(batch_op.f('ix_client_health_snapshots_client_id'))

    op.drop_table('client_health_snapshots')
    with op.batch_alter_table('analytics_risk_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_status'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_severity'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_metric_key'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_membership_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_matter_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_detected_at'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_analytics_risk_signals_client_id'))

    op.drop_table('analytics_risk_signals')
    with op.batch_alter_table('member_performance_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_performance_snapshots_workload_score'))
        batch_op.drop_index(batch_op.f('ix_member_performance_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_member_performance_snapshots_membership_id'))

    op.drop_table('member_performance_snapshots')
    with op.batch_alter_table('matter_health_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matter_health_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_matter_health_snapshots_score'))
        batch_op.drop_index(batch_op.f('ix_matter_health_snapshots_risk_level'))
        batch_op.drop_index(batch_op.f('ix_matter_health_snapshots_matter_id'))

    op.drop_table('matter_health_snapshots')
    with op.batch_alter_table('analytics_metric_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_metric_values_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_metric_values_scope_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_metric_values_scope_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_metric_values_metric_key'))

    op.drop_table('analytics_metric_values')
    with op.batch_alter_table('analytics_goal_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_goal_progress_target_met'))
        batch_op.drop_index(batch_op.f('ix_analytics_goal_progress_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_goal_progress_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_analytics_goal_progress_goal_id'))

    op.drop_table('analytics_goal_progress')
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_period_start'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_period_end'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_kind'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_generated_by_membership_id'))

    op.drop_table('analytics_snapshots')
    with op.batch_alter_table('analytics_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_goals_status'))
        batch_op.drop_index(batch_op.f('ix_analytics_goals_start_date'))
        batch_op.drop_index(batch_op.f('ix_analytics_goals_scope_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_goals_scope_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_goals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_goals_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_goals_metric_key'))
        batch_op.drop_index(batch_op.f('ix_analytics_goals_end_date'))

    op.drop_table('analytics_goals')
    with op.batch_alter_table('analytics_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_preferences_organization_id'))

    op.drop_table('analytics_preferences')
    with op.batch_alter_table('analytics_metric_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_metric_definitions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_metric_definitions_metric_key'))
        batch_op.drop_index(batch_op.f('ix_analytics_metric_definitions_direction'))
        batch_op.drop_index(batch_op.f('ix_analytics_metric_definitions_active'))

    op.drop_table('analytics_metric_definitions')
    # ### end Alembic commands ###
