"""release candidate production validation

Revision ID: 20260808_0027
Revises: 20260808_0026
Create Date: 2026-08-08 15:05:58.769735
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0027'
down_revision: Union[str, None] = '20260808_0026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_scenarios',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_key', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('execution_mode', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('thresholds_json', sa.JSON(), nullable=False),
    sa.Column('instructions_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_validation_scenarios_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_scenarios')),
    sa.UniqueConstraint('organization_id', 'scenario_key', name='uq_validation_scenario_org_key')
    )
    with op.batch_alter_table('validation_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_scenarios_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_scenarios_execution_mode'), ['execution_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_scenarios_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_scenarios_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_scenarios_scenario_key'), ['scenario_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_scenarios_severity'), ['severity'], unique=False)

    op.create_table('validation_campaigns',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('release_run_id', sa.Uuid(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('candidate_version', sa.String(length=100), nullable=False),
    sa.Column('build_ref', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], name=op.f('fk_validation_campaigns_environment_id_deployment_environments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_validation_campaigns_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_validation_campaigns_release_run_id_release_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_campaigns'))
    )
    with op.batch_alter_table('validation_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_campaigns_candidate_version'), ['candidate_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_campaigns_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_campaigns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_campaigns_release_run_id'), ['release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_campaigns_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_campaigns_status'), ['status'], unique=False)

    op.create_table('pilot_readiness_checks',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('check_key', sa.String(length=140), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['validation_campaigns.id'], name=op.f('fk_pilot_readiness_checks_campaign_id_validation_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_pilot_readiness_checks_reviewed_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_readiness_checks')),
    sa.UniqueConstraint('campaign_id', 'check_key', name='uq_pilot_check_campaign_key')
    )
    with op.batch_alter_table('pilot_readiness_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pilot_readiness_checks_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pilot_readiness_checks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_pilot_readiness_checks_check_key'), ['check_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_pilot_readiness_checks_status'), ['status'], unique=False)

    op.create_table('release_candidate_manifests',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('release_run_id', sa.Uuid(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('candidate_version', sa.String(length=100), nullable=False),
    sa.Column('database_revision', sa.String(length=180), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('gate_json', sa.JSON(), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['validation_campaigns.id'], name=op.f('fk_release_candidate_manifests_campaign_id_validation_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], name=op.f('fk_release_candidate_manifests_environment_id_deployment_environments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_release_candidate_manifests_release_run_id_release_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_candidate_manifests')),
    sa.UniqueConstraint('campaign_id', name='uq_release_candidate_campaign')
    )
    with op.batch_alter_table('release_candidate_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_candidate_manifests_artifact_sha256'), ['artifact_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_candidate_manifests_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_candidate_manifests_candidate_version'), ['candidate_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_candidate_manifests_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_candidate_manifests_release_run_id'), ['release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_candidate_manifests_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_candidate_manifests_status'), ['status'], unique=False)

    op.create_table('validation_datasets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('generation_seed', sa.Integer(), nullable=True),
    sa.Column('manifest_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['validation_campaigns.id'], name=op.f('fk_validation_datasets_campaign_id_validation_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_validation_datasets_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_datasets'))
    )
    with op.batch_alter_table('validation_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_datasets_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_datasets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_datasets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_datasets_sha256'), ['sha256'], unique=False)

    op.create_table('validation_scenario_runs',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['validation_campaigns.id'], name=op.f('fk_validation_scenario_runs_campaign_id_validation_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['validation_scenarios.id'], name=op.f('fk_validation_scenario_runs_scenario_id_validation_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_scenario_runs')),
    sa.UniqueConstraint('campaign_id', 'scenario_id', name='uq_validation_campaign_scenario')
    )
    with op.batch_alter_table('validation_scenario_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_scenario_runs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_scenario_runs_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_scenario_runs_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_scenario_runs_status'), ['status'], unique=False)

    op.create_table('validation_signoffs',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('role_label', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['validation_campaigns.id'], name=op.f('fk_validation_signoffs_campaign_id_validation_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_validation_signoffs_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_signoffs')),
    sa.UniqueConstraint('campaign_id', 'membership_id', name='uq_validation_signoff_campaign_member')
    )
    with op.batch_alter_table('validation_signoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_signoffs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_signoffs_decided_at'), ['decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_signoffs_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_signoffs_membership_id'), ['membership_id'], unique=False)

    op.create_table('validation_evidence',
    sa.Column('scenario_run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['validation_scenario_runs.id'], name=op.f('fk_validation_evidence_scenario_run_id_validation_scenario_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_evidence'))
    )
    with op.batch_alter_table('validation_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_evidence_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_evidence_scenario_run_id'), ['scenario_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_evidence_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_evidence_sha256'))
        batch_op.drop_index(batch_op.f('ix_validation_evidence_scenario_run_id'))
        batch_op.drop_index(batch_op.f('ix_validation_evidence_kind'))

    op.drop_table('validation_evidence')
    with op.batch_alter_table('validation_signoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_signoffs_membership_id'))
        batch_op.drop_index(batch_op.f('ix_validation_signoffs_decision'))
        batch_op.drop_index(batch_op.f('ix_validation_signoffs_decided_at'))
        batch_op.drop_index(batch_op.f('ix_validation_signoffs_campaign_id'))

    op.drop_table('validation_signoffs')
    with op.batch_alter_table('validation_scenario_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_scenario_runs_status'))
        batch_op.drop_index(batch_op.f('ix_validation_scenario_runs_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_validation_scenario_runs_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_validation_scenario_runs_campaign_id'))

    op.drop_table('validation_scenario_runs')
    with op.batch_alter_table('validation_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_datasets_sha256'))
        batch_op.drop_index(batch_op.f('ix_validation_datasets_organization_id'))
        batch_op.drop_index(batch_op.f('ix_validation_datasets_kind'))
        batch_op.drop_index(batch_op.f('ix_validation_datasets_campaign_id'))

    op.drop_table('validation_datasets')
    with op.batch_alter_table('release_candidate_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_candidate_manifests_status'))
        batch_op.drop_index(batch_op.f('ix_release_candidate_manifests_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_release_candidate_manifests_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_release_candidate_manifests_environment_id'))
        batch_op.drop_index(batch_op.f('ix_release_candidate_manifests_candidate_version'))
        batch_op.drop_index(batch_op.f('ix_release_candidate_manifests_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_release_candidate_manifests_artifact_sha256'))

    op.drop_table('release_candidate_manifests')
    with op.batch_alter_table('pilot_readiness_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pilot_readiness_checks_status'))
        batch_op.drop_index(batch_op.f('ix_pilot_readiness_checks_check_key'))
        batch_op.drop_index(batch_op.f('ix_pilot_readiness_checks_category'))
        batch_op.drop_index(batch_op.f('ix_pilot_readiness_checks_campaign_id'))

    op.drop_table('pilot_readiness_checks')
    with op.batch_alter_table('validation_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_validation_campaigns_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_validation_campaigns_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_validation_campaigns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_validation_campaigns_environment_id'))
        batch_op.drop_index(batch_op.f('ix_validation_campaigns_candidate_version'))

    op.drop_table('validation_campaigns')
    with op.batch_alter_table('validation_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_scenarios_severity'))
        batch_op.drop_index(batch_op.f('ix_validation_scenarios_scenario_key'))
        batch_op.drop_index(batch_op.f('ix_validation_scenarios_organization_id'))
        batch_op.drop_index(batch_op.f('ix_validation_scenarios_kind'))
        batch_op.drop_index(batch_op.f('ix_validation_scenarios_execution_mode'))
        batch_op.drop_index(batch_op.f('ix_validation_scenarios_enabled'))

    op.drop_table('validation_scenarios')
    # ### end Alembic commands ###
