"""search index document intelligence performance

Revision ID: 20260808_0018
Revises: 20260808_0017
Create Date: 2026-08-08 09:41:22.327699
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0018'
down_revision: Union[str, None] = '20260808_0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_index_cursors',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('last_source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_entity_id', sa.Uuid(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_search_index_cursors_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_index_cursors')),
    sa.UniqueConstraint('organization_id', 'source_name', name='uq_search_index_cursor_org_source')
    )
    with op.batch_alter_table('search_index_cursors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_index_cursors_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_cursors_source_name'), ['source_name'], unique=False)

    op.create_table('search_index_health_snapshots',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('stale_count', sa.Integer(), nullable=False),
    sa.Column('exact_duplicate_pairs', sa.Integer(), nullable=False),
    sa.Column('near_duplicate_pairs', sa.Integer(), nullable=False),
    sa.Column('by_entity_json', sa.JSON(), nullable=False),
    sa.Column('last_completed_job_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_search_index_health_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_index_health_snapshots'))
    )
    with op.batch_alter_table('search_index_health_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_index_health_snapshots_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_health_snapshots_snapshot_hash'), ['snapshot_hash'], unique=False)

    op.create_table('search_performance_preferences',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('use_index', sa.Boolean(), nullable=False),
    sa.Column('lexical_weight', sa.Float(), nullable=False),
    sa.Column('feature_vector_weight', sa.Float(), nullable=False),
    sa.Column('exact_title_weight', sa.Float(), nullable=False),
    sa.Column('type_weight', sa.Float(), nullable=False),
    sa.Column('near_duplicate_hamming', sa.Integer(), nullable=False),
    sa.Column('near_duplicate_jaccard', sa.Float(), nullable=False),
    sa.Column('max_candidate_rows', sa.Integer(), nullable=False),
    sa.Column('local_embedding_mode', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_search_performance_preferences_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_performance_preferences')),
    sa.UniqueConstraint('organization_id', name='uq_search_performance_preferences_org')
    )
    with op.batch_alter_table('search_performance_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_performance_preferences_organization_id'), ['organization_id'], unique=False)

    op.create_table('search_index_jobs',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('entries_seen', sa.Integer(), nullable=False),
    sa.Column('entries_created', sa.Integer(), nullable=False),
    sa.Column('entries_updated', sa.Integer(), nullable=False),
    sa.Column('entries_deleted', sa.Integer(), nullable=False),
    sa.Column('duplicates_detected', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_search_index_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_search_index_jobs_requested_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_index_jobs'))
    )
    with op.batch_alter_table('search_index_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_index_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_jobs_requested_by_membership_id'), ['requested_by_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_jobs_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_jobs_status'), ['status'], unique=False)

    op.create_table('search_index_entries',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_key', sa.String(length=220), nullable=False),
    sa.Column('source_key', sa.String(length=700), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=700), nullable=False),
    sa.Column('subtitle', sa.String(length=1000), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('href', sa.String(length=1200), nullable=False),
    sa.Column('badges_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('simhash64', sa.String(length=16), nullable=False),
    sa.Column('feature_vector_json', sa.JSON(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('rank_weight', sa.Float(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_search_index_entries_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_search_index_entries_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_search_index_entries_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_index_entries')),
    sa.UniqueConstraint('source_key', name='uq_search_index_entry_source_key')
    )
    with op.batch_alter_table('search_index_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_index_entries_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_indexed_at'), ['indexed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_simhash64'), ['simhash64'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_entries_title'), ['title'], unique=False)

    op.create_table('search_duplicate_relations',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('left_entry_id', sa.Uuid(), nullable=False),
    sa.Column('right_entry_id', sa.Uuid(), nullable=False),
    sa.Column('relation_kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('hamming_distance', sa.Integer(), nullable=False),
    sa.Column('shingle_jaccard', sa.Float(), nullable=False),
    sa.Column('reviewed_by_membership_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['left_entry_id'], ['search_index_entries.id'], name=op.f('fk_search_duplicate_relations_left_entry_id_search_index_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_search_duplicate_relations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_search_duplicate_relations_reviewed_by_membership_id_organization_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['right_entry_id'], ['search_index_entries.id'], name=op.f('fk_search_duplicate_relations_right_entry_id_search_index_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_duplicate_relations')),
    sa.UniqueConstraint('left_entry_id', 'right_entry_id', name='uq_search_duplicate_pair')
    )
    with op.batch_alter_table('search_duplicate_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_duplicate_relations_left_entry_id'), ['left_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_duplicate_relations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_duplicate_relations_relation_kind'), ['relation_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_duplicate_relations_right_entry_id'), ['right_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_duplicate_relations_status'), ['status'], unique=False)

    # PostgreSQL production acceleration. SQLite development keeps the portable B-tree indexes above.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute("CREATE INDEX IF NOT EXISTS ix_search_index_entries_fts ON search_index_entries USING gin (to_tsvector('simple', normalized_text))")
        op.execute("CREATE INDEX IF NOT EXISTS ix_search_index_entries_trgm ON search_index_entries USING gin (normalized_text gin_trgm_ops)")
        op.execute("CREATE INDEX IF NOT EXISTS ix_search_index_entries_title_trgm ON search_index_entries USING gin (title gin_trgm_ops)")

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_search_index_entries_title_trgm")
        op.execute("DROP INDEX IF EXISTS ix_search_index_entries_trgm")
        op.execute("DROP INDEX IF EXISTS ix_search_index_entries_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_duplicate_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_duplicate_relations_status'))
        batch_op.drop_index(batch_op.f('ix_search_duplicate_relations_right_entry_id'))
        batch_op.drop_index(batch_op.f('ix_search_duplicate_relations_relation_kind'))
        batch_op.drop_index(batch_op.f('ix_search_duplicate_relations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_search_duplicate_relations_left_entry_id'))

    op.drop_table('search_duplicate_relations')
    with op.batch_alter_table('search_index_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_index_entries_title'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_source_key'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_simhash64'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_matter_id'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_language'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_indexed_at'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_entity_type'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_entity_id'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_content_hash'))
        batch_op.drop_index(batch_op.f('ix_search_index_entries_client_id'))

    op.drop_table('search_index_entries')
    with op.batch_alter_table('search_index_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_index_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_search_index_jobs_scope_id'))
        batch_op.drop_index(batch_op.f('ix_search_index_jobs_requested_by_membership_id'))
        batch_op.drop_index(batch_op.f('ix_search_index_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_search_index_jobs_kind'))

    op.drop_table('search_index_jobs')
    with op.batch_alter_table('search_performance_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_performance_preferences_organization_id'))

    op.drop_table('search_performance_preferences')
    with op.batch_alter_table('search_index_health_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_index_health_snapshots_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_search_index_health_snapshots_organization_id'))

    op.drop_table('search_index_health_snapshots')
    with op.batch_alter_table('search_index_cursors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_index_cursors_source_name'))
        batch_op.drop_index(batch_op.f('ix_search_index_cursors_organization_id'))

    op.drop_table('search_index_cursors')
    # ### end Alembic commands ###
