"""production deployment topology

Revision ID: 20260808_0023
Revises: 20260808_0022
Create Date: 2026-08-08 13:07:26.221037
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0023'
down_revision: Union[str, None] = '20260808_0022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_environments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('environment_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.String(length=600), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tls_required', sa.Boolean(), nullable=False),
    sa.Column('object_storage_required', sa.Boolean(), nullable=False),
    sa.Column('change_window_required', sa.Boolean(), nullable=False),
    sa.Column('current_release_run_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_release_run_id'], ['release_runs.id'], name=op.f('fk_deployment_environments_current_release_run_id_release_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_deployment_environments_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_environments')),
    sa.UniqueConstraint('organization_id', 'environment_key', name='uq_deployment_environment_org_key')
    )
    with op.batch_alter_table('deployment_environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_environments_current_release_run_id'), ['current_release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_environments_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_environments_environment_key'), ['environment_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_environments_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_environments_organization_id'), ['organization_id'], unique=False)

    op.create_table('deployment_change_windows',
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_membership_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=900), nullable=False),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_deployment_change_windows_approved_by_membership_id_organization_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], name=op.f('fk_deployment_change_windows_environment_id_deployment_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_change_windows'))
    )
    with op.batch_alter_table('deployment_change_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_change_windows_approved_by_membership_id'), ['approved_by_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_change_windows_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_change_windows_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_change_windows_starts_at'), ['starts_at'], unique=False)

    op.create_table('deployment_secret_references',
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('secret_key', sa.String(length=180), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=1000), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], name=op.f('fk_deployment_secret_references_environment_id_deployment_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_secret_references')),
    sa.UniqueConstraint('environment_id', 'secret_key', name='uq_deployment_secret_environment_key')
    )
    with op.batch_alter_table('deployment_secret_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_secret_references_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_secret_references_secret_key'), ['secret_key'], unique=False)

    op.create_table('deployment_service_profiles',
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('service_key', sa.String(length=80), nullable=False),
    sa.Column('image_ref', sa.String(length=700), nullable=True),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_path', sa.String(length=300), nullable=True),
    sa.Column('queue_names', sa.String(length=600), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], name=op.f('fk_deployment_service_profiles_environment_id_deployment_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_service_profiles')),
    sa.UniqueConstraint('environment_id', 'service_key', name='uq_deployment_service_environment_key')
    )
    with op.batch_alter_table('deployment_service_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_service_profiles_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_service_profiles_service_key'), ['service_key'], unique=False)

    op.create_table('deployment_rollouts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('release_run_id', sa.Uuid(), nullable=False),
    sa.Column('rollback_point_id', sa.Uuid(), nullable=False),
    sa.Column('change_window_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_membership_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['change_window_id'], ['deployment_change_windows.id'], name=op.f('fk_deployment_rollouts_change_window_id_deployment_change_windows'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], name=op.f('fk_deployment_rollouts_environment_id_deployment_environments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_deployment_rollouts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_run_id'], ['release_runs.id'], name=op.f('fk_deployment_rollouts_release_run_id_release_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_membership_id'], ['organization_memberships.id'], name=op.f('fk_deployment_rollouts_requested_by_membership_id_organization_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rollback_point_id'], ['rollback_points.id'], name=op.f('fk_deployment_rollouts_rollback_point_id_rollback_points'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_rollouts'))
    )
    with op.batch_alter_table('deployment_rollouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_rollouts_change_window_id'), ['change_window_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollouts_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollouts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollouts_release_run_id'), ['release_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollouts_requested_by_membership_id'), ['requested_by_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollouts_rollback_point_id'), ['rollback_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollouts_snapshot_hash'), ['snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollouts_status'), ['status'], unique=False)

    op.create_table('deployment_rollout_steps',
    sa.Column('rollout_id', sa.Uuid(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.String(length=1200), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rollout_id'], ['deployment_rollouts.id'], name=op.f('fk_deployment_rollout_steps_rollout_id_deployment_rollouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_rollout_steps')),
    sa.UniqueConstraint('rollout_id', 'step_key', name='uq_deployment_rollout_step_key')
    )
    with op.batch_alter_table('deployment_rollout_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_rollout_steps_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollout_steps_rollout_id'), ['rollout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollout_steps_sequence'), ['sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollout_steps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_rollout_steps_step_key'), ['step_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_rollout_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_rollout_steps_step_key'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollout_steps_status'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollout_steps_sequence'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollout_steps_rollout_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollout_steps_kind'))

    op.drop_table('deployment_rollout_steps')
    with op.batch_alter_table('deployment_rollouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_rollouts_status'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollouts_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollouts_rollback_point_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollouts_requested_by_membership_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollouts_release_run_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollouts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollouts_environment_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_rollouts_change_window_id'))

    op.drop_table('deployment_rollouts')
    with op.batch_alter_table('deployment_service_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_service_profiles_service_key'))
        batch_op.drop_index(batch_op.f('ix_deployment_service_profiles_environment_id'))

    op.drop_table('deployment_service_profiles')
    with op.batch_alter_table('deployment_secret_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_secret_references_secret_key'))
        batch_op.drop_index(batch_op.f('ix_deployment_secret_references_environment_id'))

    op.drop_table('deployment_secret_references')
    with op.batch_alter_table('deployment_change_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_change_windows_starts_at'))
        batch_op.drop_index(batch_op.f('ix_deployment_change_windows_environment_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_change_windows_ends_at'))
        batch_op.drop_index(batch_op.f('ix_deployment_change_windows_approved_by_membership_id'))

    op.drop_table('deployment_change_windows')
    with op.batch_alter_table('deployment_environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_environments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_environments_kind'))
        batch_op.drop_index(batch_op.f('ix_deployment_environments_environment_key'))
        batch_op.drop_index(batch_op.f('ix_deployment_environments_enabled'))
        batch_op.drop_index(batch_op.f('ix_deployment_environments_current_release_run_id'))

    op.drop_table('deployment_environments')
    # ### end Alembic commands ###
