"""evidence litigation discovery

Revision ID: 20260808_0014
Revises: 20260808_0013
Create Date: 2026-08-08 08:00:59.782245
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260808_0014'
down_revision: Union[str, None] = '20260808_0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_bundles',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=350), nullable=False),
    sa.Column('bundle_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', name='bundlestatus', native_enum=False), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=1000), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['security_users.id'], name=op.f('fk_evidence_bundles_created_by_user_id_security_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_evidence_bundles_matter_id_matters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_bundles'))
    )
    with op.batch_alter_table('evidence_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_bundles_bundle_type'), ['bundle_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_bundles_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_bundles_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_bundles_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_bundles_title'), ['title'], unique=False)

    op.create_table('evidence_witnesses',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('FACT', 'EXPERT', 'FORMAL', 'PARTY', 'UNKNOWN', name='witnesskind', native_enum=False), nullable=False),
    sa.Column('side', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=220), nullable=True),
    sa.Column('contact_ref', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_evidence_witnesses_matter_id_matters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_witnesses')),
    sa.UniqueConstraint('matter_id', 'normalized_name', name='uq_evidence_witness_matter_name')
    )
    with op.batch_alter_table('evidence_witnesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_witnesses_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_witnesses_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_witnesses_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_witnesses_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_witnesses_side'), ['side'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_witnesses_source'), ['source'], unique=False)

    op.create_table('litigation_issues',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('burden_side', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_litigation_issues_matter_id_matters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_litigation_issues')),
    sa.UniqueConstraint('matter_id', 'code', name='uq_litigation_issue_matter_code')
    )
    with op.batch_alter_table('litigation_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litigation_issues_burden_side'), ['burden_side'], unique=False)
        batch_op.create_index(batch_op.f('ix_litigation_issues_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_litigation_issues_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_litigation_issues_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_litigation_issues_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_litigation_issues_title'), ['title'], unique=False)

    op.create_table('evidence_gaps',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.Column('gap_key', sa.String(length=260), nullable=False),
    sa.Column('title', sa.String(length=350), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='gapstatus', native_enum=False), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['litigation_issues.id'], name=op.f('fk_evidence_gaps_issue_id_litigation_issues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_evidence_gaps_matter_id_matters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_gaps')),
    sa.UniqueConstraint('matter_id', 'gap_key', name='uq_evidence_gap_matter_key')
    )
    with op.batch_alter_table('evidence_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_gaps_gap_key'), ['gap_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_gaps_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_gaps_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_gaps_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_gaps_status'), ['status'], unique=False)

    op.create_table('evidence_items',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('kind', sa.Enum('COURT_FILING', 'COURT_ORDER', 'CONTRACT', 'CORRESPONDENCE', 'FINANCIAL', 'IDENTITY', 'PROPERTY', 'ELECTRONIC', 'PHOTO_VIDEO', 'WITNESS_STATEMENT', 'EXPERT', 'OTHER', name='evidencekind', native_enum=False), nullable=False),
    sa.Column('strength', sa.Enum('UNKNOWN', 'LOW', 'MEDIUM', 'HIGH', name='evidencestrength', native_enum=False), nullable=False),
    sa.Column('review_status', sa.Enum('AUTO', 'REVIEWED', 'REJECTED', name='evidencereviewstatus', native_enum=False), nullable=False),
    sa.Column('authenticity_checked', sa.Boolean(), nullable=False),
    sa.Column('admissibility_checked', sa.Boolean(), nullable=False),
    sa.Column('original_available', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_evidence_items_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_evidence_items_matter_id_matters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    sa.UniqueConstraint('matter_id', 'document_id', name='uq_evidence_item_matter_document')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_items_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_strength'), ['strength'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_title'), ['title'], unique=False)

    op.create_table('evidence_bundle_items',
    sa.Column('bundle_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section_label', sa.String(length=220), nullable=True),
    sa.Column('included_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['evidence_bundles.id'], name=op.f('fk_evidence_bundle_items_bundle_id_evidence_bundles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], name=op.f('fk_evidence_bundle_items_evidence_item_id_evidence_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_bundle_items')),
    sa.UniqueConstraint('bundle_id', 'evidence_item_id', name='uq_bundle_evidence_item')
    )
    with op.batch_alter_table('evidence_bundle_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_bundle_items_bundle_id'), ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_bundle_items_evidence_item_id'), ['evidence_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_bundle_items_position'), ['position'], unique=False)

    op.create_table('evidence_exhibits',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'MARKED', 'ADMITTED', 'REJECTED', name='exhibitstatus', native_enum=False), nullable=False),
    sa.Column('marked_date', sa.String(length=30), nullable=True),
    sa.Column('court_reference', sa.String(length=250), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], name=op.f('fk_evidence_exhibits_evidence_item_id_evidence_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_evidence_exhibits_matter_id_matters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_exhibits')),
    sa.UniqueConstraint('matter_id', 'label', name='uq_evidence_exhibit_matter_label')
    )
    with op.batch_alter_table('evidence_exhibits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_exhibits_evidence_item_id'), ['evidence_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_exhibits_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_exhibits_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_exhibits_status'), ['status'], unique=False)

    op.create_table('evidence_issue_links',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.Enum('SUPPORTS', 'CONTRADICTS', 'CONTEXT', name='evidencelinktype', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], name=op.f('fk_evidence_issue_links_evidence_item_id_evidence_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['litigation_issues.id'], name=op.f('fk_evidence_issue_links_issue_id_litigation_issues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_evidence_issue_links_matter_id_matters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_issue_links')),
    sa.UniqueConstraint('evidence_item_id', 'issue_id', 'link_type', name='uq_evidence_issue_link')
    )
    with op.batch_alter_table('evidence_issue_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_issue_links_evidence_item_id'), ['evidence_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_issue_links_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_issue_links_link_type'), ['link_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_issue_links_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_issue_links_source'), ['source'], unique=False)

    op.create_table('evidence_witness_links',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('witness_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=False),
    sa.Column('relationship', sa.String(length=160), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], name=op.f('fk_evidence_witness_links_evidence_item_id_evidence_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_evidence_witness_links_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['witness_id'], ['evidence_witnesses.id'], name=op.f('fk_evidence_witness_links_witness_id_evidence_witnesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_witness_links')),
    sa.UniqueConstraint('witness_id', 'evidence_item_id', name='uq_witness_evidence_link')
    )
    with op.batch_alter_table('evidence_witness_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_witness_links_evidence_item_id'), ['evidence_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_witness_links_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_witness_links_relationship'), ['relationship'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_witness_links_witness_id'), ['witness_id'], unique=False)

    op.create_table('witness_prep_questions',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('witness_id', sa.Uuid(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_item_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'USED', name='witnessprepstatus', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], name=op.f('fk_witness_prep_questions_evidence_item_id_evidence_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['litigation_issues.id'], name=op.f('fk_witness_prep_questions_issue_id_litigation_issues'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_witness_prep_questions_matter_id_matters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['witness_id'], ['evidence_witnesses.id'], name=op.f('fk_witness_prep_questions_witness_id_evidence_witnesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_witness_prep_questions'))
    )
    with op.batch_alter_table('witness_prep_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_witness_prep_questions_evidence_item_id'), ['evidence_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_witness_prep_questions_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_witness_prep_questions_matter_id'), ['matter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_witness_prep_questions_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_witness_prep_questions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_witness_prep_questions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_witness_prep_questions_witness_id'), ['witness_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('witness_prep_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_witness_prep_questions_witness_id'))
        batch_op.drop_index(batch_op.f('ix_witness_prep_questions_status'))
        batch_op.drop_index(batch_op.f('ix_witness_prep_questions_source'))
        batch_op.drop_index(batch_op.f('ix_witness_prep_questions_question_type'))
        batch_op.drop_index(batch_op.f('ix_witness_prep_questions_matter_id'))
        batch_op.drop_index(batch_op.f('ix_witness_prep_questions_issue_id'))
        batch_op.drop_index(batch_op.f('ix_witness_prep_questions_evidence_item_id'))

    op.drop_table('witness_prep_questions')
    with op.batch_alter_table('evidence_witness_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_witness_links_witness_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_witness_links_relationship'))
        batch_op.drop_index(batch_op.f('ix_evidence_witness_links_matter_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_witness_links_evidence_item_id'))

    op.drop_table('evidence_witness_links')
    with op.batch_alter_table('evidence_issue_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_issue_links_source'))
        batch_op.drop_index(batch_op.f('ix_evidence_issue_links_matter_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_issue_links_link_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_issue_links_issue_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_issue_links_evidence_item_id'))

    op.drop_table('evidence_issue_links')
    with op.batch_alter_table('evidence_exhibits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_exhibits_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_exhibits_matter_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_exhibits_label'))
        batch_op.drop_index(batch_op.f('ix_evidence_exhibits_evidence_item_id'))

    op.drop_table('evidence_exhibits')
    with op.batch_alter_table('evidence_bundle_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_bundle_items_position'))
        batch_op.drop_index(batch_op.f('ix_evidence_bundle_items_evidence_item_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_bundle_items_bundle_id'))

    op.drop_table('evidence_bundle_items')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_items_title'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_strength'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_review_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_matter_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_kind'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_document_id'))

    op.drop_table('evidence_items')
    with op.batch_alter_table('evidence_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_gaps_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_gaps_severity'))
        batch_op.drop_index(batch_op.f('ix_evidence_gaps_matter_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_gaps_issue_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_gaps_gap_key'))

    op.drop_table('evidence_gaps')
    with op.batch_alter_table('litigation_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litigation_issues_title'))
        batch_op.drop_index(batch_op.f('ix_litigation_issues_source'))
        batch_op.drop_index(batch_op.f('ix_litigation_issues_priority'))
        batch_op.drop_index(batch_op.f('ix_litigation_issues_matter_id'))
        batch_op.drop_index(batch_op.f('ix_litigation_issues_code'))
        batch_op.drop_index(batch_op.f('ix_litigation_issues_burden_side'))

    op.drop_table('litigation_issues')
    with op.batch_alter_table('evidence_witnesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_witnesses_source'))
        batch_op.drop_index(batch_op.f('ix_evidence_witnesses_side'))
        batch_op.drop_index(batch_op.f('ix_evidence_witnesses_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_evidence_witnesses_name'))
        batch_op.drop_index(batch_op.f('ix_evidence_witnesses_matter_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_witnesses_kind'))

    op.drop_table('evidence_witnesses')
    with op.batch_alter_table('evidence_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_bundles_title'))
        batch_op.drop_index(batch_op.f('ix_evidence_bundles_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_bundles_sha256'))
        batch_op.drop_index(batch_op.f('ix_evidence_bundles_matter_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_bundles_bundle_type'))

    op.drop_table('evidence_bundles')
    # ### end Alembic commands ###
